hitobito/hitobito

- .travis.yml
- README.md
- spec/models/event/date_spec.rb
- spec/support/crud_test_model.rb
Dieser PR sollte nicht nur #153 beheben, sondern bereits von Travis getestet werden. 
Die Tests werden mit MySQL und auf allen Rubies ausgeführt, die laut README unterstützt werden.
Hier werden nur die Tests von hitobito selbst ausgeführt. Einzelne Wagons brauchen eigene Konfigurationen.
> test on TravisCI

- app/abilities/person_ability.rb
- app/abilities/person_readables.rb
- app/controllers/full_text_controller.rb
- app/domain/person/full_text.rb
- spec/abilities/person_readables_spec.rb
- spec/domain/person/full_text_spec.rb
> admin can find deleted people on global search

- app/controllers/group/person_add_requests_controller.rb
- app/domain/group/deleted_people.rb
- app/domain/person/add_request/creator/base.rb
- app/helpers/person_add_requests_helper.rb
- app/models/person/add_request.rb
- app/views/group/person_add_requests/_list.html.haml
- spec/models/person/add_request_spec.rb
> Add request to deleted persons, add tests

- app/abilities/event/participation_ability.rb
- app/assets/stylesheets/hitobito/_typography.scss
- app/controllers/event/participations_controller.rb
- app/controllers/events_controller.rb
- app/helpers/event_participations_helper.rb
- app/jobs/event/cancel_participation_job.rb
- app/mailers/event/participation_mailer.rb
- app/models/event.rb
- app/models/event/course.rb
- app/models/person.rb
- app/views/events/_actions_show.html.haml
- app/views/events/_application_fields.html.haml
- app/views/events/_banner_signed_in.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- db/migrate/20161122144630_add_cancel_participation_enabled_to_event.rb
- db/schema.rb
- db/seeds/custom_contents.rb
- spec/mailers/event/participation_mailer_spec.rb
- spec/models/person_spec.rb
- spec/regressions/event/participations_controller_spec.rb
- spec/views/event/participations/_actions_show.html.haml_spec.rb
- spec/views/events/_action_show.html.haml_spec.rb
> Abmeldung von Anlass ermöglichen

- app/controllers/person/csv_imports_controller.rb
Windows 10 sends csv files as application/octet-stream...
> CSV import for Windows 10

- CHANGELOG.md
- Gemfile.lock
- app/models/event.rb
- app/models/event/course.rb
- app/models/event/role/helper.rb
- config/locales/models.de.yml
> Neue Rolle Helfer für Events

- .travis.yml
A test fails on Travis due to this missing dependency.
> Make sphinx available

- app/domain/export/ics/events.rb
- app/utils/duration.rb
- spec/domain/export/ics/events_spec.rb
Incorporates changes requested in https://github.com/hitobito/hitobito/pull/519
> Fixes #518 (review follow-up)

- app/assets/javascripts/modules/people/people_filter_attribute.js.coffee
- app/domain/person/filter/attributes.rb
- app/domain/person/filter/chain.rb
- app/helpers/people_filter_helper.rb
- app/models/person.rb
- app/views/people_filters/_attributes.html.haml
- app/views/people_filters/_form.html.haml
- config/locales/views.de.yml
- spec/domain/person/filter/attributes_spec.rb
- spec/models/person_spec.rb
> Filter people by attributes

- Gemfile.lock
- app/controllers/person/csv_imports_controller.rb
- app/controllers/roles_controller.rb
- app/views/person/csv_imports/define_mapping.html.haml
- app/views/roles/_details.js.haml
- app/views/roles/_type_select.html.haml
- app/views/roles/details.js.haml
- app/views/roles/role_types.js.haml
Was badly implemented, updating a role had automatically selected the default role, instead of the actually already set role, also details on role edit screen was not shown.
also sets default role for imports
> Feature/548 default roles, corrections

- app/assets/javascripts/modules/invoice_configs.js.coffee
- app/controllers/invoice_configs_controller.rb
- app/domain/invoice/payment_slip.rb
- app/models/concerns/payment_slips.rb
- app/models/invoice.rb
- app/models/invoice_config.rb
- app/views/invoice_configs/_attrs.html.haml
- app/views/invoice_configs/_general_fields.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- db/migrate/20181010135951_add_participant_number_internal_to_invoice_configs.rb
- db/schema.rb
- spec/domain/invoice/payment_slip_spec.rb
- spec/fabricators/invoice_fabricator.rb
- spec/fixtures/invoice_configs.yml
- spec/fixtures/invoices.yml
- spec/models/invoice_config_spec.rb
> Support internal participant number on invoices

- app/domain/import/person_importer.rb
- spec/controllers/person/csv_imports_controller_spec.rb
- spec/domain/import/person_export_import_spec.rb
- spec/domain/import/person_importer_spec.rb
https://ticket.puzzle.ch/projects/hitobito/work_packages/45800/activity
> fixes security issues #45800

- app/helpers/events_helper.rb
- app/helpers/groups_helper.rb
- spec/helpers/events_helper_spec.rb
- spec/helpers/groups_helper_spec.rb
duplicate led to missing xslx export
> correcting placing of helper methods (one duplicate)

- app/controllers/public_events_controller.rb
- app/decorators/event_decorator.rb
- app/helpers/public_events_helper.rb
- app/views/public_events/_attrs_primary.html.haml
- app/views/public_events/show.html.haml
- config/routes.rb
- spec/controllers/public_events_controller_spec.rb
- spec/decorators/event_decorator_spec.rb
> Public event page for external events

- app/controllers/groups_controller.rb
- app/jobs/export/subgroups_export_job.rb
- config/locales/views.de.yml
- spec/controllers/groups_controller_spec.rb
- spec/jobs/export/subgroups_export_job_spec.rb
> Async Subgroups Export

- app/domain/export/tabular/people/participations_households.rb
- app/jobs/export/event_participations_export_job.rb
- spec/jobs/export/event_participations_export_job_spec.rb
Household export options is presented for the people export on events, but is not handled, this should fix this.
> household export for events, fixes #494

- app/views/event/questions/_fields.html.haml
Precondition for hitobito/hitobito#835
> Allow wagons to insert custom fields into questions

- app/views/doorkeeper/authorizations/new.html.erb
- config/initializers/doorkeeper.rb
See https://github.com/doorkeeper-gem/doorkeeper/wiki/Authorization-Code-Flow
> Style consent screen to match layout

- app/controllers/full_text_controller.rb
- app/views/full_text/index.html.haml
- spec/controllers/full_text_controller_spec.rb
Fixes #512
My contribution to the PBS hackaton :)
> Show first tab with results

- app/views/roles/update.js.haml
- spec/controllers/roles_controller_spec.rb
> Really fix the display of roles after inline editing, and add test

- app/views/people/_qualifications.html.haml
Pre-requisite to the implementation of the latest requirement from hitobito/hitobito#741
> Allow wagons to define custom buttons for each qualification

- app/domain/export/ics/events.rb
- spec/domain/export/ics/events_spec.rb
Fixes the issues mentioned in https://github.com/hitobito/hitobito/issues/606#issuecomment-557800966 and therefore fixes #606
> ICal feed improvements

- app/views/doorkeeper/authorizations/new.html.erb
https://github.com/doorkeeper-gem/doorkeeper-openid_connect#nonces
> Add Support for nonce

- app/assets/stylesheets/hitobito/_variables.scss.erb
- config/settings.yml
Vorschlag zur Differenzierung von Produktions-, Test- und Entwicklungsumgebung. Vergleiche #643.
> Hintergrundfarbe abhängig von Umgebung

- app/assets/javascripts/modules/participation_lists.js.coffee
> Use global CSRF token when changing action in participation_lists form

- app/decorators/service_token_decorator.rb
- app/views/service_tokens/_form.html.haml
Prerequisite for an improved implementation of hitobito/hitobito_pbs#154
> Allow wagons to extend the list of service token scopes

- app/helpers/filter_navigation/people.rb
- spec/helpers/filter_navigation/people_spec.rb
fixes hitobito/hitobito_sbv#58
> Sort custom people filters by name

- app/domain/mail_relay/base.rb
- doc/e-mail/README.md
- spec/domain/mail_relay/base_spec.rb
- spec/domain/mail_relay/lists_spec.rb
- spec/fixtures/email/list.eml
- spec/fixtures/email/multiple.eml
- spec/fixtures/email/multiple_both.eml
- spec/fixtures/email/regular.eml
- spec/fixtures/email/simple.eml
Header is no longer set by mail server
> Remove support for X-Envelope-To header

- CHANGELOG.md
- app/domain/person/event_queries.rb
- app/models/event/participation.rb
- spec/decorators/person_decorator_spec.rb
- spec/regressions/people_controller_spec.rb
> Don't display past events in the upcoming events section on a person

- app/domain/mail_relay/bulk_mail.rb
- app/mailers/delivery_report_mailer.rb
- spec/domain/mail_relay/bulk_mail_spec.rb
- spec/mailers/delivery_report_mailer_spec.rb
> Use envelope_sender in delivery reports

- app/helpers/people_filter_helper.rb
- app/models/group.rb
- app/models/person.rb
- db/migrate/20201012121722_convert_large_varchars_to_text.rb
- db/migrate/20201012121723_convert_database_to_utf8mb4.rb
- db/schema.rb
- spec/models/person_spec.rb
> Convert large varchars to text

- spec/features/role_lists_controller_spec.rb
I've run the features specs on travis about 12 times and it never failed... Hope this fixes it, if not we'll have to look further into it.
Closes #1002
> Change click_button to find before click in features spec

- LICENSE
- README.md
Erstes Update des readme und license file. Gibt es noch weitere Badges welche wir noch aufnehmen sollen?
> Update readme license

- config/locales/models.de.yml
- config/locales/models.fr.yml
- config/locales/models.it.yml
- spec/domain/export/csv/people/participations_full_spec.rb
- spec/domain/export/tabular/people/participations_full_spec.rb
- spec/jobs/export/event_participations_export_job_spec.rb
Issue: hitobito/hitobito#946
Im Zusammenhang mit Youth-PR: hitobito/hitobito_youth#12
Die englische Übersetzung werde ich noch im Transifex anpassen.
> Generalize event particip. additional info label

- CHANGELOG.md
- app/controllers/event/participations_controller.rb
- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/event/answer.rb
- app/models/event/participation.rb
- app/models/event/question.rb
- app/views/event/answers/_fields.html.haml
- app/views/event/questions/_fields.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- db/migrate/20201113151157_add_checkbox_to_event_questions.rb
- db/schema.rb
- spec/controllers/event/participations_controller_spec.rb
- spec/controllers/events_controller_spec.rb
- spec/fixtures/event/questions.yml
- spec/models/event/answer_spec.rb
- spec/models/event/question_spec.rb
Fixes hitobito/hitobito_sjas#15
> Ermögliche Fragen, die nur eine Checkbox als Antwort haben

- CHANGELOG.md
- app/assets/javascripts/modules/contactables/contactable_address_field.js.coffee
- app/controllers/addresses_controller.rb
- app/domain/address/full_text_search.rb
- app/domain/search_strategies/sphinx.rb
- app/domain/search_strategies/sql.rb
- app/indices/address_index.rb
- app/javascript/javascripts/modules/remote_typeahead.js.coffee
- app/models/address.rb
- app/views/contactable/_address_fields.html.haml
- config/routes.rb
- config/settings.yml
- spec/controllers/addresses_controller_spec.rb
- spec/domain/address/full_text_search_spec.rb
- spec/features/addresses_controller_spec.rb
> Add address typeahead for supported countries

- db/migrate/20201105060840_enable_pkce.rb
See https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-PKCE-flow
> Enable OAuth PKCE flow for doorkeeper gem

- app/domain/synchronize/mailchimp/synchronizator.rb
- app/jobs/mailchimp_synchronization_job.rb
- spec/jobs/mailchimp_synchronization_job_spec.rb
> Avoid query methods for settings, add specs

- app/helpers/messages_helper.rb
- app/javascript/javascripts/modules/clickable_placeholders.js.coffee
- app/views/messages/letter/_fields.html.haml
- config/locales/views.de.yml
Fixes https://github.com/hitobito/hitobito_cvp/issues/93
> Make letter placeholders clickable

- app/domain/mail_relay/lists.rb
- app/helpers/mailing_list/unsubscribe_url.rb
- spec/domain/mail_relay/lists_spec.rb
- spec/helpers/mailing_list/unsubscribe_url_spec.rb
Update from [Pull Request](https://github.com/hitobito/hitobito/pull/645) by @adriananderegg
> Unsubscribe link update

- app/domain/messages/letter_dispatch.rb
- app/models/person.rb
- spec/domain/messages/letter_dispatch_spec.rb
- spec/models/person_spec.rb
Closes https://github.com/hitobito/hitobito_die_mitte/issues/105
> Adjust letter dispatch to only send to people with addresses,

- app/views/devise/sessions/_form.html.haml
> Stay on oauth page after login failure

- app/models/event.rb
- spec/models/event_spec.rb
> Validate presence of event name

- app/abilities/ability_dsl/base.rb
- app/abilities/event_ability.rb
- app/abilities/group_ability.rb
- app/abilities/person_ability.rb
- app/controllers/application_controller.rb
- app/controllers/devise/registrations_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/person/colleagues_controller.rb
- app/controllers/person/history_controller.rb
- app/controllers/person/invoices_controller.rb
- app/controllers/person/log_controller.rb
- app/controllers/person/messages_controller.rb
- app/helpers/sheet/person.rb
- app/helpers/sheet_helper.rb
- app/models/person.rb
- app/models/service_token.rb
- app/views/layouts/application.html.haml
- app/views/people/_actions_show.html.haml
- config/initializers/warden.rb
- db/seeds/support/person_seeder.rb
- doc/development/02_deployment.md
- spec/abilities/event_ability_spec.rb
- spec/abilities/group_ability_spec.rb
- spec/abilities/person_ability_spec.rb
- spec/controllers/devise/registrations_controller_spec.rb
> Adjust permissions and UI for people without roles

- Gemfile.lock
- app/controllers/messages/dispatches_controller.rb
- app/domain/messages/text_message_dispatch.rb
- app/jobs/messages/dispatch_job.rb
- app/jobs/messages/text_message_delivery_report_job.rb
- app/models/assignment.rb
- app/models/message.rb
- app/models/message/text_message.rb
- spec/domain/messages/text_message_dispatch_spec.rb
- spec/jobs/messages/text_message_delivery_report_job_spec.rb
fixes hitobito/hitobito_die_mitte#110
> Extract Task into BackgroundJob

- app/controllers/events_controller.rb
- spec/controllers/events_controller_spec.rb
Fixes hitobito/hitobito_insieme#92
> Remove extra nested attributes from permitted params

- app/javascript/stylesheets/hitobito/_form.scss
Fixes #1187
Not a very elegant solution but I don't know enough about (S)CSS to make it simpler.
> Fix #1187 Width of form content not responsive

- app/domain/messages/text_message_provider/aspsms.rb
- spec/domain/messages/text_message_provider/aspsms_spec.rb
Fixes hitobito/hitobito_die_mitte#116
> Send along Puzzle's ASPSMS affiliate id

- app/controllers/application_controller.rb
- app/helpers/sheet/person.rb
- app/views/layouts/application.html.haml
- app/views/people/_actions_show.html.haml
- spec/views/layout/application.html.haml_spec.rb
> Restore root user UI

- app/controllers/events_controller.rb
- app/domain/event/filter.rb
- spec/controllers/events_controller_spec.rb
- spec/fixtures/events.yml
The permissions were simply not checked in the list-view. Now they are.
I specifically extended the scope to still be a scope. 
Fixes #1214
> Check event permissions

- app/mailers/invoice_mailer.rb
- config/locales/models.de.yml
- config/locales/views.de.yml
- spec/mailers/invoice_mailer_spec.rb
> Use standard mailing headers when sending invoice

- app/serializers/event_participation_serializer.rb
- app/serializers/group_serializer.rb
- app/serializers/person_serializer.rb
- app/serializers/role_serializer.rb
- spec/serializers/event_participation_serializer_spec.rb
- spec/serializers/group_serializer_spec.rb
- spec/serializers/person_serializer_spec.rb
See hitobito/hitobito_die_mitte#176
> Rollen einer Gruppe in der API

- config/settings.yml
> Add postfinance provider to settings, refs: #1334

- app/models/invoice_config.rb
- app/models/payment_provider_config.rb
- db/migrate/20210727125632_create_payment_provider_config.rb
- db/schema.rb
- spec/fixtures/payment_provider_configs.yml
- spec/models/payment_provider_config_spec.rb
> Add PaymentProviderConfig model and migration, refs: #1335

- app/controllers/concerns/events/course_listing.rb
- app/domain/events/filter/groups.rb
- app/domain/events/filter/state.rb
- app/helpers/events_helper.rb
- app/javascript/javascripts/modules/multiselect_add_chips.js.coffee
- app/javascript/stylesheets/vendor/chosen-bootstrap.scss
- app/views/events/courses/_filter.html.haml
- app/views/events/courses/_group_filter.html.haml
- config/locales/views.de.yml
- spec/domain/events/filter/groups_spec.rb
- spec/domain/events/filter/state_spec.rb
Fixes #1347 
Merge together with hitobito/hitobito_youth#18 and hitobito/hitobito_pbs#202
> Course filter improvements

- app/views/events/_application_fields.html.haml
Rebased PR of #1034 
Thus closes #1034
> Add additional field for events, rebased

- CHANGELOG.md
- app/abilities/token_ability.rb
- spec/abilities/token_ability_spec.rb
- spec/controllers/people_controller_spec.rb
- spec/fixtures/service_tokens.yml
> Add show_full permission to service token, refs: #1355

- app/controllers/help_texts_controller.rb
- spec/controllers/help_texts_controller_spec.rb
> Save help text translation on create, refs: #1232

- app/controllers/invoice_configs_controller.rb
- app/controllers/payment_provider_configs/ini_letter_controller.rb
- app/helpers/payment_provider_configs_helper.rb
- app/models/concerns/encryptable.rb
- app/models/invoice_config.rb
- app/models/payment_provider_config.rb
- app/views/invoice_configs/_attrs.html.haml
- app/views/invoice_configs/_form.html.haml
- app/views/invoice_configs/_form_tabs.html.haml
- app/views/invoice_configs/_provider_fields.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- config/routes.rb
- spec/controllers/invoice_configs_controller_spec.rb
> Add ebics configuration to invoice letter form, refs: #1337

- app/javascript/stylesheets/hitobito/modules/_ui-datepicker.scss
This fixes the styling for the jQuery datepicker, by adding the css from a previous datepicker version.
Fixes #1202
> Fix jQuery datepicker css

- app/controllers/invoice_configs_controller.rb
- app/domain/donation.rb
- app/models/invoice_config.rb
- app/views/invoice_configs/_general_fields.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- db/migrate/20210810115706_add_variable_donation_amount_columns_to_invoice_config.rb
- spec/domain/donation_spec.rb
- spec/fixtures/invoice_configs.yml
Closes: https://github.com/hitobito/hitobito_die_mitte/issues/173
> Add donation domain class and invoice config fields for variable donation amount calculation, refs: die_mitte#173

- CHANGELOG.md
- app/controllers/messages_controller.rb
- app/domain/invoice/batch_create.rb
- app/helpers/invoice_articles_helper.rb
- app/javascript/javascripts/modules/invoice_articles.js.coffee
- app/models/invoice_article.rb
- app/models/invoice_config.rb
- app/models/invoice_item.rb
- app/views/invoice_lists/_invoice_articles.html.haml
- app/views/invoice_lists/_invoice_items.html.haml
- config/locales/views.de.yml
- db/migrate/20210812111610_add_variable_donation_flag_to_invoice_item.rb
- db/schema.rb
- spec/domain/invoice/batch_create_spec.rb
- spec/views/invoice_lists/_form.html.haml_spec.rb
- spec/views/invoices/_form.html.haml_spec.rb
Closes https://github.com/hitobito/hitobito_die_mitte/issues/181
Merge after #1366
> Integrate variable donation, refs: die_mitte#181

- app/domain/payment_provider.rb
- app/domain/payment_providers/xtc.rb
- app/domain/payment_providers/z54.rb
- doc/features/README.md
- doc/features/ebics-connection.md
- spec/domain/payment_provider_spec.rb
> Add z54 and xtc order type, refs #1338

- app/controllers/concerns/render_messages_exports.rb
- app/controllers/messages_controller.rb
- app/domain/export/tabular/messages/letters_with_invoice/list.rb
- app/domain/export/tabular/messages/letters_with_invoice/row.rb
- app/jobs/export/message_job.rb
- app/views/messages/_actions_show.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- spec/domain/export/tabular/messages/letters_with_invoice/list_spec.rb
- spec/domain/export/tabular/messages/letters_with_invoice/row_spec.rb
Closes https://github.com/hitobito/hitobito_die_mitte/issues/127
> Enable csv export for messages, refs die_mitte#127

- app/domain/invoice/payment_processor.rb
- app/domain/payment_provider.rb
- app/domain/payments/ebics_import.rb
- app/models/payment.rb
- config/locales/models.de.yml
- db/migrate/20210820123613_add_transaction_identifier_to_payments.rb
- db/schema.rb
- doc/features/ebics-connection.md
- spec/domain/payments/ebics_import_spec.rb
> Add ebics payment importer, refs: #1339

- app/jobs/payments/ebics_import_job.rb
- app/models/payment_provider_config.rb
- config/application.rb
- spec/jobs/payments/ebics_import_job_spec.rb
> Add recurring job for payments import

- db/seeds/support/location_seeder.rb
- doc/features/README.md
- doc/features/locations.md
- lib/tasks/db.rake
See hitobito/hitobito_svse#4
I do not quite understand why this is needed now and not earlier, but it surely removes unnecessary DB-load.
> Reduce Location Seeding

- CHANGELOG.md
- app/abilities/ability.rb
- app/abilities/event/invitation_ability.rb
- app/abilities/event_ability.rb
- app/controllers/event/applications_controller.rb
- app/controllers/event/invitations/decline_controller.rb
- app/controllers/event/invitations_controller.rb
- app/controllers/event/participations_controller.rb
- app/controllers/events_controller.rb
- app/helpers/dropdown/event/role_add.rb
- app/helpers/event_invitations_helper.rb
- app/helpers/sheet/event.rb
- app/helpers/sheet/event/invitation.rb
- app/models/event.rb
- app/models/event/application.rb
- app/models/event/invitation.rb
- app/models/person.rb
- app/views/event/invitations/_actions_index.html.haml
- app/views/event/invitations/_form.html.haml
- app/views/event/invitations/_list.html.haml
- app/views/events/_actions_show.html.haml
- app/views/events/_attrs.html.haml
- app/views/events/_banner_open_invitation.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- config/routes.rb
- db/migrate/20210929064827_create_event_invitations.rb
- db/schema.rb
- spec/controllers/event/invitations/decline_controller_spec.rb
- spec/controllers/event/invitations_controller_spec.rb
> Implement invitations to events, refs: #1276

- app/controllers/messages_controller.rb
- app/domain/export/pdf/messages/letter_with_invoice.rb
- app/domain/export/pdf/messages/letter_with_invoice/donation_confirmation.rb
- app/views/messages/_attrs.html.haml
- app/views/messages/letter/_fields.html.haml
- config/locales/views.de.yml
- db/migrate/20211004073131_add_donation_confirmation_to_messages.rb
- db/schema.rb
- spec/domain/export/pdf/messages/letter_with_invoice/donation_confirmation_spec.rb
Closes https://github.com/hitobito/hitobito_die_mitte/issues/174
> Donation confirmation, refs: die_mitte#174

- app/abilities/ability_dsl/constraints/event/invitation.rb
- app/abilities/event/invitation_ability.rb
- app/abilities/event_ability.rb
- app/models/event.rb
> Add invitation supported flag, refs: #1430

- app/domain/export/pdf/labels.rb
- spec/domain/export/pdf/labels_spec.rb
> Support households in labels export, refs #1454

- Wagonfile.development
- spec/helpers/layout_helper_spec.rb
- spec/support/work_around_docker_fs_bug.rb
Belongs to https://github.com/hitobito/development/pull/31
* Add Wagonfile to allow specifying wagons via env var WAGONS
* Work around docker bug to fix tests
* Don't load wagon twice when testing
Refs https://github.com/hitobito/hitobito/issues/1463
> Fix tests on docker setup, improve setup

- app/models/event/participation.rb
- app/models/group.rb
This PR collects fixes to N+1 queries, to get a head-start on #1487, maybe even resolving #1459 along the way.
> Reduce some N+1 Queries

- app/models/person.rb
Fixes hitobito/hitobito_kljb#13
> Handle Nickname-removal more gracefully

- images/s2i/root/opt/bin/install-nodejs
> Update nodejs in baseimage

- app/jobs/address/check_validity_job.rb
- app/jobs/address/import_job.rb
- spec/jobs/address/check_validity_job_spec.rb
- spec/jobs/address/import_job_spec.rb
Refs: https://github.com/hitobito/hitobito_sbv/issues/104
> Feature/sbv 104 Import and validate addresses only when configured

- app/domain/payment_provider.rb
- app/domain/payments/ebics_import.rb
- spec/domain/payment_provider_spec.rb
Siehe https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47372/activity/ für Kontext
> Fix ebics authentication error

- config/brakeman.ignore
We have two "issues" that are not solveable right now, so we ignore them for now.
> Update ignores for brakeman

- bin/active_wagon.rb
refs: https://github.com/hitobito/hitobito_sjas/issues/71
> Add youth wagon as sjas dependency

- app/models/role.rb
- spec/models/role_spec.rb
fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/45340/
> Deactivate archived before_save hook

- app/domain/export/pdf/messages/letter_with_invoice.rb
- app/domain/export/pdf/messages/letter_with_invoice/donation_confirmation.rb
- spec/domain/export/pdf/messages/letter_with_invoice/donation_confirmation_spec.rb
Closes https://github.com/hitobito/hitobito_die_mitte/issues/191
> Adjust donation confirmation pdf export

- app/domain/export/pdf/invoice/payment_slip_qr.rb
- spec/domain/export/pdf/invoice_spec.rb
- spec/domain/export/pdf/messages/letter_with_invoice_spec.rb
> Render esr number on invoice pdf export

- CHANGELOG.md
- app/abilities/group_ability.rb
- app/controllers/group/statistics_controller.rb
- app/controllers/groups_controller.rb
- app/domain/feature_gate.rb
- app/domain/group/demographic.rb
- app/helpers/groups_helper.rb
- app/helpers/sheet/group.rb
- app/helpers/sheet/group/statistic.rb
- app/javascript/stylesheets/hitobito/_main.scss
- app/javascript/stylesheets/hitobito/modules/_group.scss
- app/javascript/stylesheets/vendor/bootstrap.scss
- app/views/group/statistics/show.html.haml
- app/views/groups/statistics.html.haml
- config/locales/views.de.yml
- config/routes.rb
- config/settings.yml
- spec/abilities/group_ability_spec.rb
- spec/domain/group/demographic_spec.rb
* Adds FeatureGate class
* Fixes hitobito/hitobito_kljb#3
> Add demographics statistic to groups, refs #hitobito/hitobito_kljb#3

- app/indices/address_index.rb
- config/thinking_sphinx.yml
> Add numbers to address sphinx index

- app/controllers/application_controller.rb
- app/domain/auth.rb
- app/domain/permission_validator.rb
- app/models/event.rb
- app/models/group.rb
- config/locales/models.de.yml
- spec/controllers/events_controller_spec.rb
- spec/controllers/groups_controller_spec.rb
See https://help.puzzle.ch/#ticket/zoom/3608
> Validate group and event contact

- app/controllers/concerns/render_messages_exports.rb
- app/controllers/invoices_controller.rb
- app/helpers/dropdown/letter_with_invoice.rb
- config/locales/views.de.yml
- spec/controllers/invoices_controller_spec.rb
refs: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/45734/events/latest/
> Fix invoice letter export on invoice_list/invoices

- app/domain/export/tabular/people/person_row.rb
- app/helpers/dropdown/people_login.rb
- app/helpers/people_helper.rb
- app/helpers/table_displays/column.rb
- app/models/person.rb
- app/models/table_display/people.rb
- app/views/people/_attrs.html.haml
- config/initializers/table_displays.rb
- config/locales/models.de.yml
- config/locales/views.de.yml
- spec/controllers/people_controller_spec.rb
- spec/domain/export/tabular/people/table_displays_spec.rb
> Display login status

- app/controllers/concerns/two_factor.rb
- app/controllers/second_factor_authentication_controller.rb
- spec/controllers/second_factor_authentication_controller_spec.rb
> Stay logged in with 2FA

- app/views/events/_attachments.html.haml
- app/views/public_events/show.html.haml
- config/locales/views.de.yml
> Render attachments on public events

- app/abilities/invoice_ability.rb
- app/controllers/invoice_lists_controller.rb
- app/helpers/dropdown/invoice_sending.rb
- spec/controllers/invoice_lists_controller_spec.rb
> Check permissions on invoice list

- doc/architecture/09_entwurfsentscheidungen.md
> Document current architecture topics

- app/controllers/invoices_controller.rb
- spec/controllers/invoices_controller_spec.rb
> Bug#1536 suchfunktion um vornamen erweitern

- app/controllers/event/roles_controller.rb
- app/views/event/roles/new.html.haml
- config/locales/models.de.yml
- spec/controllers/event/roles_controller_spec.rb
> Issue#1220 teilnehmer rolle entfernen bei hinzufuegen einer leiterrolle

- .github/ISSUE_TEMPLATE/flakyspec.yml
- .github/workflows/tests.yml
Ich wollte eine Flaky Spec erfassen und habe kein passendes Template gefunden. Da wir oft vergessen, den Seed hinzuzufügen, habe ich mal ein Form dafür erstellt.
> Flaky specs as issue template

- app/domain/invoice/qrcode.rb
- app/domain/person/address.rb
- spec/domain/export/pdf/invoice_spec.rb
- spec/domain/invoice/qrcode_spec.rb
- spec/domain/messages/letter_dispatch_spec.rb
> Include company name in person address

- app/domain/contactable/address_validator.rb
- spec/domain/contactable/address_validator_spec.rb
Refs: https://github.com/hitobito/hitobito_insieme/issues/117
> Remove invalid tags on address validity check

- app/domain/address/full_text_search.rb
- app/javascript/javascripts/modules/contactables/contactable_address_field.js.coffee
- spec/domain/address/full_text_search_spec.rb
> Allow for number anywhere inside query

- app/domain/project_analyzer.rb
- config/initializers/sentry.rb
- spec/domain/project_analyzer_spec.rb
In order to extract from hit-digisus-lab-int the project "digisus-lab"
I added a HelperClass with added capabilities
So that Sentry can be instructed accordingly
> Extract determining the project and stage

- app/domain/export/tabular/groups/list.rb
- app/domain/export/tabular/groups/row.rb
- config/locales/models.de.yml
- spec/domain/export/csv/groups/list_spec.rb
Refs: zammad#363892
Merge this before: https://github.com/hitobito/hitobito_cevi/pull/87
> Add columns to group csv export

- app/decorators/event_decorator.rb
- app/helpers/events_helper.rb
- app/helpers/format_helper.rb
- app/javascript/stylesheets/hitobito/_base.scss
- app/views/event/answers/_fields.html.haml
- app/views/event/application_market/_waiting_list_link.html.haml
- app/views/event/participations/_attrs.html.haml
- app/views/event/participations/_precondition_warnings.html.haml
- app/views/events/_attrs_application.html.haml
- app/views/events/_attrs_primary.html.haml
- app/views/notes/_note.html.haml
- app/views/people/_attrs.html.haml
- spec/helpers/format_helper_spec.rb
> Remove simple format

- app/controllers/concerns/render_people_exports.rb
- app/controllers/people_controller.rb
- app/controllers/subscriptions_controller.rb
- app/helpers/dropdown/label_items.rb
- app/helpers/dropdown/people_export.rb
- app/jobs/export/labels_job.rb
- spec/controllers/people_controller_spec.rb
> Move label export to backgroundjob

- spec/features/messages_spec.rb
> Fix email verification flaky spec

- CHANGELOG.md
- app/abilities/role_ability.rb
- app/controllers/roles_controller.rb
- app/models/concerns/paranoia/future_deleted_at_scope.rb
- app/models/role.rb
- app/views/roles/_fields.html.haml
- config/locales/models.de.yml
- config/locales/models.fr.yml
- config/locales/models.it.yml
- spec/abilities/ability_dsl/user_context_spec.rb
- spec/domain/people/merger_spec.rb
- spec/domain/person/add_request/creator/event_spec.rb
- spec/domain/person/add_request/creator/group_spec.rb
- spec/domain/person/add_request/creator/mailing_list_spec.rb
- spec/domain/person/filter/role_spec.rb
- spec/jobs/event/participation_confirmation_job_spec.rb
- spec/models/mailing_list_spec.rb
- spec/models/person/add_request/ignored_approver_spec.rb
- spec/models/role_spec.rb
Closes: #1714 
Merge with:
- https://github.com/hitobito/hitobito_pbs/pull/226
- https://github.com/hitobito/hitobito_sww/pull/44
- https://github.com/hitobito/hitobito_sbv/pull/118
> Add fields to define role created_at and deleted_at manually

- app/views/messages/_attrs.html.haml
- app/views/messages/letter/_fields.html.haml
Used by: https://github.com/hitobito/hitobito_sww/pull/47
> Render extensions for letter

- app/controllers/event/participations_controller.rb
- app/jobs/event/participation_confirmation_job.rb
- app/jobs/event/participation_notification_job.rb
- spec/controllers/event/participations_controller_spec.rb
- spec/jobs/event/participation_confirmation_job_spec.rb
- spec/jobs/event/participation_notification_job_spec.rb
> Extract notification job into separate job

- spec/controllers/mailing_lists/imap_mails_controller_spec.rb
- spec/jobs/export/event_participations_export_job_spec.rb
- spec/jobs/export/events_export_job_spec.rb
- spec/jobs/export/people_export_job_spec.rb
- spec/jobs/export/subgroups_export_job_spec.rb
- spec/jobs/export/subscriptions_job_spec.rb
In an attempt to "unflakify" the specs, I added a sleep. When this passes, I want to reduce the sleep time and try again.
> Repair flaky async download specs

- CHANGELOG.md
- app/domain/invoice/filter.rb
- app/helpers/filter_helper.rb
- app/javascript/stylesheets/hitobito/modules/_invoice.scss
- app/models/invoice.rb
- app/views/invoices/_filter.html.haml
- config/locales/views.de.yml
- spec/controllers/invoices_controller_spec.rb
- spec/domain/invoice/filter_spec.rb
- spec/models/invoice_spec.rb
Closes: https://github.com/hitobito/hitobito_sww/issues/58
> Filter invoices by daterange instead of year

- app/helpers/table_displays/column.rb
This allows specific columns to be targeted by css
Refs: zammad#364184
> Add attribute-name to table display column

- app/controllers/payments_controller.rb
- app/domain/export/tabular/payments/list.rb
- app/domain/export/tabular/payments/row.rb
- app/domain/invoice/payment_processor.rb
- app/domain/payments/collection.rb
- app/domain/payments/ebics_import.rb
- app/models/payment.rb
- config/locales/models.de.yml
- db/migrate/20220803152519_add_status_to_payments.rb
- doc/features/ebics-connection.md
- lib/tasks/payment.rake
- spec/domain/export/csv/payments/list_spec.rb
- spec/domain/invoice/payment_processor_spec.rb
> Introduce payment status and export rake tasks

- config/brakeman.ignore
- config/initializers/cookies_serializer.rb
> Swap to json cookie serializer

- CHANGELOG.md
- app/domain/export/pdf/messages/letter_with_invoice/donation_confirmation.rb
- app/domain/invoice/batch_create.rb
- app/domain/payments/collection.rb
- spec/domain/invoice/batch_create_spec.rb
- spec/domain/payments/collection_spec.rb
Refs: https://github.com/hitobito/hitobito_die_mitte/issues/204
> Use median for variable donation

- app/decorators/group_setting_decorator.rb
- app/domain/export/pdf/address_renderers.rb
- app/domain/export/pdf/invoice/receiver_address.rb
- app/domain/export/pdf/messages/letter/header.rb
- app/helpers/group_settings_helper.rb
- app/models/group_setting.rb
- app/views/group_settings/_form.html.haml
- config/locales/models.de.yml
- spec/domain/export/pdf/messages/letter/header_spec.rb
Refs: https://github.com/hitobito/hitobito_sww/issues/59
> Adjustable address position

- app/views/invoice_lists/_form.html.haml
Refs: https://github.com/hitobito/hitobito_sww/issues/63
> Allow rendering extensions for invoice fields on invoice_list form

- CHANGELOG.md
- app/controllers/event/kind_categories_controller.rb
- app/controllers/event/kinds_controller.rb
- app/controllers/oauth/applications_controller.rb
- app/domain/event/precondition_checker.rb
- app/javascript/javascripts/modules/event_kind_preconditions.js.coffee
- app/javascript/stylesheets/hitobito/_main.scss
- app/javascript/stylesheets/hitobito/modules/_event_kinds.scss
- app/models/event/kind.rb
- app/models/event/kind_qualification_kind.rb
- app/views/event/kinds/_precondition_fields.html.haml
- config/locales/models.de.yml
- db/migrate/20220831081000_add_validity_to_event_kind_qualification_kinds.rb
- db/schema.rb
- spec/controllers/event/kinds_controller_spec.rb
- spec/domain/event/precondition_checker_spec.rb
> Add event preconditions validity

- app/domain/export/tabular/payments/list.rb
- app/domain/invoice/payment_processor.rb
- db/migrate/20220913111000_add_transaction_xml_to_payments.rb
- db/schema.rb
- spec/domain/invoice/payment_processor_spec.rb
> Add transaction_xml to payments

- app/domain/invoice/item_evaluation.rb
> Search for invoice item in relevant invoices

- app/controllers/invoices_controller.rb
- app/helpers/invoices_helper.rb
- app/models/invoice_list.rb
- spec/controllers/invoice_lists_controller_spec.rb
- spec/controllers/invoices_controller_spec.rb
> Update invoice list after invoice cancellation

- app/helpers/standard_form_builder.rb
- app/helpers/utility_helper.rb
- app/models/group.rb
Refs: https://github.com/hitobito/hitobito_sww/issues/68
> Allow extending group settings

- CHANGELOG.md
- app/controllers/invoices_controller.rb
- spec/controllers/invoices_controller_spec.rb
> Allow filtering of invoices by recipient.company_name (#1773)

- CHANGELOG.md
- app/abilities/person_ability.rb
- app/helpers/sheet/person.rb
Closes: https://github.com/hitobito/hitobito_die_mitte/issues/205
> Adjust condition to see peoples invoices tab with finance permission

- CHANGELOG.md
- app/domain/events/filter/groups.rb
- app/helpers/events_helper.rb
- spec/domain/events/filter/groups_spec.rb
Refs: https://github.com/hitobito/hitobito/issues/1813
> Consider globally visible flag in events filter

- app/controllers/event/qualifications_controller.rb
- app/models/event/role.rb
- spec/controllers/event/qualifications_controller_spec.rb
Refs https://github.com/hitobito/hitobito_jubla/issues/33
Preparation for https://github.com/hitobito/hitobito_pbs/issues/233 and a similar change for Cevi I assume
> Show helper in qualifications tab

- app/domain/event/filter.rb
- spec/domain/event/filter_spec.rb
> Fix events list pagination

- app/domain/export/pdf/invoice/invoice_information.rb
- spec/domain/export/pdf/invoice_spec.rb
Fixes: https://github.com/hitobito/hitobito_die_mitte/issues/211
> Use AddressRenderer for invoice information

- app/domain/export/pdf/messages/letter.rb
- spec/domain/export/pdf/messages/letter_spec.rb
closes hitobito/hitobito_die_mitte#203
> Order invoices in pdf by last_name

- app/domain/invoice/payment_processor.rb
- spec/domain/invoice/payment_processor_spec.rb
- spec/fixtures/invoices/camt.054-without-esr-reference.xml
Closes: https://github.com/hitobito/hitobito_cevi/issues/70
> Allow payment processor to import xmls without esr reference

- app/views/invoices/_actions_index.html.haml
- app/views/invoices/_form.html.haml
> Disable payment create button and remove issued_at from form

- app/decorators/group_decorator.rb
- app/models/group.rb
- app/views/groups/_form.html.haml
- spec/decorators/group_decorator_spec.rb
Renaming the method so it makes sense to extend it in the wagon. This change is required for https://github.com/hitobito/hitobito_pbs/pull/239
> Allowing extending the self registration roles and limiting them

- CHANGELOG.md
- app/controllers/events_controller.rb
- app/serializers/event_list_serializer.rb
- spec/controllers/events_controller_spec.rb
- spec/serializers/event_list_serializer_spec.rb
- spec/serializers/event_serializer_spec.rb
> Add attachments to events API show action

- app/models/event/question.rb
- config/locales/models.de.yml
- spec/models/event/question_spec.rb
> Validate event question text

- lib/templates/wagon/spec/features/event_external_application_spec.rb
- lib/templates/wagon/spec/features/event_participation_spec.rb
- lib/templates/wagon/spec/features/self_registration_spec.rb
- lib/templates/wagon/spec/fixtures/custom_content/translations.yml
- lib/templates/wagon/spec/fixtures/custom_contents.yml
- rubocop-must.yml
> Add certain features specs for wagons

- app/domain/person/filter/attributes.rb
- config/initializers/person_language.rb
- config/settings/test.yml
- spec/domain/person/filter/attributes_spec.rb
> Add language to people attribute filter

- app/models/service_token.rb
Refs: https://github.com/hitobito/hitobito_cevi/issues/90
> Add service token to dynamic user

- app/helpers/format_helper.rb
- spec/helpers/format_helper_spec.rb
refs hitobito/hitobito_insieme#132
> Fix FormatHelper#fnumber to return html_safe string

- app/models/invoice_item.rb
- spec/models/invoice_item_spec.rb
> Add after_update hook to recalculate invoice after change

- app/domain/messages/letter_dispatch.rb
- app/domain/messages/letter_with_invoice_dispatch.rb
- app/domain/person/address.rb
- app/models/invoice.rb
- app/models/message/letter_with_invoice.rb
- app/models/person.rb
- spec/controllers/invoices_controller_spec.rb
- spec/domain/export/pdf/messages/letter_with_invoice_spec.rb
Refs hitobito/hitobito_insieme#133
> Dynamic invoice address

- CHANGELOG.md
- app/models/event.rb
- app/models/event/course.rb
- app/views/event/application_market/_waiting_list_link.html.haml
- app/views/events/_application_fields.html.haml
- config/locales/models.de.yml
- db/migrate/20221214112552_remove_supports_applications_from_events.rb
- db/schema.rb
- doc/features/waiting_list.md
- spec/controllers/event/participations_controller_spec.rb
- spec/fabricators/event_fabricator.rb
- spec/fixtures/events.yml
> Revert supports applications changes

- app/abilities/group_ability.rb
- app/abilities/person_layer_writables.rb
- app/controllers/group/log_controller.rb
- app/decorators/paper_trail/version_decorator.rb
- app/domain/group/deleted_people.rb
- app/domain/person/filter/role.rb
- app/domain/search_strategies/base.rb
- app/helpers/sheet/group.rb
- app/helpers/sheet/group/log.rb
- app/jobs/event/participation_confirmation_job.rb
- app/models/paper_trail/version.rb
- app/models/role.rb
- app/views/group/log/index.html.haml
- config/locales/views.de.yml
- config/locales/views.en.yml
- config/locales/views.fr.yml
- config/locales/views.it.yml
- config/routes.rb
- spec/abilities/group_ability_spec.rb
- spec/controllers/group/log_controller_spec.rb
- spec/decorators/paper_trail/version_decorator_spec.rb
- spec/domain/group/deleted_people_spec.rb
- spec/domain/person/filter/role_spec.rb
> Group people log

- app/views/invoices/_actions_index.html.haml
- config/locales/views.de.yml
> Rename Invoices delete button

- CHANGELOG.md
- app/controllers/invoice_configs_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/invoice_mailer.rb
- app/views/invoice_configs/_attrs.html.haml
- app/views/invoice_configs/_email_fields.html.haml
- app/views/invoice_configs/_form.html.haml
- app/views/invoice_configs/_form_tabs.html.haml
- app/views/invoice_configs/_general_fields.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- db/migrate/20230117131844_add_sender_name_to_invoice_configs.rb
- spec/mailers/invoice_mailer_spec.rb
> Add sender email to invoice config

- CHANGELOG.md
- app/abilities/person_ability.rb
- app/domain/group/deleted_people.rb
- app/domain/search_strategies/base.rb
- spec/abilities/person_ability_spec.rb
- spec/domain/search_strategies/sphinx_spec.rb
- spec/domain/search_strategies/sql_spec.rb
Fixes: https://github.com/hitobito/hitobito_sww/issues/80
> Allow searching for deleted people

- app/controllers/event/participations_controller.rb
- app/domain/event/participant_assigner.rb
- config/locales/views.de.yml
- doc/modules/events/participations.md
- spec/controllers/event/participations_controller_spec.rb
- spec/regressions/events_controller_spec.rb
Fixes: https://github.com/hitobito/hitobito_sww/issues/99
Still not sure about "Anlassverwalter".. There might be better ideas but I wasn't able to find one so I'm tossing it into the room here :)
> Assign active state during save entry to show correct flash message

- app/controllers/concerns/authenticatable.rb
- app/controllers/event/participations_controller.rb
- app/helpers/people_helper.rb
- app/jobs/event/participation_confirmation_job.rb
- spec/controllers/event/participations_controller_spec.rb
> Fix event participation handling and confirmation mail

- CHANGELOG.md
- app/controllers/invoices_controller.rb
- app/domain/export/pdf/invoice.rb
- app/helpers/dropdown/invoices.rb
- app/jobs/export/invoices_job.rb
- spec/controllers/invoices_controller_spec.rb
- spec/features/group/invoices_controller_spec.rb
> Change to async download for invoices export

- app/domain/export/pdf/labels.rb
- spec/domain/export/pdf/labels_spec.rb
Fixes https://help.puzzle.ch/#ticket/zoom/5810
> Avoid printing company name twice on labels

- app/controllers/invoices/evaluations_controller.rb
Refs: https://github.com/hitobito/hitobito_sww/issues/81
> Pass dates for invoice evaluations

- app/javascript/javascripts/modules/profil_overlay.coffee
- app/javascript/javascripts/modules/profile_overlay.coffee
- app/javascript/packs/print.scss.erb
- app/javascript/stylesheets/hitobito/modules/_profil.scss
- app/views/people/_contact_data.html.haml
Userstory:
* User clicks on the picture of a profile
* A half transparent overlay appears in front of the page showing a large profile image
* User clicks anywhere on page
* Overlay closes again
> Allow user to enlarge profile image

- app/controllers/second_factor_authentication_controller.rb
- app/domain/people/one_time_password.rb
- app/helpers/people_helper.rb
- app/javascript/stylesheets/hitobito/modules/_totp.scss
- app/views/second_factor_authentication/new.html.haml
- config/locales/views.de.yml
> Changes to 2FA screen

- app/javascript/stylesheets/hitobito/_layout.scss
- app/views/layouts/_footer.html.haml
Fixes: https://github.com/hitobito/hitobito_sww/issues/125
> Make footer detail info collapsable

- app/controllers/groups/self_registration_controller.rb
- app/helpers/standard_form_builder.rb
- config/locales/views.de.yml
- spec/controllers/groups/self_registration_controller_spec.rb
fixes hitobito/hitobito_sww#119
> Self registration form fixes

- lib/tasks/hitobito.rake
> Modify `rake app:hitobito:roles` to show 2FA requirements

- CHANGELOG.md
- app/controllers/devise/hitobito/passwords_controller.rb
- app/views/devise/mailer/reset_password_instructions.html.haml
- config/locales/views.de.yml
- spec/controllers/devise/hitobito/passwords_controller_spec.rb
> Localize password reset instructions mail

- app/abilities/ability_dsl/base.rb
- app/abilities/ability_dsl/user_context.rb
- app/abilities/group_ability.rb
- app/abilities/person_fetchables.rb
- app/abilities/person_layer_writables.rb
- app/abilities/person_readables.rb
- app/abilities/role_ability.rb
- app/models/role/types.rb
- config/locales/models.de.yml
- doc/architecture/08_konzepte.md
- spec/abilities/group_ability_spec.rb
- spec/abilities/person_readables_spec.rb
- spec/abilities/person_writables_spec.rb
- spec/decorators/group_decorator_spec.rb
- spec/domain/role/type_list_spec.rb
- spec/features/roles_controller_spec.rb
- spec/models/role_spec.rb
- spec/serializers/group_serializer_spec.rb
- spec/support/group/top_group.rb
- spec/support/locales/test.de.yml
fixes hitobito/hitobito_glp#42
> Port permission cevi-unconfined_below -> core-see_invisible_from_above

- app/domain/export/pdf/address_renderers.rb
- app/domain/export/pdf/invoice/invoice_information.rb
- app/domain/export/pdf/invoice/receiver_address.rb
- app/domain/export/pdf/messages/letter/header.rb
- spec/domain/export/pdf/messages/letter/header_spec.rb
- spec/domain/export/pdf/messages/letter_spec.rb
> Use same offset for righthand address in letters and invoices

- app/controllers/event/participation_contact_datas_controller.rb
Based on: https://github.com/hitobito/hitobito/pull/2094
Fixes: #1969 
Merge with: https://github.com/hitobito/hitobito_youth/pull/31
> Allow using different contact data class for inheriting controllers

- app/abilities/person/add_request_ability.rb
- spec/abilities/person/add_request_ability_spec.rb
> Fix add_request reject ability

- Gemfile
- Gemfile.lock
- app/domain/group/deleted_people.rb
- app/domain/search_strategies/base.rb
- config/initializers/rack_profiler.rb
- spec/domain/group/deleted_people_spec.rb
> Add rack profiler and remove n+1

- app/controllers/messages_controller.rb
- app/helpers/dropdown/invoice_new.rb
- app/helpers/dropdown/letter_with_invoice_new.rb
- app/helpers/messages_helper.rb
- config/locales/views.de.yml
> Enable dynamic invoice items for letter with invoice

- app/domain/table_displays/people/layer_group_label_column.rb
- app/domain/table_displays/people/login_status_column.rb
> Add contact_data_visible as required attrs

- app/views/devise/sessions/_form.html.haml
Closes: https://github.com/hitobito/hitobito_svse/issues/71
Used for: https://github.com/hitobito/hitobito_svse/pull/74
> Add autofocus parameter for email

- app/controllers/event/register_controller.rb
- app/helpers/i18n_helper.rb
Refs: #2125 
Needed for: https://github.com/hitobito/hitobito_youth/pull/33
> Allow register controller to extend for different contact data classes

- app/helpers/dropdown/people_login.rb
> Check update password permission when rendering reset password button

- app/views/invoice_configs/_form.html.haml
- app/views/invoice_configs/_form_tabs.html.haml
Refs: https://github.com/hitobito/hitobito_sww/issues/146
Required for: https://github.com/hitobito/hitobito_sww/pull/157
> Allow to render extensions for invoice config form tabs

- app/models/person.rb
- spec/models/person_spec.rb
> Only show unique finance groups

- app/controllers/invoice_lists_controller.rb
- app/controllers/invoices_controller.rb
- app/controllers/messages_controller.rb
- app/views/invoice_lists/_form.html.haml
- app/views/invoices/_form.html.haml
- app/views/messages/letter_with_invoice/_fields.html.haml
Fixes: https://github.com/hitobito/hitobito_sww/issues/135
Also merge: https://github.com/hitobito/hitobito_sww/pull/156
> Add issued_at to invoice forms

- CHANGELOG.md
- app/controllers/invoices/by_article_controller.rb
- app/domain/invoice/item_evaluation.rb
- app/domain/payments/collection.rb
- spec/controllers/invoices/by_article_controller_spec.rb
- spec/domain/invoice/item_evaluation_spec.rb
- spec/domain/payments/collection_spec.rb
Fixes: https://github.com/hitobito/hitobito_sww/issues/136
> Exclude cancelled invoices for evaluation and by_article

- app/mailers/invoice_mailer.rb
- app/models/invoice_config.rb
- app/views/invoice_configs/_email_fields.html.haml
- config/locales/views.de.yml
- config/locales/views.fr.yml
- config/locales/views.it.yml
- spec/mailers/invoice_mailer_spec.rb
- spec/models/invoice_config_spec.rb
> sender_name invoice config in from header

- app/domain/export/pdf/invoice/articles.rb
- config/locales/views.de.yml
- config/locales/views.en.yml
- config/locales/views.fr.yml
- config/locales/views.it.yml
- spec/domain/export/pdf/invoice_spec.rb
Fixes: https://github.com/hitobito/hitobito_sww/issues/150
Also merge: https://github.com/hitobito/hitobito_sww/pull/159
> Only show total vat row for nonzero

- app/domain/mounted_attributes/config.rb
- app/domain/mounted_attributes/registry.rb
- app/models/concerns/mounted_attr.rb
- app/models/mounted_attribute.rb
- spec/models/concerns/mounted_attr_spec.rb
- spec/models/group_spec.rb
- spec/support/group/bottom_layer.rb
- spec/support/group/mounted_attrs_group.rb
Refs hitobito/hitobito_sac_cas#84
> Specs and fixes for MountedAttr

- app/models/group.rb
- app/models/group/types.rb
- app/views/groups/_general_fields.html.haml
- db/migrate/20231010140815_make_name_nullable_on_groups.rb
- db/schema.rb
- spec/models/group_spec.rb
fixes https://github.com/hitobito/hitobito_sac_cas/issues/96
> Introduce static_name for groups

- app/domain/export/pdf/invoice/payment_slip_qr.rb
- app/domain/invoice/qrcode.rb
- spec/domain/export/pdf/invoice_spec.rb
Closes: https://github.com/hitobito/hitobito_sww/issues/145
Merge this after: https://github.com/hitobito/hitobito_sww/pull/163
> Use open_amount for payment slip

- app/javascript/javascripts/modules/remote_typeahead.js.coffee
- spec/features/person/person_typeahead_spec.rb
> add icon after highlighting label in search result 

- app/controllers/devise/hitobito/sessions_controller.rb
- app/controllers/groups/self_inscription_controller.rb
- app/helpers/i18n_helper.rb
- app/models/concerns/i18n_enums.rb
- app/models/person.rb
- app/models/person/devise_overrides.rb
- app/views/devise/sessions/_form.html.haml
- app/views/groups/self_inscription/_form.html.haml
- app/views/public_events/show.html.haml
- config/initializers/devise.rb
- config/locales/views.de.yml
- doc/modules/04_auth.md
- spec/controllers/devise/hitobito/sessions_controller_spec.rb
- spec/controllers/devise/tokens_controller_spec.rb
- spec/features/email_verification_spec.rb
- spec/features/group/invoices_controller_spec.rb
- spec/features/login_spec.rb
- spec/models/concerns/i18n_enums_spec.rb
- spec/spec_helper.rb
- spec/support/i18n_helpers.rb
Refs hitobito/hitobito_sac_cas#119
> Configurable login attrs, extensible self-inscription views

- app/controllers/concerns/two_factor.rb
- spec/controllers/devise/hitobito/sessions_controller_spec.rb
> Fix remember me for 2fa

- app/controllers/crud_controller.rb
- app/controllers/roles_controller.rb
- spec/controllers/roles_controller_spec.rb
> Terminate role immediately if delete_on is in the past

- app/models/sequence.rb
- db/migrate/20231115131813_create_sequences.rb
- spec/models/sequence_spec.rb
refs hitobito/hitobito_sac_cas#98
> Add sequence model/table

- CHANGELOG.md
- app/domain/people/cleanup_finder.rb
- app/domain/people/destroyer.rb
- app/domain/people/minimizer.rb
- app/jobs/people/cleanup_job.rb
- app/models/event/participation.rb
- app/models/person.rb
- app/models/role.rb
- config/settings.yml
- db/migrate/20230926105011_add_minimized_at_to_people.rb
- db/schema.rb
- spec/domain/people/cleanup_finder_spec.rb
- spec/domain/people/destroyer_spec.rb
- spec/models/role_spec.rb
Closes: #2106 
Also merge: https://github.com/hitobito/hitobito_youth/pull/36
> Automated people data purge

- app/controllers/roles_controller.rb
- spec/features/roles/future_roles_spec.rb
- spec/features/roles_controller_spec.rb
- spec/spec_helper.rb
> Destroy roles when Bis is in the past

- CHANGELOG.md
- app/jobs/event/participation_cleanup_job.rb
- config/settings.yml
- lib/tasks/delayed_jobs.rake
- spec/jobs/event/participation_cleanup_job_spec.rb
> Add cleanup job for participations

- app/controllers/groups/self_registration_controller.rb
- app/models/self_registration.rb
- app/models/self_registration/housemate.rb
- app/models/self_registration/main_person.rb
- app/views/groups/self_registration/_main_person.html.haml
- spec/features/self_registration_spec.rb
- spec/models/self_registration/housemate_spec.rb
- spec/models/self_registration_spec.rb
fixes hitobito/hitobito_sac_cas#164
> Properly validate person and role in self registration

- CHANGELOG.md
- app/abilities/group_ability.rb
- app/controllers/people/manual_deletions_controller.rb
- app/views/group/deleted_people/_list.html.haml
- app/views/people/manual_deletions/_show.html.haml
- app/views/people/manual_deletions/show.js.haml
- config/locales/views.de.yml
- config/routes.rb
- config/settings.yml
- spec/abilities/group_ability_spec.rb
- spec/controllers/people/manual_deletions_controller_spec.rb
- spec/domain/people/cleanup_finder_spec.rb
Fixes: #2105 
Based on: https://github.com/hitobito/hitobito/pull/2229
> Add manual deletion dialog

- app/components/steps_component.rb
- app/models/self_registration.rb
- app/models/self_registration/housemate.rb
- app/models/self_registration/main_person.rb
- app/models/self_registration/person.rb
- app/views/groups/self_registration/_main_person.html.haml
- spec/features/self_registration_spec.rb
- spec/models/self_registration/housemate_spec.rb
- spec/models/self_registration/main_person_spec.rb
> Use Attributes API

- app/models/role.rb
- spec/models/role_spec.rb
> Ignore deleted roles in role#outdated?

- app/controllers/roles_controller.rb
- spec/features/roles_controller_spec.rb
> Do not try to destroy non persisted role

- app/controllers/full_text_controller.rb
- app/javascript/stylesheets/hitobito/_layout.scss
- app/views/full_text/index.html.haml
- app/views/layouts/_footer.html.haml
- spec/features/quicksearch_spec.rb
> Fix bootstrap tabs for full text search results

- app/views/people/_roles.html.haml
- app/views/people/_roles_aside.html.haml
- spec/features/roles/future_roles_spec.rb
> Only render primary_group toggle link for active roles

- app/controllers/roles/terminations_controller.rb
- app/helpers/standard_form_builder.rb
- app/helpers/terminations_helper.rb
- app/views/roles/terminations/_modal_form.html.haml
- spec/controllers/roles/terminations_controller_spec.rb
- spec/features/roles/terminations_spec.rb
- spec/helpers/standard_form_builder_spec.rb
- spec/views/roles/terminations/_modal_form.html.haml_spec.rb
fixes hitobito/hitobito_sac_cas#200
> Role terminations: allow date input only when role.delete_on is unset

- app/controllers/person/subscriptions_controller.rb
- app/helpers/mailing_lists_helper.rb
- app/views/mailing_lists/_list.html.haml
- app/views/person/subscriptions/index.html.haml
- spec/controllers/person/subscriptions_controller_spec.rb
- spec/features/mailing_lists_spec.rb
- spec/views/mailing_lists/_list.html.haml_spec.rb
- spec/views/person/subscriptions/index.html.haml_spec.rb
> Do not render mailing list link when no read permission

- CHANGELOG.md
- app/jobs/people/duplicate_locator_job.rb
- app/models/person.rb
- app/models/self_registration.rb
- spec/controllers/groups/self_registration_controller_spec.rb
- spec/jobs/people/duplicate_locator_job_spec.rb
- spec/models/person_spec.rb
- spec/spec_helper.rb
> Check for duplication entries when creating Person

- app/helpers/events_helper.rb
- app/helpers/layout_helper.rb
- app/javascript/stylesheets/hitobito/_form.scss
- app/javascript/stylesheets/hitobito/_layout.scss
- app/javascript/stylesheets/hitobito/_navigation.scss
- app/javascript/stylesheets/hitobito/_oauth-dialog.scss
- app/javascript/stylesheets/hitobito/_table.scss
- app/views/changelog/index.html.haml
- app/views/event/participations/_list.html.haml
- app/views/events/_attrs_application.html.haml
- app/views/events/_attrs_primary.html.haml
- app/views/group/person_add_requests/_list.html.haml
- app/views/layouts/_footer.html.haml
- app/views/public_events/_attrs_primary.html.haml
- app/views/public_events/show.html.haml
- spec/controllers/people_controller_spec.rb
- spec/decorators/group_decorator_spec.rb
- spec/decorators/role_decorator_spec.rb
- spec/domain/help_texts/renderer_spec.rb
- spec/helpers/layout_helper_spec.rb
> fix reported issues from cevi and other reported issues

- CHANGELOG.md
- app/controllers/person/subscriptions_controller.rb
- app/helpers/mailing_lists_helper.rb
- app/views/person/subscriptions/index.html.haml
- spec/controllers/person/subscriptions_controller_spec.rb
- spec/views/person/subscriptions/index.html.haml_spec.rb
> Group mailing lists by layer

- app/helpers/sheet/group.rb
Fixes https://github.com/hitobito/hitobito/issues/2360#issuecomment-1896914751
> Remove blank line in root group sheet

- app/controllers/groups_controller.rb
- app/models/group.rb
- app/views/groups/_general_fields.html.haml
- spec/controllers/groups_controller_spec.rb
- spec/views/groups/_form.html.haml_spec.rb
> Disable name and short_name for static_name groups

- app/helpers/mailing_lists_helper.rb
- spec/features/mailing_lists_spec.rb
- spec/views/mailing_lists/_list.html.haml_spec.rb
- spec/views/person/subscriptions/index.html.haml_spec.rb
> Adjust name formatter to use show instead of read

- .rubocop.yml
- app/domain/people/cleanup_finder.rb
- app/jobs/job_manager.rb
- app/jobs/people/cleanup_job.rb
- config/settings.yml
- spec/domain/people/cleanup_finder_spec.rb
- Move exclusion-criterion from job into loader
- Make durations consistent within cutoff-settings
- Disable automatic cleaning by default
see hitobito/hitobito_insieme#151
> Cleanup of People::Cleanup

- config/initializers/devise.rb
- spec/features/password_reset_spec.rb
This also respects 2FA, if configured.
> Invoke the full sign-in after PW-reset

- .github/workflows/tests.yml
- app/controllers/hitobito_log_entries_controller.rb
- app/helpers/hitobito_log_entries_helper.rb
- app/helpers/sheet/hitobito_log_entry.rb
- app/helpers/sheet/tab.rb
- app/models/hitobito_log_entry.rb
- app/utils/hitobito_logger.rb
- app/views/hitobito_log_entries/_list.html.haml
- config/routes.rb
- db/migrate/20240119120948_change_mailing_lists_subscribable.rb
- db/migrate/20240126100757_change_hitobito_log_entries.rb
- db/schema.rb
- db/seeds/support/hitobito_log_entry_seeder.rb
- spec/controllers/hitobito_log_entries_controller_spec.rb
- spec/features/hitobito_log_entries_spec.rb
- spec/fixtures/hitobito_log_entries.yml
- spec/utils/hitobito_logger_spec.rb
fixes hitobito/hitobito_sac_cas#232
> HitobitoLogEntry: change category to text, add payload

- spec/domain/messages/letter_dispatch_spec.rb
This fixes specs in one file.
This does not:
- add a Specs for Person::Address covering/describing the conditional
- touch others Specs where this might be an issue
- touch the Fabricator that generates the country-code
Discuss!
> Make spec consistent again

- CHANGELOG.md
- app/helpers/invoices_helper.rb
- app/models/invoice.rb
- app/models/invoice_list.rb
- app/models/payment.rb
- config/locales/models.de.yml
- db/migrate/20240214074832_change_reference_and_txn_id_uniqueness_on_payments.rb
- db/schema.rb
- spec/models/invoice_list_spec.rb
- spec/models/invoice_spec.rb
- spec/models/payment_spec.rb
In order to quicky search and filter for partially paid and overpaid invoices, two new states are introduced:
- partial
- excess
fixes hitobito/hitobito_sww#38
> Show more invoice states

- app/helpers/standard_form_builder.rb
- app/javascript/stylesheets/hitobito/_form.scss
- app/views/contactable/_address_fields.html.haml
- app/views/person/households/_fields.html.haml
> fix width of plz and city fields

- config/locales/models.de.yml
fixes hitobito/hitobito_sac_cas#293
> Change i18n of SelfRegistrationReason

- app/domain/roles/termination.rb
- app/helpers/terminations_helper.rb
- app/views/roles/terminations/_modal_form.html.haml
- app/views/roles/terminations/_role.html.haml
- config/locales/views.de.yml
- spec/domain/roles/termination_spec.rb
- spec/features/roles/terminations_spec.rb
- spec/helpers/terminations_helper_spec.rb
fixes hitobito/hitobito_sac_cas#330
> Improve UX of terminations dialog

- app/domain/export/pdf/messages/letter.rb
- app/views/roles/_fields.html.haml
- app/views/roles/_label.html.haml
- config/locales/views.de.yml
- config/settings.yml
see #2401
This enables wagons to override parts a little more fine-grained.
> Repair some overrides

- app/components/steps_component.rb
refs https://github.com/hitobito/hitobito_sac_cas/issues/345, https://github.com/hitobito/hitobito_sac_cas/issues/346, https://github.com/hitobito/hitobito_sac_cas/issues/347
> StepsComponent: wrap submit_button in div.btn-group, fixes layout issue

- app/views/event/application_market/_popover_waiting_list.html.haml
fixes hitobito/hitobito_jemk#20
> Fix JEMK camp application market with participants on waiting list

- app/domain/mail_relay/address_list.rb
- spec/domain/mail_relay/address_list_spec.rb
fixes hitobito/hitobito_sac_cas#401
> Fix MailRelay::AddressList#additional_emails when called for new records

- spec/domain/search_strategies/sphinx_spec.rb
- spec/domain/search_strategies/sql_spec.rb
- spec/fixtures/addresses.yml
Fixes https://trello.com/c/YCXVKR6X/332-adressverzeichnis-specs-erg%C3%A4nzen
> Add address lookup tests

- CHANGELOG.md
- app/abilities/json_api/event_ability.rb
- app/abilities/token_ability.rb
- app/controllers/json_api/events_controller.rb
- app/controllers/json_api/groups_controller.rb
- app/models/event.rb
- app/resources/event_resource.rb
- app/resources/group_resource.rb
- app/resources/types.rb
- config/routes.rb
- doc/development/05_json_api.md
- spec/abilities/token_ability_spec.rb
- spec/api/events/index_spec.rb
- spec/api/events/show_spec.rb
- spec/models/event_spec.rb
- spec/resources/events/reads_spec.rb
- spec/support/graphiti/schema.json
fixes hitobito/hitobito_sac_cas#229
> Add events to json_api

- app/helpers/person_duplicates_helper.rb
- app/helpers/table_helper.rb
- app/javascript/stylesheets/hitobito/_table.scss
- app/views/event/participations/_attrs.html.haml
- app/views/mailing_lists/_form.html.haml
- app/views/shared/_grouped_table.html.haml
- spec/helpers/table_helper_spec.rb
> fix reported ui issues

- app/javascript/javascripts/modules/async_downloads.js.coffee
- spec/features/group/invoices_controller_spec.rb
> Toggle the correct css hidden class after turbo changes

- app/domain/export/pdf/participation/section.rb
- config/initializers/table_displays.rb
- spec/domain/export/pdf/participation/person_and_event_spec.rb
- spec/domain/export/pdf/participation/section_spec.rb
> Allow to display and export additional information

- app/domain/event/participant_assigner.rb
- app/jobs/event/participation_confirmation_job.rb
- spec/jobs/event/participation_confirmation_job_spec.rb
See: https://github.com/hitobito/hitobito/pull/2483
> Send approval mail regardless of participation status

- app/controllers/concerns/nestable.rb
- app/controllers/invoices/evaluations_controller.rb
- app/controllers/invoices_controller.rb
- app/controllers/payment_processes_controller.rb
- app/helpers/navigation_helper.rb
- app/helpers/sheet/invoice.rb
- app/helpers/sheet/invoice_list.rb
- app/helpers/sheet/payment_process.rb
- app/views/invoices/_nav_left.html.haml
> Correct nesting of Invoices in InvoiceLists and Groups

- app/components/application_component.rb
- app/components/steps_component.html.haml
- app/components/steps_component.rb
- app/components/steps_component_controller.js
- app/views/groups/self_registration/_fields.html.haml
- app/views/groups/self_registration/_form.html.haml
- app/views/groups/self_registration/_main_person.html.haml
- lib/templates/wagon/spec/features/self_registration_spec.rb
- spec/components/steps_component_spec.rb
- spec/features/self_registration_spec.rb
- spec/spec_helper.rb
- spec/support/view_helpers.rb
- spec/support/views/groups/self_registration/_first_step.html.haml
- spec/support/views/groups/self_registration/_second_step.html.haml
- spec/support/views/groups/self_registration/_third_step.html.haml
fixes hitobito/hitobito_sac_cas#284
> Fix StepComponent navigation

- app/models/person.rb
see: https://github.com/hitobito/hitobito_sac_cas/pull/387
> Allow adjusting person language constant

- app/views/events/_attrs_primary.html.haml
> Change event attrs to display location correctly

- app/views/person/history/index.html.haml
- config/locales/models.de.yml
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/261
> Enable rendering extensions after qualification table

- app/views/person/csv_imports/new.html.haml
The upload-form was not advancing to the next step. without turbo, it worked again fine. I did not do a full research on this.
> Disable turbo on (person/csv-import) upload-form

- app/models/event/course.rb
- app/views/person/history/_events.html.haml
- app/views/person/history/index.html.haml
- config/locales/views.de.yml
- spec/models/event/course_spec.rb
refs hitobito/hitobito_sac_cas#318
> Show qualified in person history events

- app/views/payment_processes/new.html.haml
- app/views/payment_processes/show.html.haml
- spec/features/payment_process_spec.rb
> Bugfix: submit payment process form without turbo

- Gemfile
- Gemfile.lock
- app/abilities/json_api/group_ability.rb
- app/resources/group_resource.rb
- spec/abilities/json_api/group_ability_spec.rb
> Fix swagger gui try-out feature

- .pryrc
- CHANGELOG.md
- app/abilities/invoice_ability.rb
- app/abilities/json_api/invoice_ability.rb
- app/abilities/token_ability.rb
- app/controllers/json_api/invoices_controller.rb
- app/controllers/json_api/people_controller.rb
- app/models/invoice_item.rb
- app/resources/application_resource.rb
- app/resources/invoice_item_resource.rb
- app/resources/invoice_resource.rb
- config/routes.rb
- spec/abilities/invoice_ability_spec.rb
- spec/abilities/json_api/invoice_ability_spec.rb
- spec/abilities/token_ability_spec.rb
- spec/api/invoices/index_spec.rb
- spec/api/invoices/show_spec.rb
- spec/api/invoices/update_spec.rb
- spec/resources/invoice/reads_spec.rb
- spec/resources/invoice/writes_spec.rb
- spec/support/graphiti/schema.json
refs hitobito/hitobito_sac_cas#338
> Add invoices to json api

- app/resources/event/course_resource.rb
- app/resources/event_resource.rb
- app/resources/person/name_resource.rb
- spec/api/events/index_spec.rb
- spec/resources/events/course/reads_spec.rb
- spec/resources/events/reads_spec.rb
- spec/resources/person/name/reads_spec.rb
- spec/support/graphiti/schema.json
refs hitobito/hitobito_sac_cas#431
> Add additional attributes to event resource

- app/views/person/csv_imports/define_mapping.html.haml
> Un-turbo-ize the CSV-Import mapping/upload

- app/views/events/_attrs_application.html.haml
Ergänzung zu hitobito/hitobito_sac_cas#353
> Fix course minimum age

- app/domain/export/csv/generator.rb
- spec/domain/export/csv/generator_spec.rb
fixes hitobito/hitobito_sac_cas#271
> Make PeopleController tabular export customizable in subclasses

- app/jobs/event/participation_cleanup_answers_job.rb
- spec/fabricators/event/answer_fabricator.rb
- spec/jobs/event/participation_cleanup_answers_job_spec.rb
refs hitobito/hitobito_sac_cas#367
> Auto delete outdated event_answers via settings

- app/helpers/mounted_attrs/enum_select.rb
- app/views/mailing_lists/_form.html.haml
- app/views/mounted_attributes/_form_tabs.html.haml
- app/views/subscriber/filter/_show.html.haml
- spec/views/mailing_lists/_form.html.haml_spec.rb
- spec/views/mounted_attributes/_form_tabs.html.haml_spec.rb
- spec/views/subscriber/filter/_show.html.haml_spec.rb
fixes hitobito/hitobito_sac_cas#413
> Render form fields depending on user permissions

- app/controllers/person/households_controller.rb
- app/views/person/households/_fields.html.haml
- spec/controllers/person/households_controller_spec.rb
- spec/features/person/people_controller_spec.rb
fixes hitobito/hitobito_sac_cas#424
> Person household: on adding when invalid show errors and prevent adding

- lib/tasks/dev.rake
especially if being run from a wagon...
> Create the tmp-dir, which might not exist

- app/abilities/group_based_fetchables.rb
- app/abilities/group_based_readables.rb
- app/abilities/group_details_readables.rb
- app/abilities/group_readables.rb
- app/abilities/json_api/contact_account_ability.rb
- app/abilities/person_layer_writables.rb
- app/abilities/person_readables.rb
- app/resources/group_resource.rb
- spec/abilities/group_detail_readables_spec.rb
- spec/abilities/group_readables_spec.rb
- spec/abilities/json_api/contact_account_ability_spec.rb
- spec/decorators/group_decorator_spec.rb
- spec/domain/role/type_list_spec.rb
- spec/features/person/people_filter_spec.rb
- spec/features/roles/future_roles_spec.rb
- spec/features/roles_controller_spec.rb
- spec/models/role_spec.rb
- spec/resources/group/reads_spec.rb
- spec/resources/phone_number/reads_spec.rb
- spec/serializers/group_serializer_spec.rb
- spec/spec_helper.rb
- spec/support/graphiti/schema.json
- spec/support/group/top_group.rb
- spec/support/locales/test.de.yml
- spec/support/locales/test.fr.yml
> JsonApi: define contact accounts sideloads on GroupResource

- app/controllers/people_controller.rb
- app/controllers/subscriptions_controller.rb
- app/domain/country.rb
- app/domain/export/tabular/base.rb
- app/helpers/dropdown/people_export.rb
- spec/domain/country_spec.rb
- spec/domain/export/tabular/base_spec.rb
- spec/helpers/dropdown/people_export_spec.rb
fixes hitobito/hitobito_sac_cas#427
> Changes for tabular customizations from wagons

- app/views/events/_general_fields.html.haml
- config/locales/views.de.yml
refs hitobito/hitobito_sac_cas#355
> Add tooltip to event kind inheritance link

- .gitignore
- app/decorators/qualification_decorator.rb
- app/domain/event/qualifier/calculator.rb
- app/domain/qualifications/list.rb
- spec/controllers/person/history_controller_spec.rb
- spec/decorators/qualification_decorator_spec.rb
- spec/domain/event/qualifier/calculator_spec.rb
- spec/domain/qualifications/list_spec.rb
refs hitobito/hitobito_sac_cas#332
> Calculate open training days only *after* qualification date

- app/controllers/person/query_controller.rb
- app/domain/search_strategies/sql_condition_builder.rb
- app/domain/search_strategies/sql_condition_builder/matcher.rb
refs hitobito/hitobito_sac_cas#477
> Extract matcher from sql_condition_builder to support custom field logic

- app/javascript/javascripts/modules/popover_handler.js
refs hitobito/hitobito_sac_cas#375
> Support client validations in popover forms

- app/abilities/person_readables.rb
- spec/domain/search_strategies/sql_spec.rb
Refs hitobito/hitobito_sac_cas#384
> Avoid expensive joins

- app/controllers/event/attachments_controller.rb
- app/helpers/events_helper.rb
- app/models/event/attachment.rb
- app/models/event/role.rb
- app/views/event/attachments/_attachment.html.haml
- app/views/event/attachments/update.js.haml
- app/views/events/_attachments.html.haml
- config/locales/models.de.yml
- config/locales/views.de.yml
- config/routes.rb
- db/migrate/20240503120000_add_visibility_to_event_attachments.rb
- db/schema.rb
- spec/features/event/attachments_controller_spec.rb
- spec/models/event/attachment_spec.rb
- spec/regressions/events_controller_spec.rb
- spec/views/events/_attrs.html.haml_spec.rb
Refs hitobito/hitobito_sac_cas#486
> Allow choosing the visibility of event attachments

- CHANGELOG.md
- app/domain/person/filter/qualification.rb
- app/javascript/javascripts/modules/people/people_filter_qualification_validity_toggle.js.coffee
- app/models/qualification.rb
- app/views/people_filters/_qualification.html.haml
- config/brakeman.ignore
- config/locales/views.de.yml
- spec/domain/person/filter/qualification_spec.rb
- spec/features/person/people_filter_spec.rb
- spec/models/qualification_spec.rb
refs hitobito/hitobito_sac_cas#500
baut auf  #2602 auf
> Support filtering for expired_only qualifications

- app/views/events/_general_fields.html.haml
- app/views/events/_state_field.html.haml
Refs: hitobito/hitobito_sac_cas#362
> Extract events state form field to separate partial

- app/javascript/controllers/tom_select_controller.js
refs hitobito/hitobito_sac_cas#524
> Support typeahead with multiselect via tom_select stimulus controller

- app/helpers/sheet/group/nav_left.rb
- spec/helpers/sheet/group/nav_left_spec.rb
refs hitobito/hitobito_sac_cas#523
> Rewrite group nav_left sheet to work also in specs

- CHANGELOG.md
- app/decorators/group_decorator.rb
- spec/decorators/group_decorator_spec.rb
> ROLES: Sortierung der Rollentypen im Auswahlmenü hitobito/hitobito_sac_cas#552

- app/models/household.rb
- app/models/household_member.rb
- app/models/households/address.rb
- app/models/households/member_validator.rb
- app/models/households/members_validator.rb
- config/locales/models.de.yml
- spec/models/household_spec.rb
> Init household model

- app/decorators/paper_trail/version_decorator.rb
- app/models/household.rb
- app/models/households/address.rb
- app/models/households/log_entries.rb
- app/models/households/member_validator.rb
- config/locales/views.de.yml
- spec/models/household_spec.rb
fixes #2614 
dieser PR ergänzt einfach noch das Logging, basic household model wurde bereits in den master gemerged
> Implement paper trail logging for new household model

- app/indices/group_index.rb
- app/indices/person_index.rb
> The table is not inferred automatically somehow

- .github/actions/wagon-ci-setup/action.yml
- .github/workflows/wagon-tests.yml
> Reduce wagon spec runs

- CHANGELOG.md
- app/helpers/sheet/group/nav_left.rb
- app/models/group.rb
- app/models/group/nested_set.rb
- app/views/groups/_child_groups.html.haml
- spec/helpers/sheet/group/nav_left_spec.rb
- spec/models/group_spec.rb
- spec/support/group/bottom_layer.rb
- spec/support/group/static_name_groups.rb
- spec/support/locales/test.de.yml
- spec/support/locales/test.fr.yml
> Feature/2673 Sort group names locale aware

- app/views/households/_members_table_row.html.haml
- spec/features/person/household_spec.rb
- spec/views/households/edit.html.haml_spec.rb
> Fix household member links

- app/domain/feature_gate.rb
- db/migrate/20240612185517_change_event_contact_attr_mappings.rb
Fixes #2660 
Now also includes the change that structured addresses are switched on to avoid that confusion.
> Configure the new attribute in events

- app/decorators/contactable_decorator.rb
- app/domain/export/pdf/messages/letter/header.rb
- app/domain/export/tabular/groups/row.rb
- app/domain/export/tabular/people/person_row.rb
- app/domain/person/address.rb
> ADDRESSES: Bugfixes and Adaptations

- app/models/wizards/base.rb
- spec/models/wizards/base_spec.rb
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/606
> Feature/606 Make wizard step accessor public

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Simplecov was removed in 2adfcf47fe73d2825685f6239c09660f667c4a20.
> Add and enable simplecov

- app/helpers/layout_helper.rb
- app/helpers/people/membership/verify_helper.rb
- app/views/people/membership/verify/_details.html.haml
- app/views/people/membership/verify/_footer.html.haml
- app/views/people/membership/verify/_header.html.haml
- app/views/people/membership/verify/show.html.haml
- spec/helpers/layout_helper_spec.rb
- spec/regressions/people/membership/verify_controller_spec.rb
fixes hitobito/hitobito_sac_cas#673
> PEOPLE: layout membership verify page (#673)

- app/views/person/history/_roles_table.html.haml
fixes hitobito/hitobito_sac_cas#757
> Fix HTTP 500 error on membership/log (hitobito/hitobito_sac_cas#757)

- app/models/custom_content.rb
required for https://github.com/hitobito/hitobito_sac_cas/pull/765
> Make `CustomContent#replace_placeholders` public

- app/abilities/person_ability.rb
- spec/abilities/person_ability_spec.rb
Refs https://help.puzzle.ch/#ticket/zoom/8081
> Restrict access to query endpoint

- app/components/steps_component/content_component.rb
- app/views/wizards/steps/_new_user_form.html.haml
- spec/components/steps_component/content_component_spec.rb
refs hitobito/hitobito_sac_cas#794
> Also show wizard errors when using fields_for

- app/views/people/_attrs.html.haml
Refs https://github.com/hitobito/hitobito_sac_cas/pull/853
> Render data_quality extensions

- app/controllers/groups/self_inscription_controller.rb
- app/models/wizards/inscribe_in_group_wizard.rb
- app/models/wizards/steps/confirm_inscription.rb
- app/views/groups/self_inscription/new.html.haml
- app/views/groups/self_inscription/show.html.haml
- app/views/wizards/steps/_confirm_inscription.html.haml
- config/locales/views.de.yml
- config/locales/views.fr.yml
- config/locales/views.it.yml
- config/routes.rb
- spec/controllers/groups/self_inscription_controller_spec.rb
- spec/features/self_inscription_spec.rb
- spec/models/wizards/inscribe_in_group_wizard_spec.rb
> Feature/2665 Migrate Selfinscription to wizard

- app/domain/people/household_list.rb
- spec/domain/messages/letter_dispatch_spec.rb
fixes (#2212)
reviewer please do some manual testing as well.
> fix big household exports (#2212)

- app/jobs/base_job.rb
- config/initializers/delayed_job_config.rb
- spec/jobs/base_job_spec.rb
refs hitobito/hitobito_sac#803
> Increase delayed job max run time, refs #sac-803

- app/models/group.rb
- spec/fabricators/event_fabricator.rb
- spec/models/group_spec.rb
Necessary for: https://github.com/hitobito/hitobito_pbs/issues/271
> Allow adjusting nesting even when archived

- app/jobs/concerns/graceful_termination.rb
> Fix GracefulTermination docs and check_terminated implementation

- README.md
Add the [OpenSSF Best Practies Badge](https://www.bestpractices.dev/en/projects/8947) into the readme. We made it!
> Add OpenSSF Best Practies Badge

- app/domain/person/event_queries.rb
for some reason this was removed in: https://github.com/hitobito/hitobito/commit/a139c2173af6b7c9f0cca762e9ab54a63cf8d44a
> fix eager loading of events by adding back distinct on

- app/components/steps_component/content_component.rb
Refs https://github.com/hitobito/hitobito_sac_cas/pull/931
> Make `cancel_link_back_to_person` public

- app/controllers/groups/self_registration_controller.rb
- app/models/wizards/register_new_user_wizard.rb
Fixes https://github.com/hitobito/hitobito_sac_cas/issues/936
> Move self-registration jobs and mailers to wizard

- app/controllers/devise/hitobito/sessions_controller.rb
- config/initializers/doorkeeper.rb
- config/settings.yml
- doc/developer/people/authentication.md
refs hitobito/hitobito_sac_cas#1000
> Support enabling refresh tokens via settings

- app/mailers/application_mailer.rb
- app/mailers/delivery_report_mailer.rb
- app/mailers/event/participation_mailer.rb
- app/mailers/invoice_mailer.rb
- app/models/custom_content.rb
- spec/fabricators/custom_content_fabricator.rb
- spec/mailers/application_mailer_spec.rb
- spec/mailers/event/participation_mailer_spec.rb
- spec/models/custom_content_spec.rb
> mailer cleanup (hitobito#2845)

- app/abilities/person_ability.rb
- app/controllers/person/security_tools_controller.rb
- app/helpers/sheet/person.rb
- spec/abilities/person_ability_spec.rb
Fixes https://github.com/hitobito/hitobito_sac_cas/issues/990
> Add security ability

- app/components/steps_component.html.haml
- spec/components/steps_component_spec.rb
refs (hitobito/hitobito_sac_cas#1031)
See the gray overflow to the right:
> Avoid overflow in signup view (hitobito/hitobito_sac_cas#1031)

- app/models/concerns/normalized_i18n_labels.rb
- app/models/concerns/normalized_labels.rb
- spec/models/additional_email_spec.rb
- spec/models/phone_number_spec.rb
- spec/models/role_spec.rb
- spec/models/social_account_spec.rb
> Do not suggest labels from DB

- app/helpers/event_participations_helper.rb
- app/views/event/participations/_list.html.haml
> Do not render extensions in crud table

- app/abilities/json_api/event_ability.rb
- app/abilities/token_ability.rb
- app/controllers/json_api/event/kind_categories_controller.rb
- app/models/event.rb
- app/resources/event/kind_category_resource.rb
- app/resources/event_resource.rb
- config/routes.rb
- doc/developer/common/api/json_api.md
- spec/api/event_kind_categories/index_spec.rb
- spec/api/event_kind_categories/show_spec.rb
- spec/api/events/index_spec.rb
- spec/support/graphiti/schema.json
Fixes hitobito/hitobito_sac_cas#1055
> Add `Event::KindCategory` API endpoint

- app/domain/mailing_lists/bulk_mail/imap_mail_validator.rb
- config/brakeman.ignore
- spec/domain/mailing_lists/bulk_mail/imap_mail_validator_spec.rb
Good ol' "How did this ever work?!"
Refs: https://help.puzzle.ch/#ticket/zoom/8385
> Use sti_name in sql query to fix sending to mailing list from additional email

- app/domain/synchronize/mailchimp/synchronizator.rb
- spec/domain/synchronize/mailchimp/synchronizator_spec.rb
Refs: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/70990/?environment=production
https://help.puzzle.ch/#ticket/zoom/8391
> Do not include subscribers with no email for mailchimp sync

- app/jobs/export/event_participations_export_job.rb
- spec/jobs/export/event_participations_export_job_spec.rb
Used same workaround as
https://github.com/hitobito/hitobito/commit/d3cd8f7954f5ed02a8a141a54868c8e38ba77858
> Select correct created_at for participations export

- app/views/event/attachments/_attachment.html.haml
- app/views/event/attachments/create.js.haml
- app/views/event/attachments/destroy.js.haml
- app/views/event/attachments/update.js.haml
- app/views/events/_attachments.html.haml
- spec/features/event/attachments_controller_spec.rb
Specifically: https://github.com/hitobito/hitobito_sac_cas/issues/993#issuecomment-2416064547
> Change event attachments to table

- app/controllers/event/participations_controller.rb
- app/controllers/events/courses_controller.rb
- app/controllers/events_controller.rb
- app/controllers/people_controller.rb
- app/helpers/dropdown/event/participant_add.rb
- app/models/concerns/globalized.rb
- app/models/event.rb
- app/models/person.rb
Beschleunigt die lokale jubla kurs liste bei mir, obwohl ich dort auch nicht die 10sek + antwortzeiten sehe
> Fix n+1 queries in events/courses_controller

- app/controllers/event/application_market_controller.rb
- app/models/event/participatable.rb
- spec/controllers/event/application_market_controller_spec.rb
See hitobito/hitobito_jubla#135
Fixes https://help.puzzle.ch/#ticket/zoom/8444
> Repair dates in application market

- app/models/concerns/full_text_searchable.rb
- spec/models/concerns/full_text_searchable_spec.rb
fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/72998/
> Delete special characters in before executing query (#2984)

- app/domain/mail_relay/base.rb
- app/domain/mail_relay/lists.rb
- spec/domain/mail_relay/lists_spec.rb
See https://help.puzzle.ch/#ticket/zoom/8457
> First spike to handle mailing-list senders case insensitive

- .index.yml
See https://shopify.github.io/ruby-lsp/editors.html for your personal setup.
> Remove LSP indexing-config in favor of editor-settings

- .github/actions/core-ci-setup/action.yml
- .github/actions/wagon-ci-setup/action.yml
- .github/workflows/prepare.yml
- .github/workflows/release.yml
- .github/workflows/stage-settings.yml
- .github/workflows/tests.yml
- .github/workflows/update_image.yml
- .github/workflows/wagon-tests.yml
- bin/wagon
If needed, this could be 4 different PRs. I think they go well together.
> Rework workflows

- app/controllers/event/participation_lists_controller.rb
- app/controllers/events_controller.rb
- app/models/event/participation.rb
- app/views/event/participation_lists/_new.html.haml
- config/locales/views.de.yml
- spec/controllers/event/participation_lists_controller_spec.rb
resolves [hitobito_pbs#336](https://github.com/hitobito/hitobito_pbs/issues/336)
> fix: load role_type from sti_class

- app/domain/people/one_time_password.rb
- spec/domain/people/one_time_password_spec.rb
> Some OTP-Apps provide formatted TOTPs

- app/helpers/layout_helper.rb
- app/views/layouts/application.html.haml
- app/views/layouts/oauth.html.haml
refs [hitobito_sww#190](https://github.com/hitobito/hitobito_sww/issues/190)
Muss zusammen mit https://github.com/hitobito/hitobito_sww/pull/220 im sww wagon gemerged werden
> feat: allow conditional logo render (hitobito_sww#190)

- app/decorators/person_decorator.rb
refs hitobito/hitobito_sac_cas#1259
> Use url_for to return stable redirect path for picture_full_url

- app/models/invoice.rb
This resolves the deprecation warning about this as well.
> Switch to Ruby's own Enumerable#sum

- spec/controllers/person/history_controller_spec.rb
If it were, it would not fail from time to time.
> The order of things is not checked here

- app/views/person/security_tools/index.html.haml
> PEOPLE: Doppelte Texte bei Login sperren

- doc/operator/05_restore.md
- doc/operator/README.md
- lib/tasks/restore.rake
There are docs, which are better than any comment here.
The rake-task has been used for an actual restore of an event and its related data.
> Add restore-task and describe its usage

- CHANGELOG.md
- app/controllers/invoice_configs_controller.rb
- app/domain/export/pdf/invoice/articles.rb
- app/domain/invoice/batch_update.rb
- app/models/payment_reminder.rb
- app/serializers/payment_reminder_serializer.rb
- app/views/invoice_configs/_reminder_fields.html.haml
- config/locales/models.de.yml
- db/migrate/20241209093414_add_show_invoice_description_to_payment_reminder_configs.rb
- db/schema.rb
- spec/domain/export/pdf/invoice_spec.rb
- spec/domain/invoice/batch_update_spec.rb
- spec/features/event/participation_spec.rb
references hitobito/hitobito_sww#174
> Feature: hitobito_sww#174

- app/helpers/application_market_helper.rb
- app/views/event/application_market/_application.html.haml
- app/views/event/application_market/_participant.html.haml
- config/locales/views.de.yml
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/1389
> Confirm adding participant on application market

- spec/domain/table_displays/people/login_status_column_spec.rb
- spec/domain/table_displays/shared_examples.rb
- spec/spec_helper.rb
refs hitobito/hitobito_sac_cas#1508
> Add shared examples for TableDisplays, spec for LoginStatusColumn

- app/jobs/address/check_validity_job.rb
- app/jobs/address/import_job.rb
- app/jobs/person/inactivity_block_job.rb
- app/jobs/person/inactivity_block_warning_job.rb
Ich gehe davon aus, dass dies die Ursache für einige der DJ Restarts ist.
> Implement perform_internal for recurring jobs to assert that they get rescheduled

- app/domain/export/csv/generator.rb
- spec/domain/export/csv/generator_spec.rb
hitobito/hitobito_sac_cas#1535
> Make Export::Csv::Generator csv handler configurable

- app/resources/person/name_resource.rb
fixes #2848, #2875
See also #3019
> Some organizations have multiple leader-roles

- app/domain/people/cleanup_finder.rb
- app/jobs/people/cleanup_job.rb
- config/settings.yml
- spec/jobs/people/cleanup_job_spec.rb
see hitobito/hitobito#2106
see hitobito/hitobito_pbs#361
> Handle exceptions in people cleanup

- app/controllers/event/participations_controller.rb
- app/jobs/export/event_participations_export_job.rb
- spec/jobs/export/event_participations_export_job_spec.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74350
> Fix event participation export from (hitobito/hitobito_sac_cas#1512)

- app/views/contactable/_fields.html.haml
- app/views/contactable/_phone_numbers_fields.html.haml
- spec/views/contactable/_fields.html.haml_spec.rb
Extract contactable phone_numbers fields to its own partial
refs hitobito/hitobito_sac_cas#1563
> Extract contactable phone_numbers fields (sac#1563)

- app/domain/people/one_time_password.rb
Part of: https://github.com/hitobito/hitobito/pull/3014
Habs bereits auf SAC Integration deployt und dort geht es mit meiner Stichprobe wieder
> Remove secret_key_base from totp secret building process

- app/domain/person/filter/role.rb
- spec/domain/person/filter/role_spec.rb
> Exclude people from inactive role filter if role never existed 

- app/domain/synchronize/mailchimp/subscriber.rb
refs hitobito/hitobito_sac_cas#1674
> Only deal with downcased emails when syncing mailchimp

- app/decorators/paper_trail/version_decorator.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74187
> Add date as permitted class to yaml load

- app/controllers/event/tags_controller.rb
- app/controllers/person/tags_controller.rb
- spec/controllers/person/tags_controller_spec.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74294
To recreate error, try creating a tag with a space in the end
> Srtip tag names for find_or_create_by

- app/controllers/concerns/paper_trailed.rb
- app/domain/background_jobs/paper_trailed.rb
- app/models/paper_trail/version.rb
- config/initializers/delayed_job_config.rb
- db/migrate/20250224130206_add_mutation_id_to_versions.rb
- db/schema.rb
- spec/controllers/roles_controller_spec.rb
- spec/jobs/base_job_spec.rb
refs hitobito/hitobito_sac_cas#1689
> Track request or job id on papertrail versions

- app/controllers/json_api_controller.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74980
> Add error message to api for unknown attribute

- app/controllers/event/tags_controller.rb
- app/controllers/person/tags_controller.rb
- spec/controllers/person/tags_controller_spec.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75029
> Remove whitespaces around : when creating tags

- app/models/event/attachment.rb
- app/models/group.rb
- app/models/invoice_config.rb
- app/models/oauth/application.rb
- app/models/person.rb
- spec/features/person/people_controller_spec.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73115/?query=is%3Aunresolved
> Check if file is persisted when removing

- app/domain/event/filter.rb
- config/brakeman.ignore
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75046
> Use Arel.sql to prevent UnknownAttributeReference

- app/controllers/invoices/recalculate_controller.rb
- spec/controllers/invoices/recalculate_controller_spec.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74182
> Remove invoice item id from params for recalculating total

- app/helpers/people_filter_helper.rb
- spec/features/person/people_filter_spec.rb
as of rails 7.1 the previous code produced a bad parameter name
refs hitobito/hitobito_sac_cas#1700
> Fix param names by using select_tag instead of select

- doc/developer/process/workflow.md
Update the developer workflow documentation to reflect the recently agreed procedure.
> Update dev workflow documentation

- app/controllers/doorkeeper/hitobito/oidc_sessions_controller.rb
- app/models/session.rb
- config/initializers/session_store.rb
- db/migrate/20250314073222_add_person_id_to_sessions.rb
- db/schema.rb
- lib/tasks/dev.rake
- spec/jobs/sessions_cleaner_job_spec.rb
- spec/requests/oidc_logout_spec.rb
refs hitobito/hitobito_sac_cas#1738
> Clear related web session when signing out via oidc

- .pryrc
Setup papertrail metadata in rails console
> Setup papertrail metadata in rails console

- app/controllers/invoice_lists_controller.rb
- app/models/invoice_list.rb
- spec/models/invoice_list_spec.rb
behebt https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75303
> Push down recipient_ids handling to InvoiceList

- app/controllers/people_controller.rb
- app/models/person.rb
- spec/models/person_spec.rb
Eventuell auch für aktuellen Release relevant... Ist eigentlich ein Bug im Core
> Move after_save from controller to model (hitobito/hitobito_sac_cas#1678)

- app/domain/search_strategies/person_search.rb
- app/models/concerns/full_text_searchable.rb
- spec/domain/search_strategies/person_search_spec.rb
- spec/models/concerns/full_text_searchable_spec.rb
first commit fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75559
second commit fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75490
> Do not raise error when searching for invalid date

- app/domain/mailing_lists/subscribers.rb
- app/jobs/subscriptions/opt_in_cleanup_job.rb
- app/models/mailing_list.rb
- app/views/mailing_lists/_actions_show.html.haml
- app/views/person/subscriptions/index.html.haml
- spec/domain/mailing_lists/subscribers_spec.rb
- spec/helpers/mailing_lists_helper_spec.rb
- spec/models/mailing_list_spec.rb
Refs: https://help.puzzle.ch/#ticket/zoom/8980
> Revert mailing list subscriber performance improvements since certain cases do not work anymore

- app/views/people_filters/_qualification.html.haml
- config/locales/views.de.yml
I also adjusted some other weird UI behaviour I noticed regarding the date fields
> Adjust qualification ui to fit longer qualification names (hitobito/hitobito_sac_cas#1761)

- lib/tasks/restore.rake
Code used to generate the restore-scripts for event-particiaptions and invoices.
> Restore participations with script

- app/resources/person_resource.rb
- spec/api/people/index_spec.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76021
> Fix error when including layer_group in api

- app/controllers/json_api_controller.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76097
> Add error message to api for unknown filter attribute

- app/models/family_member.rb
- spec/models/family_member_spec.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76111
> Use safe_operator when destroying family_members

- app/utils/documentation_reader.rb
- doc/developer/common/api/json_api.md
- spec/domain/documentation_reader_spec.rb
> Improve json-api documentation

- CHANGELOG.md
- app/helpers/event_kinds_helper.rb
- app/helpers/standard_form_builder.rb
- app/javascript/controllers/tom_select_controller.js
- app/views/calendars/_form.html.haml
- app/views/contactable/_address_fields.html.haml
- app/views/event/kinds/_precondition_fields.html.haml
- app/views/event/participation_contact_datas/_address_fields.html.haml
- app/views/events/courses/_filter.html.haml
- app/views/events/courses/_group_filter.html.haml
- app/views/people_filters/_tag.html.haml
- app/views/people_filters/_tag_absence.html.haml
- app/views/subscriber/group/_tags.html.haml
- spec/features/stimulus/tom_select_spec.rb
- spec/helpers/standard_form_builder_spec.rb
* Changes to `TomSelectController` stimulus controller:
+ Do not limit the options by default
+ Make the options limit configurable value data tag on the select element
* Change all country_select calls to use the stimulus controller
fixes #3364
> Do not limit TomSelect options by default, make it configurable

- app/helpers/dropdown/people_login.rb
- app/javascript/javascripts/modules/tooltips.js
- app/javascript/packs/application.js
> Register tooltip on turbo render (#3043)

- app/domain/invoice/qrcode.rb
Fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76715/
> `strip` after `to_s`

- app/domain/table_displays/people/primary_group_column.rb
We still don't really know when or if this is still the case, but we can tolerate it nonetheless
Fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76687/?query=is%3Aunresolved%20is%3Aunassigned
> Primary group can be nil sometimes

- app/models/role.rb
- spec/controllers/group/log_controller_spec.rb
- spec/domain/person/add_request/approver/group_spec.rb
- spec/models/role_spec.rb
This reverts commit 98bb09886d6fe4e5a316b42fc500b7cf1dd95c43.
> Revert "bug/92-roles-updated-at (#3434)"

- config/initializers/sentry.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76684
> Ignore exceptions caused by attempted drupal exploits

- app/domain/export/tabular/people/participations_full.rb
Used in https://github.com/hitobito/hitobito_sww/pull/273
Fixes hitobito/hitobito_sww#243
> Make participations export question labels reusable (hitobito/hitobito_sww#243)

- app/controllers/events_controller.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/77225/
> Handle both arrays and hashes for the param

- app/controllers/dashboard_controller.rb
- app/views/dashboard/dashboard.html.haml
- config/routes.rb
- config/settings.yml
- db/seeds/custom_contents.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/features/dashboard_spec.rb
fixes hitobito/hitobito_insieme#150
> Add feature toggle for custom dashboard page (hitobito/hitobito_insieme#150)

- app/models/role.rb
- spec/models/role_spec.rb
Refs: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73657/?query=is%3Aunresolved%20is%3Aunassigned
> Allow normalizing labels of archived roles

- app/abilities/concerns/visible_from_above_condition.rb
- app/abilities/event/participation_ability.rb
- app/abilities/group_based_fetchables.rb
- app/abilities/person_layer_writables.rb
- app/abilities/person_readables.rb
- app/helpers/groups_helper.rb
- app/helpers/sheet/event.rb
- app/views/event/participations/_actions_show.html.haml
- spec/abilities/person_readables_spec.rb
ref hitobito/hitobito_dsj#34
There are three separate commits needed for hitobito/hitobito_dsj#34
> Adaptions for hitobito/hitobito_dsj#34

- app/domain/invoice/qrcode.rb
- spec/domain/invoice/qrcode_spec.rb
Fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/77598/
Fixes #3522
> Fix nil invoice iban case

- app/domain/export/pdf/participation/specifics.rb
- app/models/concerns/globalized.rb
- app/models/event/question.rb
- config/settings.yml
- spec/domain/export/pdf/participation/specifics_spec.rb
- spec/features/event/events_controller_spec.rb
- spec/features/event/participation_spec.rb
- spec/features/event_external_application_spec.rb
- spec/models/event/answer_spec.rb
- spec/models/event_spec.rb
Fixes #3545
After / together with this PR, merge hitobito/hitobito_sac_cas#1988 and hitobito/hitobito_sww#283
> Make alphabetic question sorting configurable
