hitobito/hitobito

- app/controllers/full_text_controller.rb
- spec/regressions/full_text_controller_spec.rb
Fixes #68 
* Added tests for actions that throw an exception
* Added preconditions to the controller methods that caused the exception
* When calling without the q param, no error will be thrown. Instead, an empty array will be returned
Note: This PR was made during [renuo open source day 2016](https://www.renuo.ch).
> Add regression test and fix 500 error

- app/controllers/group/move_controller.rb
- spec/controllers/group/move_controller_spec.rb
The current users' group is now available as a target when moving sub-subgroups
> Issue #127: Enable moving sub-subgroups up into the top group

- app/assets/javascripts/modules/person_tags.js.coffee
After turbolink navigation, event handlers are missing on the `.person-tag-add` `span`. Using delegated event handling does the trick.
> Use delegated event handling with turbolinks

- Gemfile
- Gemfile.lock
Before:
```
RAILS_HOST_NAME=example.com RAILS_ENV=production bundle exec rails c
/home/sraez/.rvm/gems/ruby-2.0.0-p643@pitc-post-innoweek/gems/pry-doc-0.8.0/lib/pry-doc.rb:33:in `<class:Pry>': undefined method `config' for Pry:Class (NoMethodError)
```
After:
```
RAILS_HOST_NAME=example.com RAILS_ENV=production bundle exec rails c
Loading production environment (Rails 4.2.7.1)
2.0.0-p643 :001 > 
```
as well as
```
RAILS_ENV=development bundle exec rails c
require rails:   0.470000   0.120000   0.590000 (  0.580558)
require gems:   2.530000   0.260000   2.790000 (  2.818350)
Loading development environment (Rails 4.2.7.1)
```
> Fix broken rails console in production environment

- spec/models/duration_spec.rb
- spec/models/event_spec.rb
- spec/models/qualification_spec.rb
Because the timezone of the app is set to 'Berne' and the CI server is in a UTC timezone. Use Time.zone.today instead Date.today.
See [this](https://travis-ci.org/hitobito/hitobito/jobs/212571141) failed build.
> Fix failing tests between 0:00 and 1:00 UTC

- .travis.yml
- app/decorators/contactable_decorator.rb
- spec/decorators/contactable_decorator_spec.rb
enable direct call from phone numbers
hyperlink "tel:012345678" is added to every phone number when displaying a person
this is especially helpfull on mobile devices. 
see also iPhoneURLScheme from apple
https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html
> Display tel: Link with phone numbers

- AUTHORS
- CHANGELOG.md
- app/controllers/person/history_controller.rb
- app/decorators/group_decorator.rb
- app/views/person/history/index.html.haml
- spec/controllers/person/history_controller_spec.rb
- spec/regressions/person/history_controller_spec.rb
- Person history now displays the roles with layers in the group colmmn. This allows to identify to which parent group a group belongs.
- Person history now orders the roles by group with layers instead of only the group name.
> Improved Person history

- app/assets/stylesheets/hitobito/_form.scss
- app/views/people/_actions_show.html.haml
Ich will klarer machen, dass die Delete Action etwas aussergewöhnliches ist. Deshalb die zusätzliche Bootstrap Klasse. Ich musste dann noch das CSS anpassen, damit auch die korrekte Farbe Icons verwendet wird.
> Add btn danger class to delete person button and adjust it to use white icons

- app/assets/javascripts/modules/ajax_upload.js.coffee
- app/controllers/event/attachments_controller.rb
fixes #305 
Es scheint so zu sein, dass das Formular bei der zweiten Datei zwar abschickbar, aber ohne Datei ist. Daher wird es normal abgeschickt, was dann Rails dazu bringt, zurecht die fehlende Datei zu bemängeln. 
Ein Form-Reset nach dem Submit säubert das Formular und verhindert damit anscheinend diesen Fehler.
Interessanterweise kann man nach dem Submit das Formular nicht weiter verwenden, sondern muss es neu via jQuery suchen.
Ich hätte gerne ein zweites Paar Augen auf dem Code, da ich unsicher bin, ob meine Theorie auch stimmt.
> Fix erroneous upload error

- .travis.yml
A test fails on Travis CI with this error
```
Mysql2::Error: Out of sort memory, consider increasing server sort buffer size
```
Therefore I am considering.
> Increase the MySQL sort_buffer_size on TravisCI

- app/views/roles/update.js.haml
Wie nachfolgend illustriert werden nach dem Inline-Update einer Rolle die Rollen aller Gruppen einer Person angezeigt:
Die Gruppe wird beim rendern berücksichtigt
> Consider group when updating role inline

- .travis.yml
- README.md
- spec/domain/person/filter/role_spec.rb
For some security-updates, we need to drop some older Ruby-Versions. Those are EOL'd by upstream ruby anyway.
> Drop older Ruby-Versions

- app/views/events/_list.html.haml
the `if` should only be uses on the scope filter, the yearly pagination should always be there.
> fixes #516

- app/models/qualification_kind.rb
- config/locales/models.de.yml
- spec/models/qualification_kind_spec.rb
Validation on validity required validity to be bigger than zero. Probably because 0 Year validitity does not seem to make sense, but it actually exists see #458 
Probably this was done this way, because nil.to_i returns 0, so you have to explicitely check for nil.
> Allows validity of 0 year for qualification kind, fixes #458

- app/controllers/crud_controller.rb
Fixes #414
Since most DB-Errors are either setup-issues or race-conditions, I
silence them here. The setup-issues will be visible on other places and
also be logged for debugging. The race-conditions are nothing the App
can sensibly handle everytime.
So I just return "false" indicating the failed save and let the user
handle the situation according to the displayed data.
> Do not disrupt the user-workflow

- app/controllers/people_controller.rb
- app/decorators/paper_trail/version_decorator.rb
- app/domain/person/household.rb
- config/locales/views.de.yml
- spec/domain/person/household_spec.rb
fixes #617 
fixes https://github.com/hitobito/hitobito_cevi/issues/36
- does no longer create empty entries if person is in no household
- does no longer show "household updated" if there was no adress change
- creates log entries for all housemates when someone was removed
- corrects papertrail entries, that showed user instead of the actually changed item.
- now shows who made the change in the papertrail log
> fixes various issues in household log

- app/assets/stylesheets/hitobito/_form.scss
- app/helpers/standard_form_builder.rb
- spec/helpers/standard_form_builder_spec.rb
As of right now, required fields are indicated with an asterisk _after_ the input-field. This is quiet unconventional and users might oversee it easily.
Move the asterisk in front of the input-field, next to the label. Instead of hardcoding it into the label, a "required"-class is added to the control-group. The label is then extended via css.
Credits to @rapkosi
> Feature: Display required fields with an asterisk

- app/helpers/roles_helper.rb
Fix a typo to enable the automatic selection of the default role of a group when assigning a new role to a user.
> fix the default role when assigning a new group

- app/views/layouts/application.html.haml
This PR allows the links in the footer to be set per locale, while preserving the current behavior for unset locales.
settings.yml (before)
```yml
links:
"Informationen und Hilfe": https://www.scout.ch/de/...
"Aide et assistance": https://www.scout.ch/fr/...?set_language=fr
"Aiuto e assistenza": https://www.scout.ch/it/...?set_language=it
```
settings.yml (after)
```yml
links:
de:
"Informationen und Hilfe": https://www.scout.ch/de/...
fr:
"Aide et assistance": https://www.scout.ch/fr/...?set_language=fr
it:
"Aiuto e assistenza": https://www.scout.ch/it/...?set_language=it
```
> Allow I18n aware footer links

- config/environments/development.rb
For production and almost anywhere else, it might make sense to tag each
request so that they can be grouped. For development, where I manually
analyse one manual request at a time, I prefer to have less noise.
Also, the log now reads better on a small terminal-window.
Since I might overlook something important here, I put this in a pull-request
with the humble request for comments.
> Do not assume multiple parallel requests in development

- app/domain/export/pdf/labels.rb
- spec/domain/export/pdf/labels_spec.rb
Label export showed company names even if address was not marked as a company. This is annoying because users often think, they have to fill the `company_name` with the company they currently work. 
If filled like that:
**Idea:** A further improvement could be, to only display the `company_name` field, if `company` is marked.
**Before:**
**Now:**
> Fix label-export: Render only company's company_name

- Gemfile
- Gemfile.lock
I am wondering if anything stands against using better_errors. Personally, I can see no downside, since I very much enjoy the increased visibility into the state in case of an error.
> Add better_errors to improve debugging/development experience

- app/controllers/tag_lists_controller.rb
- app/domain/tag/list.rb
- app/helpers/tag_lists_helper.rb
- app/models/tag.rb
- app/views/tag_lists/_deletable.html.haml
- app/views/tag_lists/_new.html.haml
- spec/controllers/tag_lists_controller_spec.rb
- spec/domain/tag/list_spec.rb
Refs #342
Reverts 2ee8ad3cddfbebbb461571e9af2ffb996313a855 because the business logic was wrong and it broke bulk tag deletion.
Also adds tests for the modals so that doesn't happen again
> Fix bulk tag delete modal and add tests

- app/domain/synchronize/mailchimp/synchronizator.rb
The Mailchimp API is [paginated](https://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/#pagination). By default, it returns only the first 10 entries and there's no way to disable pagination altogether.
Previous versions of the Mailchimp integration didn't take this into account, causing the synchronization to fail deleting members on mailchimp, as only the first 10 members from mailchimp were compared to the hitobito members of a mailing list.
This PR is a «quick fix» that raises the pagination count (entries per page) to one million entries, which should suffice for most use cases, but the export will still fail if a mailing list exceeds this number. If this is not good / sustainable enough, I can reach out to our client in an effort to secure …
> Mailchimp export: Fix difference calculation to avoid persistence of deleted members

- app/decorators/group_decorator.rb
- spec/decorators/group_decorator_spec.rb
Similar to `ApplicationDecorator#used?`, this is a convenience method that can be used on single attributes:
```ruby
entry.used_attributes(:name).each do |_|
end
entry.used?(:name) do
end
group.modifiable_attributes(:name).each do |_|
end
group.modifiable?(:name) do
end
```
This is motivated by a work in progress solving #585
> Implement convenience method `GroupDecorator#modifiable?`

- config/environments/development.rb
better_errors only engages in requests from whitelisted IPs. By default only localhost is whitelisted. However, in dockerized setups, the requests come from a different host. This change enables docker setups to set an environment variable to specify the IP of the docker host.
> Make it possible to use better_errors in dockerized setups

- app/views/people/_add_requests.html.haml
Change the icon for accepting an request because the current icon does not exist. Makes the function working again.
Current state:
After PR:
> Change icon for accepting request

- app/controllers/roles_controller.rb
- app/helpers/form_helper.rb
- app/views/devise/registrations/edit.html.haml
- app/views/event/application_market/_popover_waiting_list.html.haml
- app/views/group/merge/select.html.haml
- app/views/group/move/select.html.haml
- app/views/invoice_configs/_form.html.haml
- app/views/invoices/_payment_form.html.haml
- app/views/invoices/_payment_reminder_form.html.haml
- app/views/notes/_section.html.haml
- app/views/payment_processes/new.html.haml
- app/views/people/_form.html.haml
- app/views/person/csv_imports/define_mapping.html.haml
- app/views/person/csv_imports/new.html.haml
- app/views/roles/_form.html.haml
- app/views/roles/_popover.html.haml
- config/locales/views.de.yml
- config/locales/views.en.yml
- spec/controllers/roles_controller_spec.rb
Die Änderungen in diesem PR hatten zum Ziel, das Verhalten beim erstellen von neuen Rollen zu verbessern:
- Wird der Knopf "Speichern und weitere erfassen" gedrückt, kommt man automatisch wieder auf die erfassen Maske
- Wird eine völlig neue Person erfasst und normal gespeichert, soll man im :edit der Person landen, um weitere Felder erfassen zu können
Achtung:
Ich dabei den form_helper angepasst und die Methoden (aus meiner Sicht klarer gemacht). Konkret: save_form_buttons => form_buttons (mit keyword Argumenten). Im Core habe ich alle Aufrufe angepasst, aber es könnte in den Wagons noch weitere aufrufe haben.
Im Zusammenhang mit diesem PR ist mir auch der Bug der in PR hitobito/hitobito_pbs#123 aufgefallen
> "Add Another" Button

- README.md
This fixes to link to 04_wagons.md in README.md.
> fix link to 04_wagons.md in README.md

- app/domain/export/ics/events.rb
- spec/domain/export/ics/events_spec.rb
This forces Google Calendar to interpret the times correctly.
> Use UTC format in iCalendar export

- config/initializers/doorkeeper_openid_connect.rb
Wir brauchen noch mindestens den Email-Claim, damit wir das als Login verwenden können. Vor- und Nachname machen IMHO im name scope Sinn. Siehe https://github.com/doorkeeper-gem/doorkeeper-openid_connect#claims
> Add Email Claim

- app/assets/stylesheets/hitobito/_layout.scss
- app/assets/stylesheets/hitobito/_navigation.scss
- app/assets/stylesheets/hitobito/_typography.scss
<table><tr><td>Before<br><img width="300" alt="before" src="https://user-images.githubusercontent.com/3001985/64474076-75d55100-d16f-11e9-932b-ca21dadbb272.png"></td><td>After<br><img width="300" alt="after" src="https://user-images.githubusercontent.com/3001985/64474075-75d55100-d16f-11e9-8f7a-e5ec4691f2e4.png"></tr></table>
It only changes the mobile styles
> Efficient screenspace-use on mobile

- app/views/people/_attrs.html.haml
Unfortunately Safari rendering engine rounds differently than others, so the second column of the people view always got wrapped on to a new line. By making the first on grow to use available space, the problem won't occur anymore.
Tested in current versions of Safari, Firefox, Chrome, Opera, IE 11 on macOS, Windows and Linux.
> Make first column of people view have flexible with.

- app/assets/stylesheets/hitobito/_layout.scss
By default, iOS Safari renders `<input type="search">` specially (with big rounded corners). This breaks the design:
This sets the default appearance to none:
> Fix quicksearch field appearance on iOS Safari.

- app/serializers/event_participation_serializer.rb
- doc/development/05_rest_api.md
- spec/serializers/event_participation_serializer_spec.rb
Wie kurz mit @carlobeltrame besprochen benötigen wir zusätzliche Attribute zu den Teilnehmenden. Im Moment werde nur Vor- und Nachname sowie Email-Adresse mitgegeben. Mit diesem PR werden alle PUBLIC_ATTRS auf Person inkludiert. Konkret sollte das auch Erweiterungen aus den wagons zulassen.
> Enrich participation serializer

- app/serializers/person_serializer.rb
- spec/serializers/person_serializer_spec.rb
Die Änderung sendet nun den household_key in der API response, wenn eine Person abgefragt wird (Jedoch nur beim "/groups/:group_id/people/:id" endpoint).
Gibt es sonstige Anpassungen die gemacht werden müssten? Ich habe die rspecs kurz gecheckt, aber dort nichts gesehen, was ich ergänzen müsste.
> Return the household key to the api response

- app/controllers/oauth/profiles_controller.rb
- app/domain/person/subscriptions.rb
- spec/domain/person/subscriptions_spec.rb
Damit externe Applikationen zusätzlich zur OAuth-Authentifizierung auch die bestehenden Hitobito-Strukturen zur Authorisierung nutzen können, sollen beim Login die Berechtigungen pro Rolle der Person mitserialisiert werden.
Dieser PR ergänzt die Rollen-Serialisierung im `Oauth::ProfilesController` mit den Permissions der Rolle. In meinem – zugegebenermassen limitierten – Verständnis der OAuth-Prozesse sollte das den Applikationen, die Hitobito per OAuth anbinden, Zugriff auf diese Information geben.
* [Issue im Trello «MiData Development»](https://trello.com/c/zDbvbGec/22-midata-z-25-anbindung-pbs-portal-in-der-midata-sauber-aufgleisen)
> Berechtigungen im OAuth «Profil» mitserialisieren (Z-25)

- app/assets/javascripts/modules/remote_typeahead.js.coffee
- app/controllers/full_text_controller.rb
- app/decorators/event_decorator.rb
- app/decorators/group_decorator.rb
- app/decorators/person_decorator.rb
- app/views/full_text/_events.html.haml
Die verschiedenen Typen von Suchresultaten, speziell die verschiedenen Anlasstypen im Youth-Wagon, sollen einfacher unterscheidbar sein.  
Dieser PR serialisiert mit den Suchresultaten eine Icon-Klasse mit, die in der Schnellsuche und der Resultatseite im Tab Anlass angezeigt wird:
Die Änderungen hier sind im Kontext einer [dazugehörigen Anpassung im Youth-Wagon](https://github.com/hitobito/hitobito_youth/pull/9) zu verstehen, welche individuelle Icons für die verschiedenen Anlasstypen definiert.
* [Issue im Trello «MiData Development»](https://trello.com/c/nPOn6Kmv/33-midata-z-33-suchresultate-typ-der-resultate)
* [Diskussion im Trello «Team MiData Features»](https://trello.com/c/uawnFN18/240-priorisierung-suchresultate)
> Icons in den Suchresultaten (Z-33)

- app/assets/stylesheets/hitobito/_main.scss
Ich bin einer Anfrage nachgegangen, die Notizen-Ansicht zu «reparieren». Die Personen-Bilder und -Icons werden auf der PBS-Testinstanz und bei mir lokal in voller Breite angezeigt:
Dieser PR importiert das existierende `_note.scss`-Stylesheet in `_main.scss`, was bei mir das «Problem» löst und die Ansicht folgendermassen ändert:
Ich habe nicht herausgefunden, ob das aus Versehen oder absichtlich nicht importiert wurde 🤷 Auf jeden Fall scheint diese einfache Anpassung die Ansicht wiederherzustellen.
* [Issue im Trello «MiData Development»](https://trello.com/c/wzB3lXMx/36-midata-z-37-ansicht-notizen-reparieren)
> Import existing note stylesheet (Z-37)

- app/controllers/mailing_lists_controller.rb
- app/domain/synchronize/mailchimp/subscriber.rb
- app/domain/synchronize/mailchimp/synchronizator.rb
- app/models/mailing_list.rb
- app/views/mailing_lists/_attrs.html.haml
- app/views/mailing_lists/_form.html.haml
- config/locales/models.de.yml
- db/migrate/20200625114634_add_mailchimp_include_additional_emails_to_mailing_list.rb
- db/schema.rb
- spec/domain/synchronize/mailchimp/subscriber_spec.rb
- spec/domain/synchronize/mailchimp/synchronizator_spec.rb
Bei der PBS gibt es den Bedarf, dass gewisse Abo-Versände nicht nur an die Haupt-Email der Abonnent*innen, sondern auch an alle «weiteren Emails» mit der Option «Versand» geschickt werden. Das soll möglich, aber optional sein: Das Standardverhalten mit den Haupt-Emails soll nicht geändert werden.
Dieser PR verändert die Mailchimp-Synchronisierung so, dass sie nicht mehr jeweils eine Person und deren Haupt-Email direkt synchronisiert, sondern ein neues Daten-Paar (Person, Email). In einem zweiten Schritt wird dann über ein neues Flag `mailchimp_include_additional_emails` möglich, das Synchronisierungsverhalten vom bisherigen Standard (nur Haupt-Email) auf das neue Verhalten (Haupt-Email plus alle Versand-Emails) zu ändern. Die commit history sollte dies wiederspiegeln.
1. Ist die …
> Mailchimp-Synchronisierung: Option zum Einschliessen von Versandadressen (Z-38)

- app/models/event.rb
- spec/models/event_spec.rb
Say we have a group G, its sibling group S and a person P with a role on S but no role on G.
A is allowed to create a shared event that includes both G and S. However, with `autosave: nil` (as it was so far) or `autosave: true`, Rails automatically saves both G and S during the creation of the event. This in turn changes the `updated_at` timestamp and sets `updater` on both groups to P. This can be confusing because now, on G it says that P has last updated G, even though he shouldn't really be allowed to do so. For this reason, we deactivate autosaving groups via the events_groups association.
Based on a real-world [report](https://help.puzzle.ch/#ticket/zoom/1505) with PBS, where a user from one Kantonalverband was listed as `updater` of another Kantonalverband on which he had no …
> Disable autosaving of an event's associated groups

- config/application.rb
- config/environments/production.rb
Essentially: move it away from development, because there is it not as
helpful. Also, it generates a lot of noise in the test-log that no-one
ever will look at.
Am I missing something here?
> Move Log-Tagging to production only

- app/abilities/token_ability.rb
- app/controllers/mailing_lists_controller.rb
- app/controllers/service_tokens_controller.rb
- app/decorators/service_token_decorator.rb
- app/serializers/mailing_list_serializer.rb
- app/serializers/mailing_list_subscriber_serializer.rb
- app/views/service_tokens/_form.html.haml
- config/locales/models.de.yml
- db/migrate/20200602143959_add_mailing_lists_to_service_tokens.rb
- db/schema.rb
- spec/abilities/token_ability_spec.rb
- spec/controllers/service_tokens_controller_spec.rb
- spec/fixtures/service_tokens.yml
- spec/regressions/mailing_lists_controller_spec.rb
Auf Abos und Abonnent*innen soll per API zugegriffen werden können. Dies soll unter anderem ermöglichen, dass weitere Versandmöglichkeiten / externe Mailanbieter integriert werden können.
👉 @diegosteiner 
Dieser PR öffnet `/groups/:group_id/mailing_lists/:mailing_list_id` für den Zugriff mit einem ServiceAccount und per JSON. Zusätzlich erweitert sie die API-Keys / service token um eine neue Berechtigung `mailing_lists` («Abonnent/innen von Mailinglisten dieser Ebene»), welche genau diesen Zugriff erlaubt.
* [PR #163 im PBS-Wagon auf Basis dieses PRs](https://github.com/hitobito/hitobito_pbs/pull/163), welcher zusätzliche PBS-spezifische Felder serialisiert
* [Issue im Trello «MiData Development»](https://trello.com/c/6EosZKkI/28-midata-z-30-schnittstellen-erweitern-api-f%C3%BCr-abos-und-a …
> API-Zugriff auf Abos und Abonnent*innen (Z-30)

- app/abilities/mailing_list_ability.rb
- app/controllers/mailing_lists_controller.rb
- spec/abilities/mailing_list_ability_spec.rb
- spec/controllers/mailing_lists_controller_spec.rb
Abos sollen neu nur noch für Personen angezeigt werden, welche Schreibrecht auf das Abo haben. Abos mit der Option «Abonnenten dürfen sich selbst an-/abmelden» werden allen Personen angezeigt.
Der PR ändert die Permissions in `MailingListAbility` und fügt zusätzliche Logik im `MailingListController` hinzu, um in der Übersichtsliste nur die sichtbaren Abos anzuzeigen.
1. Wir gehen davon aus, dass diese Anpassung von generellem Interesse ist – Abos anzuzeigen, mit denen man nicht interagieren kann, scheint uns nicht sinnvoll. Stimmt das so oder soll das Feature in einen Wagon gezügelt werden?
1. In der aktuellen Lösung verdoppelt die Logik im Controller die Angaben der `MailingListAbility`. Ich habe versucht, letztere direkt zu verwenden mit etwas wie `MailingList.accessible_by`, aber war …
> Sichtbarkeit von Abos (Z-35)

- app/domain/event/participant_assigner.rb
- spec/domain/event/participant_assigner_spec.rb
Beim Zusammenlegen von zwei Kursen wurden zwei Bugs bemerkt, die hier gefixt werden sollen.
Die TN wurden im abgesagten Kurs in die Warteliste verschoben, dann im zusammengelegten Kurs aus der Warteliste hinzugefügt. Der abgesagte Kurs wurde dann gelöscht. Die verschobenen TN hatten dann aber immer noch die id des gelöschten Events in ihrer application.priority_1_id. Versucht man dann einen solchen TN von "zugeteilte Teilnehmende" zurück auf "Anmeldungen" zu verschieben, wird versucht den TN in den priority_1 Kurs zu verschieben, was fehlschlägt. Die Lösung ist, den TN in einem solchen Fall im Kurs zu belassen (in der Spalte "angemeldet", nicht "zugeteilt").
Ein zweiter, Bug sind fehlende Answers (Anmelde- und Administrationsangaben) nach dem Verschieben via Warteliste und Löschen des …
> Fix two course merging bugs

- db/seeds/development/root.rb
Replaces #993 
Better to only do this in the development seeds. Thanks @kronn 
The other fields (firstname, lastname, birth date) are necessary to set because they are required in some wagons.
See hitobito/development#3
> Set root password in development

- config/environments/development.rb
In https://github.com/hitobito/hitobito/commit/3c63e9062e13693d294bcbc410a8f0daee35ed23#diff-a2f09e1db7a47eb67c5849478a97f3d7 support for configuring mail via environment variables was removed during the Rails 6 upgrade. This PR reinstates this possibility, since it is needed for both the [old](https://github.com/nxt-engineering/hitobito-docker/commit/b399f2bb800954385d0f29827dfaaf3f1583a562) and [new](https://github.com/hitobito/development/issues/5) Docker setups.
This re-introduces the need for an environment variable `RAILS_HOST_NAME` - is there a better way of doing this? Would a default of `localhost:3000` be sufficient for general non-Docker-based setups?
> Re-enable configuring dev mail setting via env variables

- config/environments/development.rb
`RAILS_HOST_NAME` is not required anymore if you are not using the Docker setup
> Simplify dev mail config

- CHANGELOG.md
- config/locales/views.de.yml
The correct German spelling for authorizations is 'Autorisierungen' (without the 'h', I'm also confused by this). These are the only two places where I found it misspelt. Compare https://www.duden.de/rechtschreibung/Autorisierung.
> OAuth authorizations German spelling

- CHANGELOG.md
- app/models/event.rb
- app/models/event/participation.rb
- app/models/mail_log.rb
- app/models/person.rb
- config/database.yml
- config/locales/models.de.yml
- config/locales/models.en.yml
- config/locales/models.fr.yml
- config/locales/models.it.yml
- db/migrate/20201012121723_convert_database_to_utf8mb4.rb
- db/schema.rb
- spec/controllers/event/participations_controller_spec.rb
- spec/domain/mail_relay/base_spec.rb
- spec/models/person_spec.rb
Fixes #98, #864, #398 
Bei einer verhältinismäßig großen DB gab es keine deutlich sichtbare Vergrößerung des Speicherplatzbedarfs, die Migration lief (lokal) in unter einer Minute fehlerfrei durch. Da utf8mb4 ein klares superset von utf8 und damit auch von latin1 ist, gibt es keine Konvertierungsprobleme. Es kann einfach mehr gespeichert werden.
> Convert to utf8mb4

- config/settings.yml
Gemäss RFC 8414 (https://tools.ietf.org/html/rfc8414)  und doorkeeper-gem (https://github.com/doorkeeper-gem/doorkeeper-openid_connect) muss `issuer` eine URL (eigentlich fix mit `https://`) sein.
Bisher wurde entweder `http://localhost:3000` oder `ENV['RAILS_HOST_NAME']` verwendet, was in beiden Fällen streng genommen falsch ist: die erste Variante ist ungültig wegen `http` statt `https`; die zweite ist ungültig, weil `https` fehlt.
Dieser Fix berücksichtigt allerdings `ENV['RAILS_HOST_SSL']` und erlaubt somit für Testing-Zwecke auch Issuers mit `http`-Protokoll.
> Doorkeeper issuer must be URL

- app/controllers/custom_contents_controller.rb
- app/decorators/custom_content_decorator.rb
- app/views/custom_contents/_form.html.haml
There exists a bug when custom contents are not existing in all available languages. A new translation is created when translated text should be stored. This however fails because the label is not transferred with the form. Therefore it was also never permitted to send it.
This PR fixes this.
> Allow custom content creation in new language

- config/environments/development.rb
- config/environments/test.rb
Als Diskussionsgrundlage rege ich hier mal an, dass wir bei fehlenden Übersetzungen direkt eine Exception werfen anstatt nur einen Tooltip zu rendern. Ich habe dafür die entsprechenden Settings in Rails aktiviert. Wenn ein `I18n.t`-call ein default definiert, greift das aber nicht mehr.
Was meint ihr zu dem Thema allgemein und auch im konkreten zu den Einschränkungen?
> Exception bei fehlenden Übersetzungen

- config/application.rb
- config/initializers/sentry.rb
While the OPENSHIFT_BUILD_COMMIT is technically correct and unique, it is far from human-parseable. Since we now update the VERSION with every release, we can use that as release-information.
> Human-readable VERSION for Sentry

- app/serializers/group_list_serializer.rb
- spec/serializers/group_list_serializer_spec.rb
Add the group type to the groups list. 
There might be reasons for this not to be desirable, so it needs to be discussed and thought through.
> Add specs for group_list_serializer

- app/assets/stylesheets/hitobito/_navigation.scss
Ein kleines Detail, das ich beim Styling für SJAS festgestellt habe. Für das Breadcrumb (im Screenshot oben rechts) wird die Heading Font verwendet – im Beispiel von SJAS wäre das eine Serifenschriftart (siehe «GR» oder «Anlass 352):
Da dies aber keine Überschrift ist und auch nicht Überschriftencharakter hat, schlage ich vor für das Breadcrumb die normale Content Font zu verwenden – im Beispiel von SJAS wäre das eine serifenlose Schriftart:
> Don't use heading font for breadcrumb

- app/domain/synchronize/mailchimp/synchronizator.rb
- app/jobs/mailchimp_destruction_job.rb
- app/jobs/mailchimp_synchronization_job.rb
- config/settings.yml
- config/settings/development.yml
Wenn man lokal zu debugging-Zwecken eine produktions-Datenbank hat, können dort auch Mailchimp-Credentials hinterlegt sein. Da man für einige Export die Background-Worker braucht, werde alle Jobs ausgeführt. Dazu gehört auch der Mailchimp-Sync. Da man in development aber nicht mit dem produktiven Mailchimp-Account reden möchte, ist hier ein Feature-Toggle angebracht.
Dieser PR fügt genau das hinzu.
Standardmässig wird nun im Development kein Sync mehr gemacht, man kann dies aber wie üblich lokal überschreiben, wenn man an diesem Feature arbeitet und entsprechende Daten hat. Für test habe ich keine besondere Config gemacht, da hier eh immer generierte Daten in der DB sind.
> feature-toggle für MailchimpSync

- app/controllers/subscriber/base_controller.rb
- app/controllers/subscriber/group_controller.rb
- app/views/subscriber/group/_roles.html.haml
- app/views/subscriber/group/edit.html.haml
- app/views/subscriptions/_list.html.haml
- app/views/subscriptions/_subs_table.html.haml
- config/locales/views.de.yml
- config/routes.rb
So far, subscriptions in mailing lists can only be created and deleted. In the case of group subscriptions, entering the data is tedious, and also prone to errors and change over time, when new groups are founded, roles are newly used in a group, or new roles are even added to hitobito. This PR adds the capability to edit group subscriptions.
Thanks to @tobifra for the suggestion :)
> Allow editing group / role subscriptions in mailing lists

- app/domain/invoice/payment_processor.rb
- app/domain/invoice/qrcode.rb
- app/domain/invoice/reference.rb
- app/domain/invoice/scor_reference.rb
- app/models/invoice.rb
- db/migrate/20201214202413_add_reference_to_invoices.rb
- db/schema.rb
- spec/controllers/payment_processes_controller_spec.rb
- spec/domain/export/pdf/invoice_spec.rb
- spec/domain/invoice/payment_processor_spec.rb
- spec/domain/invoice/qrcode_spec.rb
- spec/domain/invoice/scor_reference_spec.rb
- spec/fixtures/invoices.yml
- spec/models/invoice_spec.rb
Fügt dem QR Code eine Referenz hinzu. Vereinfacht das Einlesen von Rechnnungen
closes #1109
> Zahlungsreferenzen für QR Rechnungen

- spec/controllers/invoice_lists_controller_spec.rb
- spec/controllers/invoices_controller_spec.rb
- spec/controllers/oauth/active_authorizations_controller_spec.rb
- spec/domain/event/api_filter_spec.rb
- spec/domain/invoice/batch_update_spec.rb
- spec/domain/invoice/filter_spec.rb
- spec/domain/person/filter/role_spec.rb
- spec/models/invoice_spec.rb
- spec/spec_helper.rb
- spec/utils/cookie_spec.rb
- spec/utils/cookies/async_download_spec.rb
- spec/utils/cookies/async_synchronization_spec.rb
`api_filter_spec` schlagen rund ums Jahresende fehl, z.B. weil ein Event mit Startdatum in 5 Tagen erstellt und mit Defaultfilter gesucht wird. Wenn in 5 Tagen das neue Jahr schon begonnen hat, wird dieses Event aber mit dem Defaultfilter nicht mehr gefunden (Defaultfilter sucht vom 1. Januar bis 31. Dezember).
Dieser Fix setzt das für die Specs verwendete `Date.today` auf 1. Juni 2020, so dass keine derartigen Effekte auftreten.
> Time travel to middle of the year before testing

- app/controllers/events_controller.rb
- app/controllers/full_text_controller.rb
- app/controllers/subscriber/event_controller.rb
- app/controllers/subscriptions_controller.rb
- app/domain/event/filter.rb
- app/domain/search_strategies/sql.rb
- app/helpers/standard_form_builder.rb
- app/indices/event_index.rb
- app/models/event.rb
- app/models/mailing_list.rb
- bin/wagon
- db/migrate/20141218140203_modify_event_counts.rb
- db/migrate/20210107151626_translate_event_questions.rb
- db/migrate/20210118151446_translate_events.rb
- db/schema.rb
- db/seeds/support/event_seeder.rb
- db/seeds/support/person_seeder.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/subscriber/event_controller_spec.rb
- spec/controllers/subscriber/group_controller_spec.rb
- spec/domain/event/filter_spec.rb
- spec/fixtures/event_translations.yml
- spec/fixtures/events.yml
Die SJAS bieten Ferienlager für Auslandschweizer an. Da hier die viele verschiedene Kulturen und Sprachen vorkommen, sollen Anlässe (also auch Ferienlager) übersetzbar sein. 
Dieser PR ermöglicht die Übersetzung von 
- Name
- Beschreibung (genannt Alterskategorie bei der SJAS)
- Anmeldebedingungen
- Zweitunterschrift von
Der Ablauf ist ähnlich den `CustomContent`-Übersetzungen. Man bearbeitet ein Event immer nur in einer Sprache, kann diese aber über den Webseitensprachwähler ("Sprachlink") wechseln.
Die notwendigen Anpassungen in der Wagon (fixtures, seeds, ggf. specs) verlinke ich noch.
See hitobito/hitobito_sjas#35
> Mehrsprachigkeit von Events

- app/helpers/sheet/mailing_list.rb
- app/views/mailing_lists/_list.html.haml
When coming from the "my subscriptions" page, we still link to the info / settings page, because that's where the subscribe / unsubscribe button is located.
> Show messages tab on mailing lists by default

- app/controllers/messages_controller.rb
- app/models/message.rb
- app/models/message/letter.rb
- app/views/messages/_actions_show.html.haml
- config/locales/views.de.yml
Fixes https://github.com/hitobito/hitobito_cvp/issues/99
This allows to use an existing letter as a template for a new one, even after the existing one has been dispatched and is read-only.
> Enable duplicating existing letters

- app/javascript/stylesheets/hitobito/_form.scss
> Fix: Remove horizontal scrollbar on tabbed forms

- doc/architecture/README.md
Summary:
* Link to the official arc42 documentation was outdated.
Fix the URL so the link works again.
> Fix arc42 link

- spec/controllers/assignments_controller_spec.rb
Fixes #1204, hopefully
I'll re-run the Travis build a few times to see whether this is working as expected. It's hard to say whether this was the only cause, but it's one possible cause (the `Settings` stick around after the test, and the mock doesn't like being used in multiple tests). All other uses of `Settings` in the core specs are either read-only or use mocking correctly.
> Fix flaky test due to wrong use of mock

- app/domain/export/pdf/messages/letter/content.rb
- spec/domain/export/pdf/messages/letter/content_spec.rb
Ersetzt einen `nil` value durch einen Leerstring, bevor dieser ins PDF eingefügt wird. Andernfalls kommt es zu einem Fehler
> Handle nil values when replacing letter placeholders

- app/controllers/addresses_controller.rb
- app/controllers/concerns/full_text_search_strategy.rb
- app/controllers/full_text_controller.rb
- app/domain/address/full_text_search.rb
- app/domain/address/importer.rb
- app/domain/search_strategies/base.rb
- app/domain/search_strategies/sphinx.rb
- app/models/address.rb
- config/locales/models.de.yml
- config/locales/views.de.yml
- doc/README.md
- doc/features/README.md
- doc/features/address-completion.md
- lib/tasks/address.rake
- spec/config/locales_spec.rb
- spec/domain/address/full_text_search_spec.rb
- spec/features/messages_spec.rb
- spec/fixtures/addresses.yml
- spec/models/address_spec.rb
- spec/models/invoice_spec.rb
While debugging the address completion, I refactored the codebase a little. Therefore, you are now looking at an extraction, some spelling changes, several linter-changes and some new methods. Alongside these cosmetic changes, I added
- support for house numbers as they are imported right now
- some documentation on this optional feature
- a spec that ensures consistent spellings in the German locale
Fixes #1213
> Repair address completion

- app/domain/address/full_text_search.rb
- app/domain/search_strategies/base.rb
- app/domain/search_strategies/sphinx.rb
- app/indices/address_index.rb
Und also begab es sich, dass ein Kunde ausging vom Kaiser Sphinxistus, dass die Hausnummern sich zu zählen habe... Stellt sich jedoch heraus, dass Sphinx relativ schlecht darin war, einzelne Zahlen zu finden, selbst wenn es nur solche gab. Daher gab sein Gefolge ihm nur noch Strassennamen, mit denen Sphinxistus exzellent umgehen konnte. Die Hausnummern durchsuchte der edle Rubinius dann selbst. Mit der Vorauswahl, die der Kaiser getroffen hatte, war er so schnell, das hier keine Beschwerden auftraten. Es führte sogar dazu, dass die Bittsteller nun bessere Ergebnisse bekamen, was natürlich komplett Sphinxistus zugerechnet wurde. Da Rubinius so nett war (weil Matz so nett ist), sagte er dazu nichts weiter und lächelte nur.
Es drohte nur an einer Stelle offenkundig zu werden: Rubinius …
> Das Ende der Hausnummerindizierung

- app/abilities/assignment_ability.rb
- app/abilities/mailing_list_ability.rb
- app/abilities/various_ability.rb
- app/controllers/concerns/authenticatable.rb
- spec/fixtures/assignments.yml
An ability in a conditional might not be defined, with a qualifier it can always be loaded, yielding consistent results.
Otherwise, the presence of this permission is dependent on the order of
the specs which maybe set the configuration-setting to define the
permission.
I also moved the ability to the other mail-things as I expected it
there.
Fixes #1332
> Repair ability-definition to fix Specs

- app/domain/export/tabular/people/household_row.rb
- app/domain/export/tabular/people/households.rb
- app/domain/person/household.rb
- app/domain/salutation.rb
- app/models/invoice_config.rb
- app/models/payment.rb
- config/locales/models.de.yml
- spec/domain/export/tabular/people/household_row_spec.rb
- spec/domain/export/tabular/people/households_spec.rb
Fixes hitobito/hitobito_die_mitte#162
Aktuell failen noch die Spec rund um den ImapMail-Bereich. Nachdem diese gefixt sind, solte man den branch nochmal rebasen, um hier verlässliche Infos zu bekommen.
> Anrede in Haushaltsexport

- app/domain/contactable/invalid_email_tagger.rb
- app/domain/person_tags/validation.rb
- db/migrate/20200924084559_add_hitobito_detail_to_taggings.rb
- spec/domain/contactable/invalid_email_tagger_spec.rb
Der vorgeschlagene Fix aus #1321 wurde umgesetzt, zusammen mit einer Spec, um künftige "Optimierungen" zu verhindern :smile: 
Fixes #1321
> Fix invalid mail tagger

- app/abilities/event_ability.rb
- spec/abilities/event_ability_spec.rb
The following sentence in the original ticket was disregarded during the implementation of #1047: "Die Events des eigenen Kantons sollen aber weiterhin sichtbar bleiben."
This means that, even when I have no permissions (such as a bottom member in a group), having any role in a group in the layer should be enough to allow me to see the events of the layer.
See also https://help.puzzle.ch/#ticket/zoom/3370
> Events in the same layer should still be visible to anyone

- config/initializers/sentry.rb
Also, we can either do very little about it or are already busy fixing
things.
The list is compiled from current exceptions and an old list from
airbrake/errbit-times.
> Begin to ignore things we do not care about

- .github/workflows/tests.yml
- bin/active_wagon.rb
We can explicitly choose a node version by using the `setup-node` action. Otherwise, GitHub will just install the newest official Node version in the runner images, without prior warning as it seems.
> Attempt to fix node.js version in CI

- db/migrate/20211125155817_upgrade_sessions_to_secure_storage.rb
Right now, this means that there are no sessions left to secure. If for
any reason a session cannot be deleted, it will be secured. This way,
all sessions are secured.
The deletion seems necessary because the serialization format has
changed.
> Delete sessions before securing them

- app/controllers/errors_controller.rb
- config/initializers/cookies_serializer.rb
Dieser PR löst auf recht entspannte Weise zwei Probleme, die meist gleichzeitig auftreten. Die Fehler selbst lesen sich deutlich dramatischer:
1. `765: unexpected token at 'I"ZW9uoZhOFpHCdnPfgnQIA:EF'):` (nicht ganz, aber so ähnlich)
2. `fatal: machine stack overflow in critical region` (genau so, ohne weitere Info in Sentry)
Das erste führt zum zweiten. Der Hintergrund könnte ein Blogpost werden, die Lösung ist
- Fehlerseiten nicht dynamisch zu rendern oder zumindest die Cookies nicht zu prüfen
- `Rails.application.config.action_dispatch,cookies_serializer = :hybrid`
> Repair fatal json decode

- config/locales/models.de.yml
- config/settings/payment_providers.yml
Raiffeisen Typo:
Sentry error: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47916/activity/?query=is%3Aunresolved
Fixes #1558
> Fix pubkey hash typos from raiffeisen and add valiant

- app/models/event.rb
- app/views/events/_form.html.haml
This is part of #1390, which somehow was not done. It enables wagons to customize the forms a little. This is used by https://github.com/hitobito/hitobito_insieme, which will reference this PR in a while.
> Allow to hide form-tabs without overwriting the whole template

- app/helpers/dropdown/invoice_new.rb
- app/helpers/invoices_helper.rb
- app/models/group.rb
- app/models/invoice_list.rb
- app/models/mailing_list.rb
- app/views/invoice_lists/_list.html.haml
- app/views/people/_actions_index.html.haml
- spec/controllers/invoice_lists_controller_spec.rb
- spec/models/invoice_list_spec.rb
closes: https://github.com/hitobito/hitobito_svse/issues/62
Problem was, when using the async BatchCreate, the recipient_ids would be lost due to it not being persisted in the database.
Meaning:
1. Click dropdown button, sets recipient_ids to `group.people.pluck(:id)`
2. Save invoice list entry
3. Realize there's too many recipients, thus extracting it into Job and pass `invoice_list.id`
4. Job finds invoice_list by id. Loses recipient_ids due to it not being persisted
Since we already use the receiver relation for mailing_lists i thought this would be the easiest and most in tune with the given structure. Any ideas why this wasn't done like this before?
> Allow group as invoice list receiver

- app/jobs/payments/ebics_import_job.rb
- spec/fixtures/payment_provider_configs.yml
- spec/jobs/payments/ebics_import_job_spec.rb
Wenn aktuell eine von den config's failed (was durchaus realistisch ist, siehe: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/48813/?query=is%3Aunresolved) failed der ganze Job
> Rescue and log Error manually to avoid failing whole job

- app/domain/event/filter.rb
- app/models/event.rb
- spec/controllers/events_controller_spec.rb
Bisher wurde der list scope bei den Events gar nicht verwendet. Daher ist auch die Sortierung nach event_dates nicht erfolgt.
> Order events by date

- package.json
- yarn.lock
das webpack(er) upgrade bewirkte das der webpack dev server im docker dev setup nicht mehr gestartet werden konnte.
```
webpack_1          | /usr/src/app/hitobito/node_modules/webpack-cli/bin/utils/prompt-command.js:46
webpack_1          | 	return func(...args);
webpack_1          | 	       ^
webpack_1          | 
webpack_1          | TypeError: Class constructor ServeCommand cannot be invoked without 'new'
webpack_1          |     at runWhenInstalled (/usr/src/app/hitobito/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
webpack_1          |     at promptForInstallation (/usr/src/app/hitobito/node_modules/webpack-cli/bin/utils/prompt-command.js:140:10)
webpack_1          |     at /usr/src/app/hitobito/node_modules/webpack-cli/bin/cli.js:32:43
webpack_1          |     at …
```
> Downgrade webpack dev server to make it work with new webpack version

- .github/workflows/wagon-tests.yml
Closes #1642 
Der GH Actions Trigger `schedule` hat keine payload. Wir benötigten diese Payload bisher aber, um den Wagon Namen (der getestet wird) herauszufinden. Im `github` context gibt es leider auch kein spezifisches Attribut für den Repository-Namen, daher muss das per bash script kurz raus gefiltert werden.
Damit sollten dann die cron CI's wieder laufen. Beispiele, welche mit diesem angepassten Workflow liefen:
- https://github.com/hitobito/hitobito_tenants/runs/5478514117?check_suite_focus=true
- https://github.com/hitobito/hitobito_sww/runs/5476757896?check_suite_focus=true
> Extract wagon name from github context

- app/controllers/oauth/profiles_controller.rb
This is to make matching between profile endpoint and API easier:
https://github.com/hitobito/hitobito/blob/master/app/serializers/role_serializer.rb#L35
> Add technical role class to OAuth profile endpoint

- app/domain/export/pdf/participation/person_and_event.rb
refs zammad#363971
Is there an actual way to prevent this from happening? It will still be able to break if the input is too large. I just gave it more space. `truncate` ? Any other way?
> PARTICIPATION: Fix breaking page on long text

- CHANGELOG.md
- app/controllers/invoice_lists_controller.rb
Dieser PR fixt das Problem, dass das Konto und die Kontostelle nicht gespeichert werden bei einer Sammelrechnung.
Closes https://github.com/hitobito/hitobito_cevi/issues/77
> Bug: Kontostelle & Konto wird nicht gespeichert

- app/domain/export/pdf/messages/letter/section.rb
- app/domain/export/pdf/section.rb
- app/views/invoices/_form.html.haml
- app/views/invoices/_infos.html.haml
- spec/domain/export/pdf/messages/letter/content_spec.rb
- spec/domain/export/pdf/messages/letter/header_spec.rb
Refs: https://github.com/hitobito/hitobito_sww/issues/57
The change to `#offset_cursor_from_top` was simply to improve the api.
Problem was, the offset calculation had to change from the constant margin `Letter::MARGIN` to `pdf.page.margins[:top]`
With this change, I then realized that our specs for letter/content & letter/header never specified a margin.
Thus we always tested these sections somewhat wrong. The positions on the actual PDF exports didn't change. The reasons for the spec adjustments are because the analyzer shows the positions in the `pdf.bounds`. And these bounds are tied to the margin.
Manual tests showed no changes however to these letter exports. Also the transformations to the positions in specs do make mathematically sense.
> Enable extensions for invoices form and infos, also move offset_cursor_from_top to all pdf sections

- app/controllers/devise/hitobito/passwords_controller.rb
- app/controllers/person/security_tools_controller.rb
- app/helpers/people_helper.rb
- app/helpers/sheet/person.rb
- app/helpers/sheet/person/security_tool.rb
- app/javascript/stylesheets/hitobito/_layout.scss
- app/mailers/person/user_password_override_mailer.rb
- app/views/person/security_tools/index.html.haml
- config/locales/views.de.yml
- config/routes.rb
- db/seeds/custom_contents.rb
- doc/e-mail/README.md
- lib/tarantula/tarantula_config.rb
- spec/controllers/person/security_tools_controller_spec.rb
- spec/fixtures/action_text/rich_texts.yml
- spec/fixtures/custom_content/translations.yml
- spec/fixtures/custom_contents.yml
- spec/mailers/person/user_password_override_mailer_spec.rb
- spec/models/custom_content_spec.rb
> Security overview

- CHANGELOG.md
- app/controllers/event/register_controller.rb
- app/controllers/public_events_controller.rb
- app/decorators/event_decorator.rb
- app/helpers/deprecation_helper.rb
- app/helpers/format_helper.rb
- app/helpers/layout_helper.rb
- app/helpers/unauthorized_helper.rb
- app/views/devise/passwords/new.html.haml
- app/views/event/register/index.html.haml
- app/views/events/_attrs_application.html.haml
- app/views/events/_tags.html.haml
- app/views/layouts/_unauthorized.html.haml
- app/views/public_events/_attrs_primary.html.haml
- app/views/public_events/show.html.haml
- bin/wagon
- spec/utils/imap/connector_spec.rb
Um die Anmeldungen für Anlässe zu erleichtern, wird die extra Seite zwischen Anlassinformationen und Kontaktinformationen direkt im ersten Schritt angezeigt.
Die Login-Links oben rechts können pro Seite ausgeschaltet werden, um Verwirrung zu vermeiden.
Weiterhin werden nur die eingetragenen Infos vom Anlass angezeigt und ein Darstellungsbug bei der Anzeige der vergebenen Tags behoben. 
Fixes #1775
> Verbesserungen für Anlassanmeldungen

- app/domain/messages/letter_dispatch.rb
- app/domain/people/household_list.rb
- spec/domain/people/household_list_spec.rb
Fixes #1810
Fixes #1553
Ich habe folgende Änderungen vorgenommen, geordnet nach absteigender vermuteter Nützlichkeit für die Performance:
- Alle IDs der zu gruppierenden Personen werden zuerst in Memory geladen, und die gruppierenden SQL-Queries arbeiten dann mit `WHERE id IN (...)` statt mit den komplexen Bedingungen die von den Abo-Subscribers her kommen. Bei ca. 44'000 Personen sind das theoretisch 44'000 * 4 Bytes (integer ID) = ca. 172 kB RAM das dafür nötig ist.
- Die Personen die in Haushalten sind und Personen die in keinem Haushalt sind werden in zwei Teilqueries berechnet und via `UNION ALL` kombiniert
- ~~Die Daten werden jetzt nicht mehr während dem Batchen neu sortiert, sondern in der Reihenfolge belassen die vom `UNION ALL` her kommt (zuerst die Haushalte in absteigender …
> Improve household list performance

- app/javascript/stylesheets/hitobito/modules/_invoice.scss
- app/views/invoices/_filter.html.haml
Before, there were two forms for the filter
Meaning when selecting a daterange and then changing the other filter, it removes the daterange filter
> Fix invoices filter by nesting all in the same form tag

- Gemfile
- config/application.rb
- lib/tasks/db.rake
- lib/tasks/delayed_jobs.rake
Aktuell werden bei jedem Reload in der Console auch immer die Jobs neu in die DB geladen. Ich würde gerne etwas mehr Kontrolle darüber haben. Da der DJ-Setup im Kern ein DB-Setup ist, habe ich es als Folgetask an die Migrationen angehängt. Damit ist es erstmal aus dem Weg während des Entwickelns, aber vorhanden, wenn man einen Setup macht. 
Ich habe noch nicht geschaut, welche Wagons davon auch noch betroffen sind. Da der bisherigen Weg ja auch noch funktioniert, würde ich das dann bei Bedarf und Gelegenheit angehen.
> DJ-Setup separieren

- app/abilities/token_ability.rb
- app/controllers/application_controller.rb
- spec/controllers/person_duplicates/ignore_controller_spec.rb
- spec/controllers/person_duplicates/merge_controller_spec.rb
Possible fix for issue: [PERSON: Daten via API vs JSON+Token inkonsistent #1460 ](https://github.com/hitobito/hitobito/issues/1460)
Adds the ability to show all details of a person when using the api-key.
Fixes #1460
Fixes hitobito/hitobito_pbs#193
> PERSON: Daten via API... add ability to show details

- app/domain/events/filter/groups.rb
- spec/domain/events/filter/groups_spec.rb
Fixes #1861 
Previously, the `OR` circumvented the `type='Event::Course'` condition as soon as an event was globally visible, leading to server errors when trying to display globally visible camps and events in the course list.
Notice in the examples below that the parantheses right after `WHERE` are gone now.
We are now correctly using separate `WHERE (...) AND (...) AND (... OR ...)` conditions,
rather than wrongly `WHERE (... AND ... AND ... OR ...)`
Query before this PR:
```sql
WHERE (`events`.`type` = 'Event::Course' AND
(event_dates.start_at <= '2023-09-28' AND event_dates.finish_at >= '2022-09-28' OR
event_dates.start_at <= '2023-09-28' AND event_dates.start_at >= '2022-09-28') AND
`events`.`state` IN ('created', 'confirmed', 'application_open', 'application_closed', …
```
> Take care not to circumvent existing conditions when including globally_visible events

- app/domain/event/precondition_checker.rb
- app/javascript/javascripts/modules/event_kind_preconditions.js.coffee
- app/models/event/kind_qualification_kind.rb
- app/views/event/kinds/_precondition_fields.html.haml
- app/views/event/participations/_precondition_warnings.html.haml
- config/locales/models.de.yml
- spec/domain/event/precondition_checker_spec.rb
Closes: #1870 
Nach Absprache mit @ThomasEllenberger haben wir uns dazu entschieden eine weitere Option "Muss gültig oder reaktivierbar sein" einzufügen.
Somit sind die Vorbedingungen so:
- "Muss gültig sein": Muss Qualifikation haben welche nicht abgelaufen ist. Reaktivierbarkeit spielt keine Rolle
- "Muss gültig oder reaktivierbar sein": Muss Qualifikation haben. Wenn abgelaufen, muss sie in der Reaktivierbarkeitsperiode sein.
- "Muss gültig oder abgelaufen sein": Muss Qualifikation haben. Darf abgelaufen sein. Reaktivierbarkeit spielt keine Rolle.
> Add valid or reactivateable precondition to event kind qualification kind

- .github/workflows/tests.yml
We are only interested to run against code-changes. If this happens to a Branch that ist part of a PR or not is not relevant. Furthermore, the push-trigger was there all the time, so the 'PR has opened'-trigger is redundant and most of the time late.
> Do not run when the PR is opened/reopened, just on push

- db/migrate/20221207155409_clean_serialized_invoice_item_attributes.rb
A migration left some data in a serialized column untouched. This is hereby fixed.
> Cleanup serialized invoice items

- app/domain/mailing_lists/subscribers.rb
Fixes https://github.com/hitobito/hitobito/issues/1440#issuecomment-1348178994
It is not enough to delete all subscriptions of a group while archiving, because the roles of the group might also be included in the mailing list via a subscription of a higher group. E.g. say an Abteilung has 3 child groups with the same type, and the same "Member" role. If on the Abteilung there is a mailing list including all "Member" roles in the Abteilung, then I can archive one of the child groups and deleting its subscriptions will do nothing. The actual subscription belongs to the Abteilung, so it looks something like this:
```
Subscription {
group: Abteilung,
role_types: ['Group::ChildGroup::Member'],
}
```
For this reason, we really have to explicitly exclude archived roles from all mailing lists.
> Really exclude archived roles from mailing lists

- spec/fixtures/invoices.yml
Since the year pagination goes by issued_at, it is important that it is in the current year
> Make spec Jahresumbruch-safe

- config/initializers/sentry.rb
I added an error that mostly comes from misbehaving clients and script-kiddies and took the opportunity to categorize and group things. My goal is to keep that config maintainable and a huge list of Exception without a proper explanation why they are there is not my idea of maintainable.
> Start categorizing errors to make config more understandable

- app/controllers/people_controller.rb
- config/locales/views.de.yml
> Klarere Flash Message bei E-Mail-Verifikation

- app/domain/export/csv/generator.rb
Adding an UTF8 BOM allows MS Excel to read UTF-8 correctly whithout changing the charset manually.
The BOM is only added if the settings.yml file explicitly specifies to use UTF8 for csv exports.
> Adding UTF8 BOM to CSV-Exports

- CHANGELOG.md
- app/controllers/groups_controller.rb
- app/decorators/group_decorator.rb
- app/domain/feature_gate.rb
- app/helpers/groups_helper.rb
- app/models/group.rb
- app/models/role.rb
- app/views/groups/_attrs.html.haml
- app/views/groups/_form.html.haml
- bin/single-file-update-copyright
- config/initializers/doorkeeper.rb
- config/initializers/doorkeeper_openid_connect.rb
- config/locales/models.de.yml
- config/settings.yml
- config/settings/test.yml
- db/migrate/20230115160409_add_nextcloud_link_to_groups.rb
- db/schema.rb
- doc/development/08_oauth.md
- lib/tasks/hitobito.rake
- spec/controllers/oauth/userinfo_controller_spec.rb
- spec/decorators/group_decorator_spec.rb
- spec/domain/export/csv/groups/list_spec.rb
- spec/features/oauth_workflow_spec.rb
- spec/models/group_spec.rb
- spec/models/role_spec.rb
Everything is hidden behind the FeatureGate `groups.nextcloud`. This is disabled by default.
Once activated, you can
- add a nextcloud-url to any layer-group and have it displayed on every group in the layer
- use a nextcloud-scope for oauth-apps. This allows to pass user information and a list of groups to nextcloud to provision users there.
- configure roles to either map to a fixed groupname or a dynamic group, depending on the group you have the role on.
Apart from that, I added a rake-task to determine the correct configuration quicker. The idea is to have checks for everything that requires extra-steps to be configured, collected in `rake hitobito:check_config`.
Closes #1854
> Allow for integration of nextcloud

- app/views/events/_list_table.html.haml
Same as f0ffaa9f234fb29c7a974253c3d8a475f02724ee, but for the apply button.
Fixes https://help.puzzle.ch/#ticket/zoom/5753
Since my time for working on that ticket is limited, and since we don't run specs on branches anymore since #1935, I have to open a PR to run the specs.
> Link to first event group instead of parent group

- app/jobs/mailchimp_synchronization_job.rb
- app/jobs/reoccuring_mailchimp_synchronization_job.rb
- spec/jobs/mailchimp_synchronization_job_spec.rb
- spec/jobs/reoccuring_mailchimp_synchronization_job_spec.rb
After a few linting and cleanup steps, I unexpectedly found the bug. 
The perform-methods of the `ReoccuringJob` handles the rescheduling. Therefore, overwriting it prevents the rescheduling.
The current healthz-checks for the DJ pod catch this, but it would be cleaner to reschedule the job directly instead of relying on external reboots.
> Repair Mailchimp-Sync

- Gemfile.lock
- config/initializers/prometheus.rb
- config/puma.rb
In order to get more metrics in our updated dashboards, we need to update the exporter gem. The config did not need changes.
> Upgrade prometheus exporter

- app/models/group/types.rb
Admist the cloud of Rubocop-Fixes lies a small change. "Thou shalt not include deleted groups in thy course listing" said a voice. As the fog was pushed away by the growing sunlight, it became apparent that a programmer tried to be funny. 
All there was, was a subtle oversight and a small fix. Well, that, and the sincere hope that this PR is deemed worthy to be merged.
And with hopeful eyes the programmer looked towards the reviewer...
> Course filter without deleted groups

- app/controllers/invoices_controller.rb
- app/models/invoice.rb
- app/views/invoices/_filter.html.haml
Behaviour before: Invoice lists have the current year (excluding first and last day) preselect, so when looking at old invoice lists, the list is empty and the fact that the end days are not including is surprising.
Behaviour after: Invoice lists by default show invoices starting at the beginning of the year when the list was created, to the end of the current year. The first and last day of the range is included in both the default range and when a different range is chosen by the user.
Tests: A few tests failed in my local run, but they don't look related to this change.
> Invoice lists: display all invoices by default and make ends of range inclusive

- app/domain/people/one_time_password.rb
- config/settings.yml
- spec/domain/people/one_time_password_spec.rb
Resolves #1830 
Die library erlaub auch ein `drift_ahead` (https://rubydoc.info/github/mdp/rotp/master/ROTP%2FTOTP:verify). Daraus schliesse ich, dass die drift parameter nur das jeweilige ende es slots verschieben und nicht den ganzen slot.
Der Code akzeptiert einen Time-Drift von maximal +/- 15 Sekunden. Das RFC zum TOTP spricht von bis zu 60s Verschiebung… (6.  Resynchronization, https://www.ietf.org/rfc/rfc6238.txt). Ich denke das sollte aber reichen um das Problem zu umgehen.
> Fix totp drift

- app/javascript/stylesheets/hitobito/modules/_profil.scss
Limit width of enlarged profile image to be the maximum of the screen width.
Relates to #2044
> fix: enlarged profil image for mobile devices

- app/controllers/subscriptions_controller.rb
- app/jobs/export/subscriptions_job.rb
Context: https://help.puzzle.ch/#ticket/zoom/6146
https://github.com/hitobito/hitobito_pbs/pull/276
Even though in the views present, the subscriptions export never (AFAIK) exported table displays
> Enable subscriptions export to export table displays

- app/controllers/addresses_controller.rb
- app/helpers/standard_form_builder.rb
- app/javascript/javascripts/modules/contactables/contactable_address_field.js.coffee
- app/javascript/stylesheets/hitobito/_form.scss
- app/javascript/stylesheets/hitobito/modules/_privacy_policy.scss
- app/views/contactable/_address_fields.html.haml
- app/views/devise/sessions/_form.html.haml
- app/views/groups/self_registration/_form.html.haml
- app/views/groups/self_registration/new.html.haml
- app/views/people/_privacy_policy_acceptance_field.html.haml
- spec/features/roles_controller_spec.rb
Die `.span*` CSS Klassen sind sehr mühsam um damit zu arbeiten. Ich habe das Layout dieser Felder jetzt stattdessen mit Flexbox gelöst. Das war in 2012 vielleicht noch nicht so verbreitet, aber heutzutage das normalste der Welt.
Dies ist die Grundlage für ein Issue in einem privaten Repository. Ich verlinke von dort hierhin, aber halt nicht von hier dorthin. Ausserdem verwandt mit https://github.com/hitobito/hitobito_sww/issues/119
Dieser PR enthält ausserdem diverse visuelle Cleanups von unter Zeitdruck realisierten (SWW-)Features.
Hier ein vorher-nachher-Vergleich auf diversen Bildschirmgrössen:
| Vorher  | Nachher |
| ------------- | ------------- |
| ![Screenshot 2023-05-24 at 10-33-58 hitobito - Puzzle ITC](https://github.com/hitobito/hitobito/assets/7566995/dc05713c-504d-4509-8f50-ec …
> Einheitliche Breiten für die PLZ/Ort und Land Felder

- lib/release/highlevel.rb
- lib/release/main.rb
Since some wagons have translations via transifex and others don't, the release-script should not
care. Therefore, this adds a check to only update the translations of wagons which have transifex
configured.
Fixes hitobito/hitobito_jemk#7
> RELEASE: Einsprachigkeit

- app/abilities/various_ability.rb
This has been a pain because when the Ability constant gets referenced before any course types have been defined (e.g in the wagon.rb of a wagon) the permissions just did not get registered. This happened because when the Ability constant was loaded, the VariousAbility constant was aswell. Thus already evaluating course types before they were loaded
Fixes: https://github.com/hitobito/hitobito_jubla/actions/runs/5239299435/jobs/9458999780
Fixes: #2113
> Do not implement logic on class level for permissions

- .github/workflows/security-scanners.yml
The current version of brakeman (rightfully) drops support for Ruby 2.7.
We do not (yet).
So, long story short: we use the best brakeman-version there is today for our current ruby-version.
This PR should change our workflow to not complain about not using the latest version anymore.
> Let's keep running brakeman

- config/locales/models.de.yml
- config/locales/models.en.yml
- config/locales/models.fr.yml
- config/locales/models.it.yml
This also removes them as dropdown options from the form which should have already been done in #2011
Closes: #1982
> Remove invoice config payment slip translations

- app/domain/table_displays/people/login_status_column.rb
Fixes: https://help.puzzle.ch/#ticket/zoom/6415
> Use fully-qualified column name to make sure uniq works on login status

- db/seeds/custom_contents.rb
Anstelle von
Wir haben deine **Vornameldung** für die Teilnahme an folgendem Anlass erhalten:
sollte es 
Wir haben deine **Voranmeldung** für die Teilnahme an folgendem Anlass erhalten:
heissen.
> Typo Vornameldung -> Voranmeldung

- app/controllers/public_events_controller.rb
- app/views/public_events/show.html.haml
- spec/controllers/public_events_controller_spec.rb
Avoid copying duplicated template code in wagon by controlling visibility of `application_attrs` on `public_events/show` page via class_attribute
> Control public events application_attrs via class_method

- app/domain/export/pdf/messages/letter/header.rb
I checked, it's only used in the sww wagon
> Use different argument for SWW wagon

- app/abilities/person_ability.rb
- spec/abilities/person_ability_spec.rb
Wir erhalten viele Anfragen von Abteilungen und Kantonalverbänden, dass sich Personen mit 2FA nicht einloggen können, oder dass 2FA für diese Personen nicht zurückgesetzt werden kann. Ich schlage deshalb vor, dass nicht nur admins, sondern auch Personen mit layer_and_below_full oder layer_full für ihre Mitglieder 2FA zurücksetzen können.
Das Deaktivieren (ungleich Zurücksetzen) von 2FA soll weiterhin nur für admins zur Verfügung stehen. Somit können Admin weiterhin 2FA für einzelne Personen forcieren, ohne von lokalen Leiter*innen übersteuert zu werden. Ausserdem entsteht für die lokalen Leiter*innen weniger die Verwirrung ums Zurücksetzen und Deaktivieren, da letztere Option gar nicht zur Verfügung steht.
> Allow 2fa reset for layer and below full

- app/domain/structure_parser.rb
- lib/tasks/hitobito.rake
- spec/domain/structure_parser_spec.rb
`rake hitobito:roles` generates a structure which we also use to describe new instances. Therefore, parsing this structure saves a lot of repetitive work and keeps things consistent. The generated content still needs to be placed into the right files and many more manual steps are needed for a full group-definition. But this can give you a head-start. Also, it might need more work with the next new instance.
> Structure parser

- .pryrc
- CHANGELOG.md
- app/controllers/json_api/groups_controller.rb
- app/controllers/json_api/people_controller.rb
- app/resources/group_resource.rb
- config/routes.rb
- doc/development/05_json_api.md
- spec/controllers/json_api/groups_controller_spec.rb
- spec/requests/json_api/group_schema.rb
- spec/requests/json_api/groups_spec.rb
- spec/requests/json_api/person_schema.rb
- spec/resources/group/reads_spec.rb
- spec/resources/person/reads_spec.rb
- spec/resources/role/reads_spec.rb
- spec/spec_helper.rb
- spec/support/resource_spec_helper.rb
- swagger/swagger.yaml
fixes hitobito#2243
Ich denke das setzt grob mal den endpoint um. Bei den specs bin ich mir noch unsicher, folgendes ist mir unklar:
- Wofür genau brauche ich das schema in der swagger api doku? Wieviel JSON:API standard wollen wir nachbauen? 
- Wollen/Brauchen wir wirklich so umfangreiche controller specs wie bei people? 
Fürs Api selber denke ich es wäre besser den type filter as is zu belassen und nicht wie spezifiziert hier noch auf human names zu mappen. Archivierte Gruppen habe ich jetzt grundsätzlich mal nicht drinnen via endpoint, müssten noch schauen ob das via filter sinnvoll zu machen und wie das zu dokumentieren wäre
> Add groups to json:api

- lib/release/highlevel.rb
- lib/release/lowlevel.rb
Mitten im Trubel der Feiertagsvorbereitung und der Festtagsmusik nehmen wir uns häufig mehr vor, als wir sollten. Einige Leute machen sogar komplett unnötige Zusagen. Im Zwischenmenschlichen kann man dies noch als Scherz überspielen. "Haha, ich halte dir die Tür auf, die schon geöffnet ist :joy: ". 
`git` findet das allerdings nicht so gut. Und genau hier setzt dieser PR an. Es werden nur noch Commits gemacht, wenn es auch sinnvoll ist. 
Für eine bessere Welt, in der mehr Integrationsumgebungen mit dem gleichen Codestand deployed werden können.
Fixes #2268
> Vermeidung von Commits ohne Changes

- app/controllers/subscriber/group_controller.rb
- spec/controllers/subscriber/group_controller_spec.rb
Closes: #2270 
Im `subscriber/event_controller` kann auch ein Anlass via Gruppenname gesucht werden.. Ich fand das jetzt aber zu komplex um mir dafür noch ein Bein auszureissen. Zumal man dort via Event auf Gruppe schliessen muss etc.
Wenn das aber noch nötig ist, müssen wir dort nochmal dahinter.
> Make groups searchable by static name

- app/domain/group/privacy_policy_finder.rb
- spec/domain/group/privacy_policy_finder_spec.rb
fixes hitobito/hitobito#2281
acceptance is always needed unless we are an active record model and the value is already persisted in the database
> Improve policy_finder acceptance_needed? logic

- app/helpers/standard_form_builder.rb
- app/views/groups/self_registration/_main_person.html.haml
- add missing html_safe for boolean caption label
- pass form as locals when extending main_person partial
Refs hitobito/hitobito_sac_cas#162
Fixes #2307
> Minor changes for self_registration

- .github/workflows/prepare-version.yml
- .github/workflows/remote-version.yml
- .github/workflows/stage-settings.yml
- Gemfile
- Gemfile.lock
- app/domain/release_version.rb
- bin/version
- config/brakeman.ignore
- lib/release/main.rb
- lib/tasks/ci.rake
- lib/tasks/dev.rake
- spec/bin/version_spec.rb
- spec/domain/release_version_spec.rb
Um das geplante Versionsschema sowohl im Normalfall als auch den angedachten Ausnahmen zu unterstützen, wurden die Workflows und Hilfsscripte angepasst.
Die Version wird als MAJOR.MINOR.PATCH festgehalten. Aus Nutzersicht gibt es nun etwas mehr Auswahl beim Starten des Workflow prepare-release. 
See #2214 
Dieser Helper kann Vorschläge für die folgenden Varianten ausgeben:
- patch (Release "ausser der Reihe", erhöht die Patch-Version)
- regular (regelmässiger Release, erhöht die Minor-Version, falls dies nicht bereits kürzlich gesehen ist)
- integration (fügt an die aktuelle production-version eine aufsteigende Zahl an)
- custom (es wird eine übergebene Version schlicht als Vorschlag verwendet)
Aus Sicht des version-scripts ist patch hier der Normalfall.
Es gibt nun Specs für dieses …
> Improve version handling

- .github/workflows/build-image.yml
- .github/workflows/sbom.yml
- .github/workflows/security-scanners.yml
- .github/workflows/tests.yml
- .github/workflows/wagon-tests.yml
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/cache@v3. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update actions to follow deprecation warning

- Gemfile.lock
"Mostly harmless"
https://github.com/ruby/timeout/releases/tag/v0.4.1
> Bump timeout-gem

- spec/domain/people/merger_spec.rb
A `let` in rspec is caching its value. Therefore it is not the right tool if you just want to give something a name or save a few keystrokes.
fixes #1784
> Fix flaky spec

- app/controllers/people_controller.rb
- app/decorators/person_decorator.rb
- app/views/people/_roles.html.haml
Seems to improve people#index page by about 30-50%
- include picture_attachment in scope
- filter preloaded roles in memory
> Speed up people#index by removing 3n+1 queries

- lib/tasks/dev.rake
When working in a wagon that has enforced 2FA, TOTP needs to be setup upon first login. If you create a new local admin, it most certainly has a role that needs this.
This PR set the secrets in a way that is repeatable and therefore reduces the friction when supporting organizations using such secure wagon setups. The same 2FA-setup can then be used again for development. It is not intended for production or integration setups, it should be (as before) be purely local admin.
> Setup TOTP for local dev-admins

- CHANGELOG.md
- app/controllers/invoices_controller.rb
- app/helpers/invoices_helper.rb
- app/helpers/sheet/invoice.rb
- app/helpers/sheet/invoice_list.rb
- app/helpers/standard_table_builder.rb
- app/models/invoice.rb
- app/views/invoices/_table.html.haml
- config/locales/models.de.yml
- spec/models/invoice_spec.rb
This adds a new column "last payment at" to the invoices-tables and allows sorting by it.
It further adds the sorting for "amount paid", which has been missing (it was displayed, but did not work).
The invoice-area is now wrapped in a group-sheet to reduce the disruptive design of it. In future changes to this area, a more common navigation (tabs) might be added.
This also contains a bug fix for when invalid dates are entered into the date-range fields.
Fixes hitobito/hitobito_sww#147
> Sort invoices by date of last payment

- .github/workflows/sbom.yml
https://github.com/CycloneDX/cdxgen/pull/837 removed the XML format. Fortunately, our CLI SBOM merge tool can also handle JSON. Hopefully, DependencyTrack can also handle it.
To avoid future breakage, the major version of the package is pinned.
> Handle and avoid breaking changes in cdxgen

- Gemfile
- Gemfile.lock
- spec/support/graphiti/shared_examples.rb
The test will also be run in all wagons, to make sure that we don't break the documentation in just one wagon either.
Previously, we fixed the validity in https://github.com/hitobito/hitobito/commit/cfff477a6228478ddc72902cfa7758fc63b6ea11 and https://github.com/hitobito/hitobito/pull/2492
> Add test to make sure openapi.yaml is kept valid

- app/abilities/token_ability.rb
- app/serializers/group_serializer.rb
- spec/abilities/token_ability_spec.rb
- spec/controllers/groups_controller_spec.rb
Fixes #2160
Some attributes in the group serializer don't actually show when accessing the page by service token. 
The problem seems to be that the token isn't allowed to show_details:
https://github.com/hitobito/hitobito/blob/51e0e4779120b8c82c56817feb33c3f858504241/app/serializers/group_serializer.rb#L50
This fix looks very good, but doesn't work 😎 May it help someone else to find out what is going on
> Trying to fix the api for service tokens

- app/models/async_download_file.rb
Refs hitobito/hitobito_sac_cas#271
The filename there must be like "Adressen_00001234.csv", with capital A, for maximum backwards compatibility.
> Don't downcase async download filenames

- app/models/concerns/encryptable.rb
- spec/models/group_spec.rb
In essence, I changed the guard-condition from `data.nil?` to `data.blank?`. While at it, I added a small spec for this exact case and formatted the file according to rubocop's rules.
The original specs for this are lost, most likely when moving from the separate `GroupSettings`-model to attributes directly on the `Group`.
See https://sentry.puzzle.ch/pitc/hitobito-backend/issues/66965 for stacktrace and such.
> Handle missing encrypted value better

- app/controllers/event/participations_controller.rb
- app/views/event/participations/_list.html.haml
Otherwise, for reasons I could not debug fully, the columns person.additional_information and participation.additional_information are both requested as additional_information when counting the total pages. When requesing this information earlier, the error does not occur, therefore I do.
See: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/67232
> Prepare pagination to avoid errors with duplicate columns

- .github/actions/core-ci-setup/action.yml
- .github/workflows/tests.yml
Reduces the time for running CI on GitHub Actions from roughly 15-16min to roughly 10min, and you get your result even faster when you are only working on a feature spec or rubocop fix. Plus we can rerun only a single type of spec if desired.
Successful CI run: https://github.com/hitobito/hitobito/actions/runs/8877767084
We could improve this even more by splitting up the main specs into more parallel specs, but I'd say we try out how this feels and then go from there.
We could also do something similar for the wagons, but wagon tests already take less time than the core tests, and it might be a little more complicated to set up because of our reusable workflow setup, and because so far in the wagons we use a single rake command which runs all tests in series.
> Run core specs in parallel

- app/helpers/standard_form_builder.rb
- app/javascript/javascripts/modules/remote_autocomplete.js
- spec/features/event/events_controller_spec.rb
Refs: hitobito/hitobito_sac_cas#478
> Add remote typeahead spinner and no results message

- app/models/future_role.rb
- app/models/person.rb
- app/models/self_registration/person.rb
- spec/models/future_role_spec.rb
Fixes hitobito/hitobito_sac_cas#493
- **Rewrite Person#household_people as pure activerecord query without plain sql**
- **SelfRegistration::Person: allow validating/saving with custom validation context**
- **FutureRole: forward validation_context when validating target role**
> Changes needed for SAC family main person

- app/javascript/controllers/remote_autocomplete_controller.js
- app/javascript/javascripts/modules/remote_autocomplete.js
- app/views/layouts/application.html.haml
Wrapt den für die Personen Such relevanten Teil des Plugins in einem Stimulus Controller. Das behebt den Bug für das `people_field` auf dem StandardFormBuilder.
> Fix person field for invalid forms, (#2565)

- app/javascript/stylesheets/hitobito/_form.scss
- app/javascript/stylesheets/hitobito/_modal.scss
- app/views/subscriber/group/_roles.html.haml
- app/views/subscriber/group/_tags.html.haml
- spec/features/subscriber/group_controller_spec.rb
- bigger group names
- visually separate groups
- do not render layer without subgroups
> UI improvements in subscribers/group/roles filtering

- .github/workflows/wagon-tests.yml
When testing the wagon, it tries to find a matching branch in the core and youth-wagon.
If the feature-branch cannot be found, it should default to the value from the input, which in turn defaults to `master`.
This allows to have synced changes in the wagon and the core, just by naming the feature-branch the same.
I only tested the output of the `git ls-remote | cut | grep`-command, manually outside the action. A full integration-test is of course possible, but IMHO not worth the effort. If needed, I would revert and redo this.
> Try to use a common branch for all repos

- app/abilities/ability_dsl/base.rb
- doc/architecture/08_konzepte.md
- doc/development/03_guidelines.md
Wie etwas funktioniert sollte in der architektur dokumentation und nicht in den guidelines beschrieben sein.
> [skip ci] Move ability aspects from guideless to architecture konzepte

- app/views/people_filters/_form.html.haml
- app/views/people_filters/_language.html.haml
- app/views/subscriber/filter/_form.html.haml
The filter for the core-attribute `language` is always shown. This PR restricts the filter to wagons that use the field. 
See #2620
> Restrict Language Filter

- Gemfile
- Gemfile.lock
Fixes a build error during bundle install:
Installing hpricot 0.8.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> Use hpricot from GitHub which builds on newer systems

- db/seeds/support/group_seeder.rb
- db/seeds/support/person_seeder.rb
`Faker::Internet.safe_email` has been deprecated in 3.2.0 and removed in 3.2.3.
See https://github.com/faker-ruby/faker/blob/main/CHANGELOG.md#v320-2023-04-14
> Replace Faker::Internet.safe_email with email

- app/models/group/types.rb
During seeding I got the following error:
TRANSACTION (10.7ms)  ROLLBACK
undefined method `layer_group_id' for nil:NilClass excluded from capture: DSN not set
rails aborted!
NoMethodError: undefined method `layer_group_id' for nil:NilClass (NoMethodError)
layer_id = self.class.layer ? id : parent.layer_group_id
^^^^^^^^^^^^^^^
/usr/src/app/hitobito/app/models/group/types.rb:57:in `set_layer_group_id'
Tasks: TOP => wagon:seed
By using the safe access seeds went through.
> Fix seeding by using safe access in Group::Types#set_layer_group_id

- app/models/group/types.rb
This reverts commit 8b9c1e6af01ea4a156efc53c35f5cecb006f1bc4.
> Revert "Fix seeding by using safe access in Group::Types#set_layer_group_id (#2648)"

- app/helpers/people/membership/verification_qr_code.rb
That way we can easily link the QR image to the target URL.
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/533
> Make VerificationQrCode#verify_url public

- app/views/events/_attrs_application.html.haml
application_closing_at wird doppelt ausgegeben. Dies führt dazu, dass das Feld "Anmeldeschluss" zwei Mal im Frontend sichtbar ist und den User verwirrt.
> Remove duplicate field

- .github/actions/core-ci-setup/action.yml
- .github/actions/wagon-ci-setup/action.yml
- .github/workflows/wagon-tests.yml
- lib/templates/wagon/lib/tasks/spec.rake
Fixes #2588 
Beispiel Runs des Workflows:
Generic Wagon (kein dritter Wagon, keine Feature Specs): https://github.com/hitobito/hitobito_generic/actions/runs/9383854180
SAC Wagon (inkl. youth Wagon, inkl. Wagon-Feature-Specs): https://github.com/hitobito/hitobito_sac_cas/actions/runs/9383912986
Mögliche weitere Verbesserungen:
> Run wagon specs in parallel

- config/environments/development.rb
`DEPRECATION WARNING: action_view.raise_on_missing_translations is deprecated and will be removed in Rails 7.0. Set i18n.raise_on_missing_translations instead. Note that this new setting also affects how missing translations are handled in controllers.`
> Fix deprectation warning

- app/helpers/sheet/group/nav_left.rb
- app/models/group/nested_set.rb
Fixes an edge-case of #2673
Sometimes, layers do not have subgroups.
> Allow the left navigation for empty layer-groups

- config/initializers/acts_as_taggable_on.rb
- spec/controllers/person/tags_controller_spec.rb
We have subscription-tags which have (rightfully) a dependency on the tags. In preventing automated deletion of tags, we essentially prevent an error that occurs when the 'unused' tag is actually used as a subscription-tag. This way, when removing the tags from a person, we can add it later again without breaking the automated subscription to a mailing-list.
This resolves a help-ticket and the sentry-issue for this: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/64849
> Prevent automatic deletion of tags

- app/models/wizards/step.rb
- spec/models/wizards/step_spec.rb
This allows to easily use case/when to implement `step_after` in wizards.
> Override case operator for Wizards::Step

- Gemfile
- spec/requests/generic_oauth_index_spec.rb
- spec/requests/generic_oauth_show_spec.rb
When running tests there is no need for them and they slow down specs.
Non scientific benchmark, running `rspec spec/features/` in hitobito_sac_cas:
Before:
```
Finished in 3 minutes 41.8 seconds (files took 5.14 seconds to load)
140 examples
```
After
```
Finished in 3 minutes 5.7 seconds (files took 3.95 seconds to load)
140 examples
```
> Make better_errors/binding_of_caller dev only dependencies

- app/models/household.rb
- app/models/households/log_entries.rb
- spec/models/household_spec.rb
fixes hitobito/hitobito_sac_cas#570
Those changes are needed as `#save` must now yield the updated people records. This is required to make the SAC wagon changes possible which depend on the updated `household_key` on the people records.
> SAC Household Anpassungen

- config/initializers/delayed_job_config.rb
`delayed_job` hat die gesamte Rails App alle 5 Sekunden neu initialisiert. Dies verbraucht viele Ressourcen.
```
Delayed::Backend::ActiveRecord::Job Update All (0.3ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2024-07-08 13:47:45', `delayed_jobs`.`locked_by` = 'host:598ed481adca pid:1' WHERE (((run_at <= '2024-07-08 13:47:45.424631' AND (locked_at IS NULL OR locked_at < '2024-07-08 09:47:45.424644')) OR locked_by = 'host:598ed481adca pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1
Raven 3.1.2 configured not to capture errors: DSN not set
Creating scope :configured. Overwriting existing method MailingList.configured.
Creating scope :anyone. Overwriting existing method MailingList.anyone.
Creating scope :opt_out. Overwriting existing method …
```
> stop delayed job from reloading whole rails app all 5 seconds

- spec/spec_helper.rb
This has been tested by running the specs in the SAC_CAS-Wagon in a certain order:
rspec ./spec/decorators/role_decorator_spec.rb ./spec/resources/group/reads_spec.rb --seed 11597
Surely, this might happen anywhere where both generated URLs and decorators with draper are being tested.
> Reduce flaky specs by no altering the environment too much

- .github/workflows/wagon-tests.yml
This should reduce (somewhat) false negatives on the dashboard or whereever you get your action-status.
Integration-proof: https://github.com/hitobito/hitobito_sac_cas/actions/runs/9969667188/job/27547055188#step:6:20
> Switch to lenient feature-specs for wagon-test as well

- app/views/layouts/application.html.haml
- app/views/layouts/oauth.html.haml
It's currently like this:
```html
</body>↩
<footer id='page-footer'>↩
```
> Fix HTML Structure: footer needs to be inside body.

- spec/decorators/qualification_decorator_spec.rb
The fabricator gets initialized before the time traveled date is set, or it caches the current date leading to a bug.
> deflake qualification_decorator_spec

- app/views/wizards/show.html.haml
The real wizard view is in https://github.com/hitobito/hitobito/blob/304772c9e773f54ba04f24a85078d69d00859fac/app/views/groups/self_registration/show.html.haml
It has been added in #2750 but doesn't seem to serve any purpose.
> Remove unused wizard show template

- app/javascript/javascripts/modules/datepicker.js.coffee
- app/javascript/stylesheets/hitobito/modules/_ui-datepicker.scss
Allow the UI Datepicker to set min/max dates and make it visible, so that dates outside this range are not selectable by not displaying them. Not displaying the dates, is the best styling option in my opinion, since the dates are currently already displayed in a light grey.
> Introduce datepicker min/max Date

- app/models/person.rb
Required for https://github.com/hitobito/hitobito_sac_cas/pull/864 ([failing ci](https://github.com/hitobito/hitobito_sac_cas/actions/runs/10487966679/job/29049457501?pr=864))
wenn :data_quality nicht existiert, wird es ignoriert. ist für andere wagons also kein problem.
> Exclude `data_quality` in `validates_by_schema`

- .github/workflows/tests.yml
When the trigger is on all branches and all pull-requests, the tests will run twice when not originating from a fork. Thus we limit it to only master.
> Don't run tests twice on pull-requests

- app/helpers/form_helper.rb
When you passed an options hash including something below the data key, the merge would just override it. Now it merges them together.
> Use deep_merge to prevent overriding given options

- app/controllers/concerns/sortable.rb
We need to overwrite this in the tenants-wagon where the table-name of some models is qualified with a schema-name.
Prerequisite for https://github.com/hitobito/hitobito_tenants/pull/17
> Extract used table-name for subquery

- db/seeds/support/event_seeder.rb
Most of the time, when I try to test something in event applications, I have to edit the range of the dates for applications, I adjusted the range from 60 to 300 days, that way, the application window is more often still open per default and we still have random event, that are over or in the future :smile:
> extend range event applications are open in seeds

- spec/domain/people/household_list_spec.rb
Use contain_exactly to ignore the order.
Failing spec in https://github.com/hitobito/hitobito/actions/runs/10776426970/job/29883143659?pr=2832
```
1) People::HouseholdList#households_in_batches people scope with selects works
Failure/Error:
expect(yielded_batch.map { |household| household.map(&:id) }).to eq([
[person3.id,
person4.id, person6.id, person7.id],
[person1.id],
[person2.id],
[person5.id]
])
expected: [[572409569, 572409570, 572409572, 572409573], [572409567], [572409568], [572409571]]
got: [[572409573, 572409569, 572409570, 572409572], [572409567], [572409568], [572409571]]
```
> Fix flaky spec in household_list_spec

- app/models/custom_content.rb
To prevent errors when not converting to string in mailer (e.g. [here](https://github.com/hitobito/hitobito_sac_cas/blob/6d5c8a107255861685043ed792c5fe2f70434f83/app/mailers/signup/sektion_mailer.rb#L34))
> Convert custom content placeholders to string

- app/mailers/application_mailer.rb
- spec/mailers/application_mailer_spec.rb
xss ist möglich, wenn man z.b. `https://example.com/"></a><b>XSS</b><a/href="#` als link umfrage (link_survey) eingibt und im placeholder für `link_to(label, url = nil)` ein label setzt, weil die url teilweise nicht sanitized wird
> Prevent XSS in email URLs

- .github/actions/core-ci-setup/action.yml
- .github/workflows/tests.yml
- .github/workflows/wagon-tests.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- config/database.yml
This PR covers 3 aspects:
1. it drops support for sqlite3, which is not usable or needed for local development anymore.
2. it updates a config setting to the current version
3. it supports some more settings for the postgresql-connection. 
The newly supported settings are
- lock_timeout
- statement_timeout
Both help us to stop overly long-running queries and therefore stabilize the application. The actual settings are then done on the server/cluster with environment variables.
> Rework database config

- app/views/roles/_info.html.haml
Damit sind die Bullets der Liste wieder richtig ausgerichtet
**vorher** 
**nachher**
> Permission von Rolen im info aside richtig ausrichten

- app/decorators/event/participation_decorator.rb
- app/decorators/person_decorator.rb
- app/domain/person/event_queries.rb
- app/views/people/_attrs.html.haml
- app/views/people/_event_aside.html.haml
- app/views/people/_participation_aside.html.haml
- spec/decorators/event/participation_decorator.rb
- spec/decorators/person_decorator_spec.rb
- spec/regressions/people_controller_spec.rb
refs [hitobito_youth#85](https://github.com/hitobito/hitobito_youth/issues/85)
Auf der Person unter «Meine nächsten Anlässe» soll ein Link zur Anmeldung dieser Person haben. Zuerst war die Idee den bestehenden Link anzupassen, was aber zu Problemen bei Personen ohne Rollen hätte führen können. Deshalb wurde entschieden, einfach einen zusätzlichen Link einzufügen.
> feat: add button to get to participation (hitobito_jubla#85)

- app/models/person.rb
- spec/features/roles_controller_spec.rb
- spec/models/person_spec.rb
refs: hitobito/hitobito_sac_cas#1155
Mysterious error was found, when checkbox company was checked but no company_name was provided.
`tidy_bytes': undefined method `empty?' for nil:NilClass (NoMethodError) return string if string.empty? || string.ascii_only? Problem, was that to_s function returned nil, which should never happen.
> PEOPLE: fix missing company name leads to 404.

- .github/workflows/wagon-tests.yml
In the SAC project we had the issue from time to time, that changes in the code would break the seeds and thus interrupt the workflow of other developers which needed to reseed locally.
To avoid that we want to run the seeds during CI so we'd notice of a PR would beeak the seeds.
Actual CI run is here: https://github.com/hitobito/hitobito_sac_cas/pull/1047
> Run seeds in CI

- config/environments/production.rb
- spec/domain/tags/merger_spec.rb
It does not help across different services and prevents easy JSON-parsing of the log-lines. Therefore, a removal seems sensible.
> Remove Request-Identifier from logs

- app/javascript/controllers/form_field_check_dependent_controller.js
Configured with a stimulus value:
https://stimulus.hotwired.dev/reference/values
> Allow FormFieldCheckDependentController to check all dependent boxes

- .git-blame-ignore-revs
- Procfile
- Procfile.dev
- bin/active_wagon.rb
- bin/dev
- doc/developer/local_setup.md
Mit setzen von `BUNDLE_GEMFILE` kann man die Gemfile.lock Problematik fürs lokale entwickeln beheben. Da die Problematik allen zur genüge bekannt ist und wir deutlich mehr entwickeln als gems updaten wäre ich für die Lösung. 
Den rubocop reformatting commit 89f4f71d2153124421c8069db36837707ee57c2d aus der blame history rauszunehmen finde ich ebefalls sinnvoll. Was meint ihr? 
Falls wir das pushen wollen, wie verteilen wir die Infos am besten an den Rest vom Team?
> Dev setup improvements

- app/models/event/kind.rb
- app/views/events/_general_fields.html.haml
- spec/models/event/kind_spec.rb
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/1201
Mit diesem PR wird neu nach dem `short_name` sortiert (also der Wert **vor** der Klammer). Das macht aus meiner Sicht zumindest generisch mehr Sinn ~aber ich spreche das dann noch mit Tobi ab~ Tobi findets auch gut
> Order event kinds by short name

- app/controllers/group/person_add_requests_controller.rb
> Select person columns after order_by_name

- Gemfile
- Gemfile.lock
- app/views/people_filters/_filter.html.haml
- app/views/subscriber/filter/_form.html.haml
- app/views/subscriber/filter/_show.html.haml
- config/initializers/niceql.rb
Im SAC Wagon wollen wir zusätzliche subscriber filter implementieren.
Im Core sollen in den subscriber filter partials entsprechend die wagon extensions gerendert werden.
> Render wagon extensions in subscriber filter partials

- config/database.yml
As we have a lot of idle-connections, I want to set the timeout lower in integration-setups. For this, configuration through env-vars is needed.
> Make more DB-connection aspects configurable

- app/views/groups/_general_fields.html.haml
- spec/views/groups/_form.html.haml_spec.rb
I did not want to separate the fields and duplicate the static-name logic. Also, not autocompleting the group-name is probably a good idea anyway.
fixes hitobito/hitobito_jubla#170
> Prevent errors when using browser-autocomplete

- .rubocop_todo.yml
- app/domain/event/participant_assigner.rb
- spec/domain/event/participant_assigner_spec.rb
Due to the recent refactoring in https://github.com/hitobito/hitobito/pull/2769 the choice_items method is only implemented by Event::Question::Default
Fixes:
- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73536/?environment=integration
- https://help.puzzle.ch/#ticket/zoom/8560
> Do not depend on method that is not guaranteed for all questions

- app/helpers/upload_display_helper.rb
This fixes the `upload_url` helper to extract the image dimensions as integers. With the migration to Rails 7.0 the Active Storage variant processor was changed to `:vips` which raised an "no implicit conversion
of String into Integer" exception when encountering the stringified integers. See also
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-storage-default-variant-processor-changed-to-vips
> Fix profile pictures on person view

- app/decorators/group_decorator.rb
- app/helpers/roles_helper.rb
- app/models/group.rb
- app/models/role/types.rb
- app/views/groups/_self_registration_fields.html.haml
- config/locales/views.de.yml
- lib/tasks/hitobito.rake
- spec/controllers/groups/self_inscription_controller_spec.rb
- spec/controllers/groups/self_registration_controller_spec.rb
- spec/controllers/groups_controller_spec.rb
- spec/decorators/group_decorator_spec.rb
- spec/features/email_verification_spec.rb
- spec/models/wizards/inscribe_in_group_wizard_spec.rb
- spec/models/wizards/register_new_user_wizard_spec.rb
- spec/resources/group/reads_spec.rb
closes #2357 
Prüfen. ob es auf einer Instanz Gruppen mit Self-Registation gibt, die dann invalid sind:
```ruby
class SelfRegistrationRoleTypeChecker
def allowed_role_types_by_group_type(allowed_permissions = [])
Group.all_types.index_with do |group_type|
group_type.role_types.reject do |role_type|
role_type.restricted? || (role_type.permissions - allowed_permissions).any?
end
end
end
def offending_self_registrations
allowed_role_types_by_group_type.flat_map do |group_type, allowed_role_types|
Group.where(type: group_type.sti_name)
.where.not(self_registration_role_type: allowed_role_types.map(&:sti_name) + [nil])
end.compact
end
def check
offending_self_registrations.each do |group|
puts "Group ##{group.id} #{group.name} uses self registration with #{group.self_registration_role_type} …
```
> Externe Registrierung für Rollen mit Contact_Data

- app/domain/export/pdf/invoice/articles.rb
- spec/domain/export/pdf/invoice_spec.rb
This means:
- show text in a normal invoice
- show text on a reminder and the original text should be shown
- do not show it, if it is a reminder and the text should not be shown
The PR fixes #3124
> Show Invoice-Text unless configured otherwise

- app/utils/imap/connector.rb
Reduziert das noise im delayed job log
```
│ 2025-01-20T17:24:27+0100: [Worker(host:delayed-job-785b9b4556-jn7dd pid:1)] Job MailingLists::MailRetrieverJob (id=254583) RUNNING                                                                                                                                                                                           │
│ /app-src/app/utils/imap/connector.rb:97: warning: DEPRECATED: Call Net::IMAP.new with keyword options                                                                                                                                                                                                                        │
│ 2025-01-20T17:24:28+0100: [Worker(host:delayed-job-785b9b4556-jn7dd pid:1)] Job MailingLists::MailRetrieverJob …
```
> Replace deprecated imap constructor call

- app/controllers/concerns/render_table_displays.rb
- app/controllers/people_controller.rb
- app/domain/export/tabular/people/table_displays.rb
- app/domain/table_displays/column.rb
- app/domain/table_displays/people/primary_group_column.rb
- app/helpers/dropdown/table_displays.rb
- app/jobs/export/people_export_job.rb
- app/jobs/export/subscriptions_job.rb
- config/initializers/table_displays.rb
- spec/controllers/people_controller_spec.rb
- spec/domain/export/tabular/people/table_displays_spec.rb
- spec/domain/table_displays/people/login_status_column_spec.rb
- spec/domain/table_displays/people/primary_group_column_spec.rb
This Pull Request introduces #exclude_attr? which was an SAC implementation, to not display certain table display attributes in some groups.
This came with the issue that when a person selects an attribute, that does not exist in another group, the query is still trying to execute with the "excluded attr". That throws an error which is also fixed in this Pull Request (all columns that are `exclued_attr? = true`, will not be displayed/exported in any way, also when selected via a previous group/condition where it was possible)
> Add exlude_attr method to table displays column (hitobito/hitobito_sac_cas#1512)

- app/models/concerns/contactable.rb
- spec/models/person_spec.rb
this is required for the glp wagon where zip codes should not get validated
> Allow disabling of zip code validation (fixes hitobito/hitobito_sac_cas#1488)

- app/models/family_member.rb
- db/migrate/20240917160527_migrate_people_relations_to_family_members.rb
Refs https://github.com/hitobito/hitobito/issues/2402#event-14162177866
Das `PeopleRelation` Model wird nur noch bei der PBS eingesetzt, alle anderen sind auf `FamilyMember` (siehe [docs](https://github.com/hitobito/hitobito/blob/master/doc/developer/people/relational_constructs.md))
Diese Migration überführt die records ins neue Format.
fixes #2402
> feat: migrate all PeopleRelations to FamilyMembers

- app/abilities/person_readables.rb
- spec/abilities/person_readables_spec.rb
- spec/controllers/tags/merge_controller_spec.rb
Da der root user keine permissions hat und folglich `has_group_based_conditions?` immer `false` ist joinen wir dennoch Gruppen und Rollen, damit die TableDisplays, die Spalten von den Rollen anzeigen auch für den root user funktionieren.
> Fix table displays for root by using roles join

- app/models/event.rb
- config/locales/models.de.yml
- spec/features/quicksearch_spec.rb
- spec/models/event_spec.rb
fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74186 and  https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73987/ and https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74162
> Add default fallback when no event translation exists (#3140)

- lib/templates/wagon/spec/spec_helper.rb.tt
The warning said:
>  Rails 7.1 has deprecated the singular fixture_path in favour of an array.You should migrate to plural:
> Follow Deprecation-Warning

- db/migrate/20240513100000_split_addresses.rb
We know that this is desctructive, which is why there is a report to STDOUT, via mail and an a PaperTrail associated with the affected person-entry in the database.
See #3144
> When deleting addresses, do not validate

- CHANGELOG.md
- app/abilities/ability_dsl/constraints/person.rb
- app/abilities/person_ability.rb
- app/abilities/person_readables.rb
- app/domain/person/filter/base.rb
- app/domain/person/filter/chain.rb
- app/domain/person/filter/list.rb
- app/domain/person/filter/role.rb
- app/models/person.rb
- app/models/person/groups.rb
- app/models/role.rb
- config/settings.yml
- spec/abilities/person_ability_spec.rb
- spec/domain/person/filter/role_spec.rb
- spec/features/self_registration_spec.rb
- spec/models/role_spec.rb
Soll das noch ins Changelog, oder die zeile vom fix angepasst werden, zb. 
statt
> Filtern nach vergangenen Rollen zeigt nur Personen, welche für den User aktuell sichtbar sind (hitobito_sac_cas#1655)
statt
> Personen ohne aktive Rolle sind via Filter auf der Gruppe auf Basis ihrer vergangen Rollen, nach einem konfigurierbarem Zeitraum (aktuell sofort), nicht mehr auffindbar
(hitobito_sac_cas#1655)
Fraglich auch ob wir wirklich einen association wollen, ob uns das wo was kostet  oder weh tut. Sonst finde ich liest es sich so besser. Es scheint auch, dass für layer_permission kein ability change notwendig ist, das hab ich noch nicht ganz durchschaut warum das auch ohne geht
> Read inactive roles via person_readables if configured

- app/domain/person/subscriptions.rb
- spec/domain/person/subscriptions_spec.rb
This bug was found with real-life data on a hackathon.
> Even if I cannot subscribe myself, I can be subscribed

- app/models/invoice_list.rb
- app/models/role.rb
- spec/domain/invoice/batch_create_spec.rb
This prevents sending multiple invoices to a single person with multiple roles in group
Refs: hitobito/hitobito_sww#235
> Distinct people on invoice_list receiver

- app/domain/nil_array_coder.rb
- spec/domain/nil_array_coder_spec.rb
The columns for required and hidden contact attributes in events are serialized with this Coder. Previously, rails stored the data as YAML, the coder handles the data as JSON.
Since YAML is a superset of JSON, we can just use YAML to read everything and store new values as JSON.
See #3252
> Spec'n'fix NilArrayCoder

- app/domain/person/filter/attributes.rb
- app/helpers/people_filter_helper.rb
- app/helpers/person/filter/attribute_control.rb
- app/helpers/standard_form_builder.rb
- app/javascript/javascripts/modules/people/people_filter_attribute.js.coffee
- app/models/person.rb
- app/views/people_filters/_attributes.html.haml
- config/locales/views.de.yml
- spec/domain/person/filter/attributes_spec.rb
- spec/features/person/people_filter_spec.rb
- spec/models/person_spec.rb
This pull request adds the option to have different input field types in person filter, the country_select is for https://github.com/hitobito/hitobito_swb/issues/20 but also just for the country attibute in core, that users dont have to match for "CH" in a string field, I also added an integer field, with type integer. Date and string fields still work the same.
> Add different input_types to person filter

- app/domain/people/duplicate_conditions.rb
- app/domain/person/filter/attributes.rb
- app/domain/search_strategies/sql_condition_builder/matcher.rb
- app/models/additional_email.rb
- app/models/group.rb
- app/models/invoice.rb
- app/models/invoice_config.rb
- app/models/mail_log.rb
- app/models/mailing_list.rb
- app/models/message_recipient.rb
- app/models/person.rb
- app/views/contactable/_additional_address_fields.html.haml
- db/migrate/20250409131142_remove_case_insensitve_collation.rb
- db/schema.rb
- spec/api/people/index_spec.rb
- spec/controllers/people_controller_spec.rb
- spec/domain/people/duplicate_conditions_spec.rb
- spec/models/additional_email_spec.rb
- spec/models/group_spec.rb
- spec/models/invoice_config_spec.rb
- spec/models/invoice_spec.rb
- spec/models/mail_log_spec.rb
- spec/models/mailing_list_spec.rb
- spec/models/message_recipient_spec.rb
- spec/models/person_spec.rb
Downcasing all the current emails is still missing in the migration currently.
> Remove case_insensitive_emails collation (#3153)

- app/domain/structure_parser.rb
- lib/tasks/hitobito.rake
The current improvement round offers the following new features:
- nesting of layers (Root < Sublayer)
- validation of used permissions (no more typos)
- allow forcing the wanted class-name for roles (" -- (Group::SubGroup::RoleName)"-notation)
- direct creation of files
Also, there is now a DRY_RUN for the rake-task.
For consistency, the output of `hitobito:roles` has been extended. The role-classes are there optionally available via `hitobito:roles[true]`.
Some next steps are also shown, mostly so that I do not forget. Working with the new structure does not end with this, it only starts with this task.
> Structure parser Part II

- app/domain/table_displays/event/participations/question_column.rb
- app/views/event/participations/_answers.html.haml
Blank answers are also "not answered", I also disabled the option to select hidden questions in table displays, that use case isn't really needed.
> Improve some use cases of event questions

- lib/release/highlevel.rb
- lib/tasks/transifex.rake
The mode 'onlytranslated' omits reviewed translations. Therefore, we use the mode 'sourceastranslation' to avoid empty translations.
> Avoid empty translations by reusing the source

- app/utils/encryption_service.rb
- spec/models/payment_provider_config_spec.rb
Sentry: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76101
The decrypted value have an unknown encoding. As we only accept utf-8 for input-values, the resulting value (that we stored ourselves) needs be set to utf-8.
> Allow for unicode in encrypted passwords

- app/domain/export/tabular/event/participations/table_displays.rb
- spec/domain/export/tabular/people/table_displays_spec.rb
We don't want person table attrs inside our participation query :exploding_head:
> Use event participation as model_class for participation exports (#3353)

- app/helpers/dropdown/table_displays.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75649
Basically this error is possible when the event has an event question with an empty (nil) question. I would say we don't want to display those questions in the table displays
> Do not display empty label table display columns

- app/domain/mailing_lists/subscribers.rb
If this is not needed (as defined by spec-coverage), this removal would allow a the subscriber-exclusion to work on huge mailing_lists again.
> Remove maybe unneeded code

- .github/workflows/run-all-wagon-tests.yml
- .github/workflows/tests.yml
Before merging, this needs slight modifications to the tests.yml workflows in each wagon, i.e. add a distinct_id parameter and pass it to the reusable workflow, and also accept the wagon_dependency_ref parameter, even if it is unused.
To test this new workflow locally, I used the [act](https://nektosact.com/) plugin for github CLI:
```bash
gh extension install https://github.com/nektos/gh-act
docker pull catthehacker/ubuntu:full-latest # caution: takes up a lot of disk space!
gh act push -P ubuntu-latest=catthehacker/ubuntu:full-latest --pull=false -W .github/workflows/run-all-wagon-tests.yml -s WAGON_TESTS_GITHUB_TOKEN=github_pat_<redacted>
```
> Automate running all wagon tests on core changes #3442

- app/controllers/events_controller.rb
- spec/controllers/events_controller_spec.rb
- spec/fixtures/event/question_translations.yml
- spec/models/event_spec.rb
Bis wir eine Lösung fürs UI haben befülllen wir die Übersetzungen manuell im controller
refs hitobito/hitobito_swb#74
> Populate translations of derived questions in events_controller

- .github/workflows/run-all-wagon-tests.yml
After this change, it is the responsibility of the devs to trigger the wagon tests on each PR whenever they feel like it is the right time for it, by adding the `run-wagon-tests!` label. We will also install branch protection rules to ensure this happens before every merge.
(Overriding these rules will still be possible, and the wagon tests will still run on each push to master)
> Disable pull_request trigger for now

- lib/tasks/restore.rake
This helps mostly with french content as strings in postgres are being single-quoted.
> Restore: quote strings for inserts

- app/javascript/javascripts/modules/remote_autocomplete.js
> Escape query when replacing string to not display encodings in quicksearch

- app/controllers/group/merge_controller.rb
- app/domain/group/merger.rb
- spec/controllers/group/merge_controller_spec.rb
- spec/domain/group/merger_spec.rb
Refs #3475
Noch offen: Datenmigrationen im youth und pbs Wagon, um die tatsächlichen invaliden Events aufzuräumen, siehe Auflistung im Issue
> Fix group merging

- app/domain/invoice/batch_create.rb
- app/domain/invoice/batch_update.rb
- app/domain/messages/letter_dispatch.rb
- app/domain/messages/letter_with_invoice_dispatch.rb
- app/jobs/messages/dispatch_job.rb
- doc/developer/messages/dispatch.md
Updating the invoice-list with every created invoice add a lot of callback-overhead. Going over the list in batches (well, slices) allows us to do this only after 1000 invoices. This update takes more than a second, so the benefit of doing this more seldom should be clear.
While at it, this also fixes the success-count in the LetterDispatch which is shown in the UI.
> Improve message dispatch

- spec/domain/table_displays/people/primary_group_column_spec.rb
One example how to get an empty primary_group is when someone signs up to an external event. This person then has no roles, hence the primary_group is not set.
There must be some other cases though, since this happened when displaying a person list of a group, i.e. the people all have at least one role.
Refs https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76687/?query=is%3Aunresolved%20is%3Aunassigned
> Add tests for nil primary_group

- app/controllers/bounces_controller.rb
- spec/controllers/bounces_controller_spec.rb
Fixes #3518
Since the Model is used in different contexts, I put the autorization into the Controller.
> Grant some non-admins access to bounces of mailing-list

- spec/models/qualification_spec.rb
Sometimes the created qualification had an old date "2022-03-22". This is very unexpected, since the fabricator picks a date between 0 and 24 months ago. The root cause is still unclear.
Fixed by explicitly setting the `start_at` date, though I'm not sure if that actually fixes the problem.
fyi @amaierhofer
> Fix random failing qualification spec

- app/models/message/letter_with_invoice.rb
- config/locales/models.de.yml
- config/locales/models.en.yml
- config/locales/models.fr.yml
- config/locales/models.it.yml
- spec/models/message/letter_with_invoice_spec.rb
fixes hitobito#3342
Der Fehler ist aufgetreten wenn man ein PDF eines Rechnungsbriefes ohne Rechnungsposten erstellen wollte.
> Validate at least one invoice item for invoice messages (hitobito#3342)
